package com.evmtv.epg.entity;

import com.evmtv.epg.request.BaseRequest;

public class TContract extends BaseRequest{
    /**
	 * 
	 */
	private static final long serialVersionUID = 6641949288736635876L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.ID
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FGUID
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String fguid;
    /**
     * 广告位
     */
    private String fpositionid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FAdvName
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String fadvname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FAdvLocId
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private Integer fadvlocid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FAdvLevel
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String fadvlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FDefinition
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String fdefinition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FAgent
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String fagent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FBranchId
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private Long fbranchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FCreateTime
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String fcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FCreateUserId
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private Long fcreateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FUpdateTime
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String fupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FUpdateUserId
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private Long fupdateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FContactName
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String fcontactname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FContactTel
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String fcontacttel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FStartTime
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String fstarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FEndTime
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String fendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FPrice
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String fprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FDiscount
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String fdiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FPayWay
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String fpayway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FDeleted
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String fdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FChecked
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String fchecked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FFreezed
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String ffreezed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FTitle
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String ftitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FFilePath
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String ffilepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FFileTitle
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String ffiletitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.FPicTitle
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    private String fpictitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.ID
     *
     * @return the value of t_contract.ID
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.ID
     *
     * @param id the value for t_contract.ID
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FGUID
     *
     * @return the value of t_contract.FGUID
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFguid() {
        return fguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FGUID
     *
     * @param fguid the value for t_contract.FGUID
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFguid(String fguid) {
        this.fguid = fguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FAdvName
     *
     * @return the value of t_contract.FAdvName
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFadvname() {
        return fadvname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FAdvName
     *
     * @param fadvname the value for t_contract.FAdvName
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFadvname(String fadvname) {
        this.fadvname = fadvname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FAdvLocId
     *
     * @return the value of t_contract.FAdvLocId
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public Integer getFadvlocid() {
        return fadvlocid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FAdvLocId
     *
     * @param fadvlocid the value for t_contract.FAdvLocId
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFadvlocid(Integer fadvlocid) {
        this.fadvlocid = fadvlocid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FAdvLevel
     *
     * @return the value of t_contract.FAdvLevel
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFadvlevel() {
        return fadvlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FAdvLevel
     *
     * @param fadvlevel the value for t_contract.FAdvLevel
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFadvlevel(String fadvlevel) {
        this.fadvlevel = fadvlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FDefinition
     *
     * @return the value of t_contract.FDefinition
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFdefinition() {
        return fdefinition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FDefinition
     *
     * @param fdefinition the value for t_contract.FDefinition
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFdefinition(String fdefinition) {
        this.fdefinition = fdefinition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FAgent
     *
     * @return the value of t_contract.FAgent
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFagent() {
        return fagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FAgent
     *
     * @param fagent the value for t_contract.FAgent
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFagent(String fagent) {
        this.fagent = fagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FBranchId
     *
     * @return the value of t_contract.FBranchId
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public Long getFbranchid() {
        return fbranchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FBranchId
     *
     * @param fbranchid the value for t_contract.FBranchId
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFbranchid(Long fbranchid) {
        this.fbranchid = fbranchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FCreateTime
     *
     * @return the value of t_contract.FCreateTime
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFcreatetime() {
        return fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FCreateTime
     *
     * @param fcreatetime the value for t_contract.FCreateTime
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFcreatetime(String fcreatetime) {
        this.fcreatetime = fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FCreateUserId
     *
     * @return the value of t_contract.FCreateUserId
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public Long getFcreateuserid() {
        return fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FCreateUserId
     *
     * @param fcreateuserid the value for t_contract.FCreateUserId
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFcreateuserid(Long fcreateuserid) {
        this.fcreateuserid = fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FUpdateTime
     *
     * @return the value of t_contract.FUpdateTime
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFupdatetime() {
        return fupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FUpdateTime
     *
     * @param fupdatetime the value for t_contract.FUpdateTime
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFupdatetime(String fupdatetime) {
        this.fupdatetime = fupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FUpdateUserId
     *
     * @return the value of t_contract.FUpdateUserId
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public Long getFupdateuserid() {
        return fupdateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FUpdateUserId
     *
     * @param fupdateuserid the value for t_contract.FUpdateUserId
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFupdateuserid(Long fupdateuserid) {
        this.fupdateuserid = fupdateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FContactName
     *
     * @return the value of t_contract.FContactName
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFcontactname() {
        return fcontactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FContactName
     *
     * @param fcontactname the value for t_contract.FContactName
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFcontactname(String fcontactname) {
        this.fcontactname = fcontactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FContactTel
     *
     * @return the value of t_contract.FContactTel
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFcontacttel() {
        return fcontacttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FContactTel
     *
     * @param fcontacttel the value for t_contract.FContactTel
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFcontacttel(String fcontacttel) {
        this.fcontacttel = fcontacttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FStartTime
     *
     * @return the value of t_contract.FStartTime
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFstarttime() {
        return fstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FStartTime
     *
     * @param fstarttime the value for t_contract.FStartTime
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFstarttime(String fstarttime) {
        this.fstarttime = fstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FEndTime
     *
     * @return the value of t_contract.FEndTime
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFendtime() {
        return fendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FEndTime
     *
     * @param fendtime the value for t_contract.FEndTime
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFendtime(String fendtime) {
        this.fendtime = fendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FPrice
     *
     * @return the value of t_contract.FPrice
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFprice() {
        return fprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FPrice
     *
     * @param fprice the value for t_contract.FPrice
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFprice(String fprice) {
        this.fprice = fprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FDiscount
     *
     * @return the value of t_contract.FDiscount
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFdiscount() {
        return fdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FDiscount
     *
     * @param fdiscount the value for t_contract.FDiscount
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFdiscount(String fdiscount) {
        this.fdiscount = fdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FPayWay
     *
     * @return the value of t_contract.FPayWay
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFpayway() {
        return fpayway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FPayWay
     *
     * @param fpayway the value for t_contract.FPayWay
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFpayway(String fpayway) {
        this.fpayway = fpayway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FDeleted
     *
     * @return the value of t_contract.FDeleted
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFdeleted() {
        return fdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FDeleted
     *
     * @param fdeleted the value for t_contract.FDeleted
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFdeleted(String fdeleted) {
        this.fdeleted = fdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FChecked
     *
     * @return the value of t_contract.FChecked
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFchecked() {
        return fchecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FChecked
     *
     * @param fchecked the value for t_contract.FChecked
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFchecked(String fchecked) {
        this.fchecked = fchecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FFreezed
     *
     * @return the value of t_contract.FFreezed
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFfreezed() {
        return ffreezed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FFreezed
     *
     * @param ffreezed the value for t_contract.FFreezed
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFfreezed(String ffreezed) {
        this.ffreezed = ffreezed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FTitle
     *
     * @return the value of t_contract.FTitle
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFtitle() {
        return ftitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FTitle
     *
     * @param ftitle the value for t_contract.FTitle
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFtitle(String ftitle) {
        this.ftitle = ftitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FFilePath
     *
     * @return the value of t_contract.FFilePath
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFfilepath() {
        return ffilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FFilePath
     *
     * @param ffilepath the value for t_contract.FFilePath
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFfilepath(String ffilepath) {
        this.ffilepath = ffilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FFileTitle
     *
     * @return the value of t_contract.FFileTitle
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFfiletitle() {
        return ffiletitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FFileTitle
     *
     * @param ffiletitle the value for t_contract.FFileTitle
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFfiletitle(String ffiletitle) {
        this.ffiletitle = ffiletitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.FPicTitle
     *
     * @return the value of t_contract.FPicTitle
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getFpictitle() {
        return fpictitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.FPicTitle
     *
     * @param fpictitle the value for t_contract.FPicTitle
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setFpictitle(String fpictitle) {
        this.fpictitle = fpictitle;
    }

	public String getFpositionid() {
		return fpositionid;
	}

	public void setFpositionid(String fpositionid) {
		this.fpositionid = fpositionid;
	}
}