package com.evmtv.epg.mapper;

import com.evmtv.epg.entity.TBranchAdvclass;
import com.evmtv.epg.entity.TBranchAdvclassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBranchAdvclassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_advclass
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    int countByExample(TBranchAdvclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_advclass
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    int deleteByExample(TBranchAdvclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_advclass
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_advclass
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    int insert(TBranchAdvclass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_advclass
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    int insertSelective(TBranchAdvclass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_advclass
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    List<TBranchAdvclass> selectByExample(TBranchAdvclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_advclass
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    TBranchAdvclass selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_advclass
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    int updateByExampleSelective(@Param("record") TBranchAdvclass record, @Param("example") TBranchAdvclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_advclass
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    int updateByExample(@Param("record") TBranchAdvclass record, @Param("example") TBranchAdvclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_advclass
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    int updateByPrimaryKeySelective(TBranchAdvclass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_advclass
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    int updateByPrimaryKey(TBranchAdvclass record);

	List<Long> selectByBranchId(TBranchAdvclassExample example);
}