package com.evmtv.epg.entity;

public class TSourceChannels {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_source_channels.ID
     *
     * @mbggenerated Fri Nov 08 15:56:35 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_source_channels.FChannelsId
     *
     * @mbggenerated Fri Nov 08 15:56:35 CST 2013
     */
    private Long fchannelsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_source_channels.FSourceId
     *
     * @mbggenerated Fri Nov 08 15:56:35 CST 2013
     */
    private Long fsourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_source_channels.FReleaseVersionId
     *
     * @mbggenerated Fri Nov 08 15:56:35 CST 2013
     */
    private Long freleaseversionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_source_channels.FChannelGroupsId
     *
     * @mbggenerated Fri Nov 08 15:56:35 CST 2013
     */
    private Long fchannelgroupsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_source_channels.ID
     *
     * @return the value of t_source_channels.ID
     *
     * @mbggenerated Fri Nov 08 15:56:35 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_source_channels.ID
     *
     * @param id the value for t_source_channels.ID
     *
     * @mbggenerated Fri Nov 08 15:56:35 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_source_channels.FChannelsId
     *
     * @return the value of t_source_channels.FChannelsId
     *
     * @mbggenerated Fri Nov 08 15:56:35 CST 2013
     */
    public Long getFchannelsid() {
        return fchannelsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_source_channels.FChannelsId
     *
     * @param fchannelsid the value for t_source_channels.FChannelsId
     *
     * @mbggenerated Fri Nov 08 15:56:35 CST 2013
     */
    public void setFchannelsid(Long fchannelsid) {
        this.fchannelsid = fchannelsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_source_channels.FSourceId
     *
     * @return the value of t_source_channels.FSourceId
     *
     * @mbggenerated Fri Nov 08 15:56:35 CST 2013
     */
    public Long getFsourceid() {
        return fsourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_source_channels.FSourceId
     *
     * @param fsourceid the value for t_source_channels.FSourceId
     *
     * @mbggenerated Fri Nov 08 15:56:35 CST 2013
     */
    public void setFsourceid(Long fsourceid) {
        this.fsourceid = fsourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_source_channels.FReleaseVersionId
     *
     * @return the value of t_source_channels.FReleaseVersionId
     *
     * @mbggenerated Fri Nov 08 15:56:35 CST 2013
     */
    public Long getFreleaseversionid() {
        return freleaseversionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_source_channels.FReleaseVersionId
     *
     * @param freleaseversionid the value for t_source_channels.FReleaseVersionId
     *
     * @mbggenerated Fri Nov 08 15:56:35 CST 2013
     */
    public void setFreleaseversionid(Long freleaseversionid) {
        this.freleaseversionid = freleaseversionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_source_channels.FChannelGroupsId
     *
     * @return the value of t_source_channels.FChannelGroupsId
     *
     * @mbggenerated Fri Nov 08 15:56:35 CST 2013
     */
    public Long getFchannelgroupsid() {
        return fchannelgroupsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_source_channels.FChannelGroupsId
     *
     * @param fchannelgroupsid the value for t_source_channels.FChannelGroupsId
     *
     * @mbggenerated Fri Nov 08 15:56:35 CST 2013
     */
    public void setFchannelgroupsid(Long fchannelgroupsid) {
        this.fchannelgroupsid = fchannelgroupsid;
    }
}