package com.evmtv.epg.entity;

import java.util.ArrayList;
import java.util.List;

import com.evmtv.epg.request.BaseRequest;

public class TUserExample extends BaseRequest{
    /**
	 * @field serialVersionUID
	 * @field_type long
	 */
	private static final long serialVersionUID = -8707436662038182092L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    public TUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIsNull() {
            addCriterion("FCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIsNotNull() {
            addCriterion("FCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeEqualTo(String value) {
            addCriterion("FCreateTime =", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotEqualTo(String value) {
            addCriterion("FCreateTime <>", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeGreaterThan(String value) {
            addCriterion("FCreateTime >", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("FCreateTime >=", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLessThan(String value) {
            addCriterion("FCreateTime <", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLessThanOrEqualTo(String value) {
            addCriterion("FCreateTime <=", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLike(String value) {
            addCriterion("FCreateTime like", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotLike(String value) {
            addCriterion("FCreateTime not like", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIn(List<String> values) {
            addCriterion("FCreateTime in", values, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotIn(List<String> values) {
            addCriterion("FCreateTime not in", values, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeBetween(String value1, String value2) {
            addCriterion("FCreateTime between", value1, value2, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotBetween(String value1, String value2) {
            addCriterion("FCreateTime not between", value1, value2, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIsNull() {
            addCriterion("FCreateUserId is null");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIsNotNull() {
            addCriterion("FCreateUserId is not null");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridEqualTo(Long value) {
            addCriterion("FCreateUserId =", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotEqualTo(Long value) {
            addCriterion("FCreateUserId <>", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridGreaterThan(Long value) {
            addCriterion("FCreateUserId >", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridGreaterThanOrEqualTo(Long value) {
            addCriterion("FCreateUserId >=", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridLessThan(Long value) {
            addCriterion("FCreateUserId <", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridLessThanOrEqualTo(Long value) {
            addCriterion("FCreateUserId <=", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIn(List<Long> values) {
            addCriterion("FCreateUserId in", values, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotIn(List<Long> values) {
            addCriterion("FCreateUserId not in", values, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridBetween(Long value1, Long value2) {
            addCriterion("FCreateUserId between", value1, value2, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotBetween(Long value1, Long value2) {
            addCriterion("FCreateUserId not between", value1, value2, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIsNull() {
            addCriterion("FUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIsNotNull() {
            addCriterion("FUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeEqualTo(String value) {
            addCriterion("FUpdateTime =", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotEqualTo(String value) {
            addCriterion("FUpdateTime <>", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeGreaterThan(String value) {
            addCriterion("FUpdateTime >", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("FUpdateTime >=", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLessThan(String value) {
            addCriterion("FUpdateTime <", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLessThanOrEqualTo(String value) {
            addCriterion("FUpdateTime <=", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLike(String value) {
            addCriterion("FUpdateTime like", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotLike(String value) {
            addCriterion("FUpdateTime not like", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIn(List<String> values) {
            addCriterion("FUpdateTime in", values, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotIn(List<String> values) {
            addCriterion("FUpdateTime not in", values, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeBetween(String value1, String value2) {
            addCriterion("FUpdateTime between", value1, value2, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotBetween(String value1, String value2) {
            addCriterion("FUpdateTime not between", value1, value2, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridIsNull() {
            addCriterion("FUpdateUserId is null");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridIsNotNull() {
            addCriterion("FUpdateUserId is not null");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridEqualTo(Long value) {
            addCriterion("FUpdateUserId =", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridNotEqualTo(Long value) {
            addCriterion("FUpdateUserId <>", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridGreaterThan(Long value) {
            addCriterion("FUpdateUserId >", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridGreaterThanOrEqualTo(Long value) {
            addCriterion("FUpdateUserId >=", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridLessThan(Long value) {
            addCriterion("FUpdateUserId <", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridLessThanOrEqualTo(Long value) {
            addCriterion("FUpdateUserId <=", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridIn(List<Long> values) {
            addCriterion("FUpdateUserId in", values, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridNotIn(List<Long> values) {
            addCriterion("FUpdateUserId not in", values, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridBetween(Long value1, Long value2) {
            addCriterion("FUpdateUserId between", value1, value2, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridNotBetween(Long value1, Long value2) {
            addCriterion("FUpdateUserId not between", value1, value2, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFfreezedIsNull() {
            addCriterion("FFreezed is null");
            return (Criteria) this;
        }

        public Criteria andFfreezedIsNotNull() {
            addCriterion("FFreezed is not null");
            return (Criteria) this;
        }

        public Criteria andFfreezedEqualTo(String value) {
            addCriterion("FFreezed =", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedNotEqualTo(String value) {
            addCriterion("FFreezed <>", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedGreaterThan(String value) {
            addCriterion("FFreezed >", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedGreaterThanOrEqualTo(String value) {
            addCriterion("FFreezed >=", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedLessThan(String value) {
            addCriterion("FFreezed <", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedLessThanOrEqualTo(String value) {
            addCriterion("FFreezed <=", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedLike(String value) {
            addCriterion("FFreezed like", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedNotLike(String value) {
            addCriterion("FFreezed not like", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedIn(List<String> values) {
            addCriterion("FFreezed in", values, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedNotIn(List<String> values) {
            addCriterion("FFreezed not in", values, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedBetween(String value1, String value2) {
            addCriterion("FFreezed between", value1, value2, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedNotBetween(String value1, String value2) {
            addCriterion("FFreezed not between", value1, value2, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFdeletedIsNull() {
            addCriterion("FDeleted is null");
            return (Criteria) this;
        }

        public Criteria andFdeletedIsNotNull() {
            addCriterion("FDeleted is not null");
            return (Criteria) this;
        }

        public Criteria andFdeletedEqualTo(String value) {
            addCriterion("FDeleted =", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedNotEqualTo(String value) {
            addCriterion("FDeleted <>", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedGreaterThan(String value) {
            addCriterion("FDeleted >", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedGreaterThanOrEqualTo(String value) {
            addCriterion("FDeleted >=", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedLessThan(String value) {
            addCriterion("FDeleted <", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedLessThanOrEqualTo(String value) {
            addCriterion("FDeleted <=", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedLike(String value) {
            addCriterion("FDeleted like", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedNotLike(String value) {
            addCriterion("FDeleted not like", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedIn(List<String> values) {
            addCriterion("FDeleted in", values, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedNotIn(List<String> values) {
            addCriterion("FDeleted not in", values, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedBetween(String value1, String value2) {
            addCriterion("FDeleted between", value1, value2, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedNotBetween(String value1, String value2) {
            addCriterion("FDeleted not between", value1, value2, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFguidIsNull() {
            addCriterion("FGUID is null");
            return (Criteria) this;
        }

        public Criteria andFguidIsNotNull() {
            addCriterion("FGUID is not null");
            return (Criteria) this;
        }

        public Criteria andFguidEqualTo(String value) {
            addCriterion("FGUID =", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidNotEqualTo(String value) {
            addCriterion("FGUID <>", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidGreaterThan(String value) {
            addCriterion("FGUID >", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidGreaterThanOrEqualTo(String value) {
            addCriterion("FGUID >=", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidLessThan(String value) {
            addCriterion("FGUID <", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidLessThanOrEqualTo(String value) {
            addCriterion("FGUID <=", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidLike(String value) {
            addCriterion("FGUID like", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidNotLike(String value) {
            addCriterion("FGUID not like", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidIn(List<String> values) {
            addCriterion("FGUID in", values, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidNotIn(List<String> values) {
            addCriterion("FGUID not in", values, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidBetween(String value1, String value2) {
            addCriterion("FGUID between", value1, value2, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidNotBetween(String value1, String value2) {
            addCriterion("FGUID not between", value1, value2, "fguid");
            return (Criteria) this;
        }

        public Criteria andFnameIsNull() {
            addCriterion("FName is null");
            return (Criteria) this;
        }

        public Criteria andFnameIsNotNull() {
            addCriterion("FName is not null");
            return (Criteria) this;
        }

        public Criteria andFnameEqualTo(String value) {
            addCriterion("FName =", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotEqualTo(String value) {
            addCriterion("FName <>", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameGreaterThan(String value) {
            addCriterion("FName >", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameGreaterThanOrEqualTo(String value) {
            addCriterion("FName >=", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameLessThan(String value) {
            addCriterion("FName <", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameLessThanOrEqualTo(String value) {
            addCriterion("FName <=", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameLike(String value) {
            addCriterion("FName like", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotLike(String value) {
            addCriterion("FName not like", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameIn(List<String> values) {
            addCriterion("FName in", values, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotIn(List<String> values) {
            addCriterion("FName not in", values, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameBetween(String value1, String value2) {
            addCriterion("FName between", value1, value2, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotBetween(String value1, String value2) {
            addCriterion("FName not between", value1, value2, "fname");
            return (Criteria) this;
        }

        public Criteria andFusernameIsNull() {
            addCriterion("FUserName is null");
            return (Criteria) this;
        }

        public Criteria andFusernameIsNotNull() {
            addCriterion("FUserName is not null");
            return (Criteria) this;
        }

        public Criteria andFusernameEqualTo(String value) {
            addCriterion("FUserName =", value, "fusername");
            return (Criteria) this;
        }

        public Criteria andFusernameNotEqualTo(String value) {
            addCriterion("FUserName <>", value, "fusername");
            return (Criteria) this;
        }

        public Criteria andFusernameGreaterThan(String value) {
            addCriterion("FUserName >", value, "fusername");
            return (Criteria) this;
        }

        public Criteria andFusernameGreaterThanOrEqualTo(String value) {
            addCriterion("FUserName >=", value, "fusername");
            return (Criteria) this;
        }

        public Criteria andFusernameLessThan(String value) {
            addCriterion("FUserName <", value, "fusername");
            return (Criteria) this;
        }

        public Criteria andFusernameLessThanOrEqualTo(String value) {
            addCriterion("FUserName <=", value, "fusername");
            return (Criteria) this;
        }

        public Criteria andFusernameLike(String value) {
            addCriterion("FUserName like", value, "fusername");
            return (Criteria) this;
        }

        public Criteria andFusernameNotLike(String value) {
            addCriterion("FUserName not like", value, "fusername");
            return (Criteria) this;
        }

        public Criteria andFusernameIn(List<String> values) {
            addCriterion("FUserName in", values, "fusername");
            return (Criteria) this;
        }

        public Criteria andFusernameNotIn(List<String> values) {
            addCriterion("FUserName not in", values, "fusername");
            return (Criteria) this;
        }

        public Criteria andFusernameBetween(String value1, String value2) {
            addCriterion("FUserName between", value1, value2, "fusername");
            return (Criteria) this;
        }

        public Criteria andFusernameNotBetween(String value1, String value2) {
            addCriterion("FUserName not between", value1, value2, "fusername");
            return (Criteria) this;
        }

        public Criteria andFpasswordIsNull() {
            addCriterion("FPassword is null");
            return (Criteria) this;
        }

        public Criteria andFpasswordIsNotNull() {
            addCriterion("FPassword is not null");
            return (Criteria) this;
        }

        public Criteria andFpasswordEqualTo(String value) {
            addCriterion("FPassword =", value, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordNotEqualTo(String value) {
            addCriterion("FPassword <>", value, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordGreaterThan(String value) {
            addCriterion("FPassword >", value, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordGreaterThanOrEqualTo(String value) {
            addCriterion("FPassword >=", value, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordLessThan(String value) {
            addCriterion("FPassword <", value, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordLessThanOrEqualTo(String value) {
            addCriterion("FPassword <=", value, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordLike(String value) {
            addCriterion("FPassword like", value, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordNotLike(String value) {
            addCriterion("FPassword not like", value, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordIn(List<String> values) {
            addCriterion("FPassword in", values, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordNotIn(List<String> values) {
            addCriterion("FPassword not in", values, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordBetween(String value1, String value2) {
            addCriterion("FPassword between", value1, value2, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordNotBetween(String value1, String value2) {
            addCriterion("FPassword not between", value1, value2, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFdepartIsNull() {
            addCriterion("FDepart is null");
            return (Criteria) this;
        }

        public Criteria andFdepartIsNotNull() {
            addCriterion("FDepart is not null");
            return (Criteria) this;
        }

        public Criteria andFdepartEqualTo(String value) {
            addCriterion("FDepart =", value, "fdepart");
            return (Criteria) this;
        }

        public Criteria andFdepartNotEqualTo(String value) {
            addCriterion("FDepart <>", value, "fdepart");
            return (Criteria) this;
        }

        public Criteria andFdepartGreaterThan(String value) {
            addCriterion("FDepart >", value, "fdepart");
            return (Criteria) this;
        }

        public Criteria andFdepartGreaterThanOrEqualTo(String value) {
            addCriterion("FDepart >=", value, "fdepart");
            return (Criteria) this;
        }

        public Criteria andFdepartLessThan(String value) {
            addCriterion("FDepart <", value, "fdepart");
            return (Criteria) this;
        }

        public Criteria andFdepartLessThanOrEqualTo(String value) {
            addCriterion("FDepart <=", value, "fdepart");
            return (Criteria) this;
        }

        public Criteria andFdepartLike(String value) {
            addCriterion("FDepart like", value, "fdepart");
            return (Criteria) this;
        }

        public Criteria andFdepartNotLike(String value) {
            addCriterion("FDepart not like", value, "fdepart");
            return (Criteria) this;
        }

        public Criteria andFdepartIn(List<String> values) {
            addCriterion("FDepart in", values, "fdepart");
            return (Criteria) this;
        }

        public Criteria andFdepartNotIn(List<String> values) {
            addCriterion("FDepart not in", values, "fdepart");
            return (Criteria) this;
        }

        public Criteria andFdepartBetween(String value1, String value2) {
            addCriterion("FDepart between", value1, value2, "fdepart");
            return (Criteria) this;
        }

        public Criteria andFdepartNotBetween(String value1, String value2) {
            addCriterion("FDepart not between", value1, value2, "fdepart");
            return (Criteria) this;
        }

        public Criteria andFpostIsNull() {
            addCriterion("FPost is null");
            return (Criteria) this;
        }

        public Criteria andFpostIsNotNull() {
            addCriterion("FPost is not null");
            return (Criteria) this;
        }

        public Criteria andFpostEqualTo(String value) {
            addCriterion("FPost =", value, "fpost");
            return (Criteria) this;
        }

        public Criteria andFpostNotEqualTo(String value) {
            addCriterion("FPost <>", value, "fpost");
            return (Criteria) this;
        }

        public Criteria andFpostGreaterThan(String value) {
            addCriterion("FPost >", value, "fpost");
            return (Criteria) this;
        }

        public Criteria andFpostGreaterThanOrEqualTo(String value) {
            addCriterion("FPost >=", value, "fpost");
            return (Criteria) this;
        }

        public Criteria andFpostLessThan(String value) {
            addCriterion("FPost <", value, "fpost");
            return (Criteria) this;
        }

        public Criteria andFpostLessThanOrEqualTo(String value) {
            addCriterion("FPost <=", value, "fpost");
            return (Criteria) this;
        }

        public Criteria andFpostLike(String value) {
            addCriterion("FPost like", value, "fpost");
            return (Criteria) this;
        }

        public Criteria andFpostNotLike(String value) {
            addCriterion("FPost not like", value, "fpost");
            return (Criteria) this;
        }

        public Criteria andFpostIn(List<String> values) {
            addCriterion("FPost in", values, "fpost");
            return (Criteria) this;
        }

        public Criteria andFpostNotIn(List<String> values) {
            addCriterion("FPost not in", values, "fpost");
            return (Criteria) this;
        }

        public Criteria andFpostBetween(String value1, String value2) {
            addCriterion("FPost between", value1, value2, "fpost");
            return (Criteria) this;
        }

        public Criteria andFpostNotBetween(String value1, String value2) {
            addCriterion("FPost not between", value1, value2, "fpost");
            return (Criteria) this;
        }

        public Criteria andFcompanyIsNull() {
            addCriterion("FCompany is null");
            return (Criteria) this;
        }

        public Criteria andFcompanyIsNotNull() {
            addCriterion("FCompany is not null");
            return (Criteria) this;
        }

        public Criteria andFcompanyEqualTo(String value) {
            addCriterion("FCompany =", value, "fcompany");
            return (Criteria) this;
        }

        public Criteria andFcompanyNotEqualTo(String value) {
            addCriterion("FCompany <>", value, "fcompany");
            return (Criteria) this;
        }

        public Criteria andFcompanyGreaterThan(String value) {
            addCriterion("FCompany >", value, "fcompany");
            return (Criteria) this;
        }

        public Criteria andFcompanyGreaterThanOrEqualTo(String value) {
            addCriterion("FCompany >=", value, "fcompany");
            return (Criteria) this;
        }

        public Criteria andFcompanyLessThan(String value) {
            addCriterion("FCompany <", value, "fcompany");
            return (Criteria) this;
        }

        public Criteria andFcompanyLessThanOrEqualTo(String value) {
            addCriterion("FCompany <=", value, "fcompany");
            return (Criteria) this;
        }

        public Criteria andFcompanyLike(String value) {
            addCriterion("FCompany like", value, "fcompany");
            return (Criteria) this;
        }

        public Criteria andFcompanyNotLike(String value) {
            addCriterion("FCompany not like", value, "fcompany");
            return (Criteria) this;
        }

        public Criteria andFcompanyIn(List<String> values) {
            addCriterion("FCompany in", values, "fcompany");
            return (Criteria) this;
        }

        public Criteria andFcompanyNotIn(List<String> values) {
            addCriterion("FCompany not in", values, "fcompany");
            return (Criteria) this;
        }

        public Criteria andFcompanyBetween(String value1, String value2) {
            addCriterion("FCompany between", value1, value2, "fcompany");
            return (Criteria) this;
        }

        public Criteria andFcompanyNotBetween(String value1, String value2) {
            addCriterion("FCompany not between", value1, value2, "fcompany");
            return (Criteria) this;
        }

        public Criteria andFbranchidIsNull() {
            addCriterion("FBranchId is null");
            return (Criteria) this;
        }

        public Criteria andFbranchidIsNotNull() {
            addCriterion("FBranchId is not null");
            return (Criteria) this;
        }

        public Criteria andFbranchidEqualTo(Long value) {
            addCriterion("FBranchId =", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidNotEqualTo(Long value) {
            addCriterion("FBranchId <>", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidGreaterThan(Long value) {
            addCriterion("FBranchId >", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidGreaterThanOrEqualTo(Long value) {
            addCriterion("FBranchId >=", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidLessThan(Long value) {
            addCriterion("FBranchId <", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidLessThanOrEqualTo(Long value) {
            addCriterion("FBranchId <=", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidIn(List<Long> values) {
            addCriterion("FBranchId in", values, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidNotIn(List<Long> values) {
            addCriterion("FBranchId not in", values, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidBetween(Long value1, Long value2) {
            addCriterion("FBranchId between", value1, value2, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidNotBetween(Long value1, Long value2) {
            addCriterion("FBranchId not between", value1, value2, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidIsNull() {
            addCriterion("FUserGroupId is null");
            return (Criteria) this;
        }

        public Criteria andFusergroupidIsNotNull() {
            addCriterion("FUserGroupId is not null");
            return (Criteria) this;
        }

        public Criteria andFusergroupidEqualTo(Long value) {
            addCriterion("FUserGroupId =", value, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidNotEqualTo(Long value) {
            addCriterion("FUserGroupId <>", value, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidGreaterThan(Long value) {
            addCriterion("FUserGroupId >", value, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidGreaterThanOrEqualTo(Long value) {
            addCriterion("FUserGroupId >=", value, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidLessThan(Long value) {
            addCriterion("FUserGroupId <", value, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidLessThanOrEqualTo(Long value) {
            addCriterion("FUserGroupId <=", value, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidIn(List<Long> values) {
            addCriterion("FUserGroupId in", values, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidNotIn(List<Long> values) {
            addCriterion("FUserGroupId not in", values, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidBetween(Long value1, Long value2) {
            addCriterion("FUserGroupId between", value1, value2, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidNotBetween(Long value1, Long value2) {
            addCriterion("FUserGroupId not between", value1, value2, "fusergroupid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 10 15:05:53 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}