package com.evmtv.epg.mapper;

import com.evmtv.epg.entity.TTimePeriod;
import com.evmtv.epg.entity.TTimePeriodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TTimePeriodMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_period
     *
     * @mbggenerated Mon Nov 11 05:58:46 CST 2013
     */
    int countByExample(TTimePeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_period
     *
     * @mbggenerated Mon Nov 11 05:58:46 CST 2013
     */
    int deleteByExample(TTimePeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_period
     *
     * @mbggenerated Mon Nov 11 05:58:46 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_period
     *
     * @mbggenerated Mon Nov 11 05:58:46 CST 2013
     */
    int insert(TTimePeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_period
     *
     * @mbggenerated Mon Nov 11 05:58:46 CST 2013
     */
    int insertSelective(TTimePeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_period
     *
     * @mbggenerated Mon Nov 11 05:58:46 CST 2013
     */
    List<TTimePeriod> selectByExample(TTimePeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_period
     *
     * @mbggenerated Mon Nov 11 05:58:46 CST 2013
     */
    TTimePeriod selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_period
     *
     * @mbggenerated Mon Nov 11 05:58:46 CST 2013
     */
    int updateByExampleSelective(@Param("record") TTimePeriod record, @Param("example") TTimePeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_period
     *
     * @mbggenerated Mon Nov 11 05:58:46 CST 2013
     */
    int updateByExample(@Param("record") TTimePeriod record, @Param("example") TTimePeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_period
     *
     * @mbggenerated Mon Nov 11 05:58:46 CST 2013
     */
    int updateByPrimaryKeySelective(TTimePeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_period
     *
     * @mbggenerated Mon Nov 11 05:58:46 CST 2013
     */
    int updateByPrimaryKey(TTimePeriod record);
    /**
     * 分公司时间段
     * @param example
     * @return
     */
    List<TTimePeriod> selectBranchTimeByExample(TTimePeriodExample example);
    /**
     * 检查时间段是否重复
     * @param period
     * @return
     */
    int selectCheckRepeat(TTimePeriod period);
}