package com.evmtv.epg.entity;

import com.evmtv.epg.request.BaseRequest;

public class TBranchAdvclass extends BaseRequest{
    /**
	 * 
	 */
	private static final long serialVersionUID = -4316324793094859400L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_advclass.ID
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_advclass.FAdvClassId
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    private Long fadvclassid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_advclass.FBranchId
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    private Long fbranchid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_advclass.ID
     *
     * @return the value of t_branch_advclass.ID
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_advclass.ID
     *
     * @param id the value for t_branch_advclass.ID
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_advclass.FAdvClassId
     *
     * @return the value of t_branch_advclass.FAdvClassId
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    public Long getFadvclassid() {
        return fadvclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_advclass.FAdvClassId
     *
     * @param fadvclassid the value for t_branch_advclass.FAdvClassId
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    public void setFadvclassid(Long fadvclassid) {
        this.fadvclassid = fadvclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_advclass.FBranchId
     *
     * @return the value of t_branch_advclass.FBranchId
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    public Long getFbranchid() {
        return fbranchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_advclass.FBranchId
     *
     * @param fbranchid the value for t_branch_advclass.FBranchId
     *
     * @mbggenerated Wed Jul 10 11:09:29 CST 2013
     */
    public void setFbranchid(Long fbranchid) {
        this.fbranchid = fbranchid;
    }
}