package com.evmtv.epg.entity;

import java.util.ArrayList;
import java.util.List;

import com.evmtv.epg.request.BaseRequest;

public class TBranchExample extends BaseRequest{
    /**
	 * @field serialVersionUID
	 * @field_type long
	 */
	private static final long serialVersionUID = -759242953454740569L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    public TBranchExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIsNull() {
            addCriterion("FCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIsNotNull() {
            addCriterion("FCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeEqualTo(String value) {
            addCriterion("FCreateTime =", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotEqualTo(String value) {
            addCriterion("FCreateTime <>", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeGreaterThan(String value) {
            addCriterion("FCreateTime >", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("FCreateTime >=", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLessThan(String value) {
            addCriterion("FCreateTime <", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLessThanOrEqualTo(String value) {
            addCriterion("FCreateTime <=", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLike(String value) {
            addCriterion("FCreateTime like", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotLike(String value) {
            addCriterion("FCreateTime not like", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIn(List<String> values) {
            addCriterion("FCreateTime in", values, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotIn(List<String> values) {
            addCriterion("FCreateTime not in", values, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeBetween(String value1, String value2) {
            addCriterion("FCreateTime between", value1, value2, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotBetween(String value1, String value2) {
            addCriterion("FCreateTime not between", value1, value2, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIsNull() {
            addCriterion("FCreateUserId is null");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIsNotNull() {
            addCriterion("FCreateUserId is not null");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridEqualTo(Long value) {
            addCriterion("FCreateUserId =", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotEqualTo(Long value) {
            addCriterion("FCreateUserId <>", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridGreaterThan(Long value) {
            addCriterion("FCreateUserId >", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridGreaterThanOrEqualTo(Long value) {
            addCriterion("FCreateUserId >=", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridLessThan(Long value) {
            addCriterion("FCreateUserId <", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridLessThanOrEqualTo(Long value) {
            addCriterion("FCreateUserId <=", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIn(List<Long> values) {
            addCriterion("FCreateUserId in", values, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotIn(List<Long> values) {
            addCriterion("FCreateUserId not in", values, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridBetween(Long value1, Long value2) {
            addCriterion("FCreateUserId between", value1, value2, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotBetween(Long value1, Long value2) {
            addCriterion("FCreateUserId not between", value1, value2, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIsNull() {
            addCriterion("FUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIsNotNull() {
            addCriterion("FUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeEqualTo(String value) {
            addCriterion("FUpdateTime =", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotEqualTo(String value) {
            addCriterion("FUpdateTime <>", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeGreaterThan(String value) {
            addCriterion("FUpdateTime >", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("FUpdateTime >=", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLessThan(String value) {
            addCriterion("FUpdateTime <", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLessThanOrEqualTo(String value) {
            addCriterion("FUpdateTime <=", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLike(String value) {
            addCriterion("FUpdateTime like", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotLike(String value) {
            addCriterion("FUpdateTime not like", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIn(List<String> values) {
            addCriterion("FUpdateTime in", values, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotIn(List<String> values) {
            addCriterion("FUpdateTime not in", values, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeBetween(String value1, String value2) {
            addCriterion("FUpdateTime between", value1, value2, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotBetween(String value1, String value2) {
            addCriterion("FUpdateTime not between", value1, value2, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridIsNull() {
            addCriterion("FUpdateUserId is null");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridIsNotNull() {
            addCriterion("FUpdateUserId is not null");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridEqualTo(Long value) {
            addCriterion("FUpdateUserId =", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridNotEqualTo(Long value) {
            addCriterion("FUpdateUserId <>", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridGreaterThan(Long value) {
            addCriterion("FUpdateUserId >", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridGreaterThanOrEqualTo(Long value) {
            addCriterion("FUpdateUserId >=", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridLessThan(Long value) {
            addCriterion("FUpdateUserId <", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridLessThanOrEqualTo(Long value) {
            addCriterion("FUpdateUserId <=", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridIn(List<Long> values) {
            addCriterion("FUpdateUserId in", values, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridNotIn(List<Long> values) {
            addCriterion("FUpdateUserId not in", values, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridBetween(Long value1, Long value2) {
            addCriterion("FUpdateUserId between", value1, value2, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridNotBetween(Long value1, Long value2) {
            addCriterion("FUpdateUserId not between", value1, value2, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFguidIsNull() {
            addCriterion("FGUID is null");
            return (Criteria) this;
        }

        public Criteria andFguidIsNotNull() {
            addCriterion("FGUID is not null");
            return (Criteria) this;
        }

        public Criteria andFguidEqualTo(String value) {
            addCriterion("FGUID =", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidNotEqualTo(String value) {
            addCriterion("FGUID <>", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidGreaterThan(String value) {
            addCriterion("FGUID >", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidGreaterThanOrEqualTo(String value) {
            addCriterion("FGUID >=", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidLessThan(String value) {
            addCriterion("FGUID <", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidLessThanOrEqualTo(String value) {
            addCriterion("FGUID <=", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidLike(String value) {
            addCriterion("FGUID like", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidNotLike(String value) {
            addCriterion("FGUID not like", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidIn(List<String> values) {
            addCriterion("FGUID in", values, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidNotIn(List<String> values) {
            addCriterion("FGUID not in", values, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidBetween(String value1, String value2) {
            addCriterion("FGUID between", value1, value2, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidNotBetween(String value1, String value2) {
            addCriterion("FGUID not between", value1, value2, "fguid");
            return (Criteria) this;
        }

        public Criteria andFnameIsNull() {
            addCriterion("FName is null");
            return (Criteria) this;
        }

        public Criteria andFnameIsNotNull() {
            addCriterion("FName is not null");
            return (Criteria) this;
        }

        public Criteria andFnameEqualTo(String value) {
            addCriterion("FName =", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotEqualTo(String value) {
            addCriterion("FName <>", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameGreaterThan(String value) {
            addCriterion("FName >", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameGreaterThanOrEqualTo(String value) {
            addCriterion("FName >=", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameLessThan(String value) {
            addCriterion("FName <", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameLessThanOrEqualTo(String value) {
            addCriterion("FName <=", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameLike(String value) {
            addCriterion("FName like", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotLike(String value) {
            addCriterion("FName not like", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameIn(List<String> values) {
            addCriterion("FName in", values, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotIn(List<String> values) {
            addCriterion("FName not in", values, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameBetween(String value1, String value2) {
            addCriterion("FName between", value1, value2, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotBetween(String value1, String value2) {
            addCriterion("FName not between", value1, value2, "fname");
            return (Criteria) this;
        }

        public Criteria andFcodeIsNull() {
            addCriterion("FCode is null");
            return (Criteria) this;
        }

        public Criteria andFcodeIsNotNull() {
            addCriterion("FCode is not null");
            return (Criteria) this;
        }

        public Criteria andFcodeEqualTo(String value) {
            addCriterion("FCode =", value, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeNotEqualTo(String value) {
            addCriterion("FCode <>", value, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeGreaterThan(String value) {
            addCriterion("FCode >", value, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeGreaterThanOrEqualTo(String value) {
            addCriterion("FCode >=", value, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeLessThan(String value) {
            addCriterion("FCode <", value, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeLessThanOrEqualTo(String value) {
            addCriterion("FCode <=", value, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeLike(String value) {
            addCriterion("FCode like", value, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeNotLike(String value) {
            addCriterion("FCode not like", value, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeIn(List<String> values) {
            addCriterion("FCode in", values, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeNotIn(List<String> values) {
            addCriterion("FCode not in", values, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeBetween(String value1, String value2) {
            addCriterion("FCode between", value1, value2, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeNotBetween(String value1, String value2) {
            addCriterion("FCode not between", value1, value2, "fcode");
            return (Criteria) this;
        }

        public Criteria andFaddressIsNull() {
            addCriterion("FAddress is null");
            return (Criteria) this;
        }

        public Criteria andFaddressIsNotNull() {
            addCriterion("FAddress is not null");
            return (Criteria) this;
        }

        public Criteria andFaddressEqualTo(String value) {
            addCriterion("FAddress =", value, "faddress");
            return (Criteria) this;
        }

        public Criteria andFaddressNotEqualTo(String value) {
            addCriterion("FAddress <>", value, "faddress");
            return (Criteria) this;
        }

        public Criteria andFaddressGreaterThan(String value) {
            addCriterion("FAddress >", value, "faddress");
            return (Criteria) this;
        }

        public Criteria andFaddressGreaterThanOrEqualTo(String value) {
            addCriterion("FAddress >=", value, "faddress");
            return (Criteria) this;
        }

        public Criteria andFaddressLessThan(String value) {
            addCriterion("FAddress <", value, "faddress");
            return (Criteria) this;
        }

        public Criteria andFaddressLessThanOrEqualTo(String value) {
            addCriterion("FAddress <=", value, "faddress");
            return (Criteria) this;
        }

        public Criteria andFaddressLike(String value) {
            addCriterion("FAddress like", value, "faddress");
            return (Criteria) this;
        }

        public Criteria andFaddressNotLike(String value) {
            addCriterion("FAddress not like", value, "faddress");
            return (Criteria) this;
        }

        public Criteria andFaddressIn(List<String> values) {
            addCriterion("FAddress in", values, "faddress");
            return (Criteria) this;
        }

        public Criteria andFaddressNotIn(List<String> values) {
            addCriterion("FAddress not in", values, "faddress");
            return (Criteria) this;
        }

        public Criteria andFaddressBetween(String value1, String value2) {
            addCriterion("FAddress between", value1, value2, "faddress");
            return (Criteria) this;
        }

        public Criteria andFaddressNotBetween(String value1, String value2) {
            addCriterion("FAddress not between", value1, value2, "faddress");
            return (Criteria) this;
        }

        public Criteria andFisspecialchannelIsNull() {
            addCriterion("FIsSpecialChannel is null");
            return (Criteria) this;
        }

        public Criteria andFisspecialchannelIsNotNull() {
            addCriterion("FIsSpecialChannel is not null");
            return (Criteria) this;
        }

        public Criteria andFisspecialchannelEqualTo(String value) {
            addCriterion("FIsSpecialChannel =", value, "fisspecialchannel");
            return (Criteria) this;
        }

        public Criteria andFisspecialchannelNotEqualTo(String value) {
            addCriterion("FIsSpecialChannel <>", value, "fisspecialchannel");
            return (Criteria) this;
        }

        public Criteria andFisspecialchannelGreaterThan(String value) {
            addCriterion("FIsSpecialChannel >", value, "fisspecialchannel");
            return (Criteria) this;
        }

        public Criteria andFisspecialchannelGreaterThanOrEqualTo(String value) {
            addCriterion("FIsSpecialChannel >=", value, "fisspecialchannel");
            return (Criteria) this;
        }

        public Criteria andFisspecialchannelLessThan(String value) {
            addCriterion("FIsSpecialChannel <", value, "fisspecialchannel");
            return (Criteria) this;
        }

        public Criteria andFisspecialchannelLessThanOrEqualTo(String value) {
            addCriterion("FIsSpecialChannel <=", value, "fisspecialchannel");
            return (Criteria) this;
        }

        public Criteria andFisspecialchannelLike(String value) {
            addCriterion("FIsSpecialChannel like", value, "fisspecialchannel");
            return (Criteria) this;
        }

        public Criteria andFisspecialchannelNotLike(String value) {
            addCriterion("FIsSpecialChannel not like", value, "fisspecialchannel");
            return (Criteria) this;
        }

        public Criteria andFisspecialchannelIn(List<String> values) {
            addCriterion("FIsSpecialChannel in", values, "fisspecialchannel");
            return (Criteria) this;
        }

        public Criteria andFisspecialchannelNotIn(List<String> values) {
            addCriterion("FIsSpecialChannel not in", values, "fisspecialchannel");
            return (Criteria) this;
        }

        public Criteria andFisspecialchannelBetween(String value1, String value2) {
            addCriterion("FIsSpecialChannel between", value1, value2, "fisspecialchannel");
            return (Criteria) this;
        }

        public Criteria andFisspecialchannelNotBetween(String value1, String value2) {
            addCriterion("FIsSpecialChannel not between", value1, value2, "fisspecialchannel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_branch
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 22 14:34:35 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}