package com.evmtv.epg.entity;

public class TAdvWithBLOBs extends TAdv {
    /**
	 * @field serialVersionUID
	 * @field_type long
	 */
	private static final long serialVersionUID = 8752896896158280362L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.FExpand
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private String fexpand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.FRemark
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private String fremark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.FExpand
     *
     * @return the value of t_adv.FExpand
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public String getFexpand() {
        return fexpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.FExpand
     *
     * @param fexpand the value for t_adv.FExpand
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setFexpand(String fexpand) {
        this.fexpand = fexpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.FRemark
     *
     * @return the value of t_adv.FRemark
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public String getFremark() {
        return fremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.FRemark
     *
     * @param fremark the value for t_adv.FRemark
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setFremark(String fremark) {
        this.fremark = fremark;
    }
}