package com.evmtv.epg.entity;

import com.evmtv.epg.request.BaseRequest;

public class TAdvClass extends BaseRequest{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv_class.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv_class.FPositionId
     *
     * @mbggenerated
     */
    private Integer fpositionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv_class.FType
     *
     * @mbggenerated
     */
    private String ftype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv_class.ID
     *
     * @return the value of t_adv_class.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv_class.ID
     *
     * @param id the value for t_adv_class.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv_class.FPositionId
     *
     * @return the value of t_adv_class.FPositionId
     *
     * @mbggenerated
     */
    public Integer getFpositionid() {
        return fpositionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv_class.FPositionId
     *
     * @param fpositionid the value for t_adv_class.FPositionId
     *
     * @mbggenerated
     */
    public void setFpositionid(Integer fpositionid) {
        this.fpositionid = fpositionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv_class.FType
     *
     * @return the value of t_adv_class.FType
     *
     * @mbggenerated
     */
    public String getFtype() {
        return ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv_class.FType
     *
     * @param ftype the value for t_adv_class.FType
     *
     * @mbggenerated
     */
    public void setFtype(String ftype) {
        this.ftype = ftype == null ? null : ftype.trim();
    }
}