package com.evmtv.epg.entity;

import java.util.List;

import com.evmtv.epg.request.BaseRequest;

public class TBranchSourceRelease extends BaseRequest{
    /**
	 * @field serialVersionUID
	 * @field_type long
	 */
	private static final long serialVersionUID = -4976877247360846788L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_source_release.ID
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_source_release.FBranchId
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    private Long fbranchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_source_release.FSourceId
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    private Long fsourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_source_release.FCreateTime
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    private String fcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_source_release.FCreateUserId
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    private Long fcreateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_source_release.FContractId
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    private Long fcontractid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_source_release.FIsUsing
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    private String fisusing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_source_release.FUpdateTime
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    private String fupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_source_release.FVersion
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    private String fversion;

    /**
     * 广告位索引
     */
	private List<Long> fsourceidList;
	/**
	 * 合同索引
	 */
	private List<Long> fcontractidList;
	/**
	 * 发布广告
	 */
	private List<TSourceWithBLOBs> sources;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_source_release.ID
     *
     * @return the value of t_branch_source_release.ID
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_source_release.ID
     *
     * @param id the value for t_branch_source_release.ID
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_source_release.FBranchId
     *
     * @return the value of t_branch_source_release.FBranchId
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public Long getFbranchid() {
        return fbranchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_source_release.FBranchId
     *
     * @param fbranchid the value for t_branch_source_release.FBranchId
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public void setFbranchid(Long fbranchid) {
        this.fbranchid = fbranchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_source_release.FSourceId
     *
     * @return the value of t_branch_source_release.FSourceId
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public Long getFsourceid() {
        return fsourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_source_release.FSourceId
     *
     * @param fsourceid the value for t_branch_source_release.FSourceId
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public void setFsourceid(Long fsourceid) {
        this.fsourceid = fsourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_source_release.FCreateTime
     *
     * @return the value of t_branch_source_release.FCreateTime
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public String getFcreatetime() {
        return fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_source_release.FCreateTime
     *
     * @param fcreatetime the value for t_branch_source_release.FCreateTime
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public void setFcreatetime(String fcreatetime) {
        this.fcreatetime = fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_source_release.FCreateUserId
     *
     * @return the value of t_branch_source_release.FCreateUserId
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public Long getFcreateuserid() {
        return fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_source_release.FCreateUserId
     *
     * @param fcreateuserid the value for t_branch_source_release.FCreateUserId
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public void setFcreateuserid(Long fcreateuserid) {
        this.fcreateuserid = fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_source_release.FContractId
     *
     * @return the value of t_branch_source_release.FContractId
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public Long getFcontractid() {
        return fcontractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_source_release.FContractId
     *
     * @param fcontractid the value for t_branch_source_release.FContractId
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public void setFcontractid(Long fcontractid) {
        this.fcontractid = fcontractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_source_release.FIsUsing
     *
     * @return the value of t_branch_source_release.FIsUsing
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public String getFisusing() {
        return fisusing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_source_release.FIsUsing
     *
     * @param fisusing the value for t_branch_source_release.FIsUsing
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public void setFisusing(String fisusing) {
        this.fisusing = fisusing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_source_release.FUpdateTime
     *
     * @return the value of t_branch_source_release.FUpdateTime
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public String getFupdatetime() {
        return fupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_source_release.FUpdateTime
     *
     * @param fupdatetime the value for t_branch_source_release.FUpdateTime
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public void setFupdatetime(String fupdatetime) {
        this.fupdatetime = fupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_source_release.FVersion
     *
     * @return the value of t_branch_source_release.FVersion
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public String getFversion() {
        return fversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_source_release.FVersion
     *
     * @param fversion the value for t_branch_source_release.FVersion
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public void setFversion(String fversion) {
        this.fversion = fversion;
    }

	/**
	 * @return the fsourceidList
	 */
	public List<Long> getFsourceidList() {
		return fsourceidList;
	}

	/**
	 * @param fsourceidList the fsourceidList to set
	 */
	public void setFsourceidList(List<Long> fsourceidList) {
		this.fsourceidList = fsourceidList;
	}

	/**
	 * @return the fcontractidList
	 */
	public List<Long> getFcontractidList() {
		return fcontractidList;
	}

	/**
	 * @param fcontractidList the fcontractidList to set
	 */
	public void setFcontractidList(List<Long> fcontractidList) {
		this.fcontractidList = fcontractidList;
	}

	public List<TSourceWithBLOBs> getSources() {
		return sources;
	}

	public void setSources(List<TSourceWithBLOBs> sources) {
		this.sources = sources;
	}
}