package com.evmtv.epg.entity;

public class TContractAdvResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_adv_resource.ID
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_adv_resource.FResourceId
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    private Long fresourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_adv_resource.FContractAdvId
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    private Long fcontractadvid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_adv_resource.FEdited
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    private String fedited;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_adv_resource.FOriginalResourceId
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    private Long foriginalresourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_adv_resource.FIsOriginalResource
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    private String fisoriginalresource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_adv_resource.FSourceId
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    private Long fsourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_adv_resource.FIsUsing
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    private String fisusing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_adv_resource.FUseStartTime
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    private String fusestarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_adv_resource.FUseEndTime
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    private String fuseendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_adv_resource.FNodeId
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    private Long fnodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_adv_resource.FOrder
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    private Integer forder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_adv_resource.ID
     *
     * @return the value of t_contract_adv_resource.ID
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_adv_resource.ID
     *
     * @param id the value for t_contract_adv_resource.ID
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_adv_resource.FResourceId
     *
     * @return the value of t_contract_adv_resource.FResourceId
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public Long getFresourceid() {
        return fresourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_adv_resource.FResourceId
     *
     * @param fresourceid the value for t_contract_adv_resource.FResourceId
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public void setFresourceid(Long fresourceid) {
        this.fresourceid = fresourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_adv_resource.FContractAdvId
     *
     * @return the value of t_contract_adv_resource.FContractAdvId
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public Long getFcontractadvid() {
        return fcontractadvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_adv_resource.FContractAdvId
     *
     * @param fcontractadvid the value for t_contract_adv_resource.FContractAdvId
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public void setFcontractadvid(Long fcontractadvid) {
        this.fcontractadvid = fcontractadvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_adv_resource.FEdited
     *
     * @return the value of t_contract_adv_resource.FEdited
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public String getFedited() {
        return fedited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_adv_resource.FEdited
     *
     * @param fedited the value for t_contract_adv_resource.FEdited
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public void setFedited(String fedited) {
        this.fedited = fedited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_adv_resource.FOriginalResourceId
     *
     * @return the value of t_contract_adv_resource.FOriginalResourceId
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public Long getForiginalresourceid() {
        return foriginalresourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_adv_resource.FOriginalResourceId
     *
     * @param foriginalresourceid the value for t_contract_adv_resource.FOriginalResourceId
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public void setForiginalresourceid(Long foriginalresourceid) {
        this.foriginalresourceid = foriginalresourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_adv_resource.FIsOriginalResource
     *
     * @return the value of t_contract_adv_resource.FIsOriginalResource
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public String getFisoriginalresource() {
        return fisoriginalresource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_adv_resource.FIsOriginalResource
     *
     * @param fisoriginalresource the value for t_contract_adv_resource.FIsOriginalResource
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public void setFisoriginalresource(String fisoriginalresource) {
        this.fisoriginalresource = fisoriginalresource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_adv_resource.FSourceId
     *
     * @return the value of t_contract_adv_resource.FSourceId
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public Long getFsourceid() {
        return fsourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_adv_resource.FSourceId
     *
     * @param fsourceid the value for t_contract_adv_resource.FSourceId
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public void setFsourceid(Long fsourceid) {
        this.fsourceid = fsourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_adv_resource.FIsUsing
     *
     * @return the value of t_contract_adv_resource.FIsUsing
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public String getFisusing() {
        return fisusing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_adv_resource.FIsUsing
     *
     * @param fisusing the value for t_contract_adv_resource.FIsUsing
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public void setFisusing(String fisusing) {
        this.fisusing = fisusing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_adv_resource.FUseStartTime
     *
     * @return the value of t_contract_adv_resource.FUseStartTime
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public String getFusestarttime() {
        return fusestarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_adv_resource.FUseStartTime
     *
     * @param fusestarttime the value for t_contract_adv_resource.FUseStartTime
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public void setFusestarttime(String fusestarttime) {
        this.fusestarttime = fusestarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_adv_resource.FUseEndTime
     *
     * @return the value of t_contract_adv_resource.FUseEndTime
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public String getFuseendtime() {
        return fuseendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_adv_resource.FUseEndTime
     *
     * @param fuseendtime the value for t_contract_adv_resource.FUseEndTime
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public void setFuseendtime(String fuseendtime) {
        this.fuseendtime = fuseendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_adv_resource.FNodeId
     *
     * @return the value of t_contract_adv_resource.FNodeId
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public Long getFnodeid() {
        return fnodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_adv_resource.FNodeId
     *
     * @param fnodeid the value for t_contract_adv_resource.FNodeId
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public void setFnodeid(Long fnodeid) {
        this.fnodeid = fnodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_adv_resource.FOrder
     *
     * @return the value of t_contract_adv_resource.FOrder
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public Integer getForder() {
        return forder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_adv_resource.FOrder
     *
     * @param forder the value for t_contract_adv_resource.FOrder
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    public void setForder(Integer forder) {
        this.forder = forder;
    }
}