package com.evmtv.epg.entity;

import java.util.List;


public class TContractAdv  extends TContractAdvResource{
    /**
	 * @field serialVersionUID
	 * @field_type long
	 */
	private String ftype;//广告位
	
	private int count;//素材总数
	
	private String fpath;//文件路径
	
	private int fpositionid;//广告位
	
	private String fcontractName;//合同名称
	
	private String fname;//素材名称
	
	private int fwidth;//素材高
	
	private int fheight;//素材高
	
	private Long carId;//合同广告位素材素材索引

	private String fstarttime;//合同开始时间
	
	private String fendtime;//合同结束时间
	
	private Long fbranchid;//分公司索引
	
	private String fguid;
	
	private List<Long> advIdList;//广告位索引

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_adv.FContractId
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    private Long fcontractid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_adv.FAdvId
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    private Long fadvid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_adv.FDefinition
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    private String fdefinition;

	/**
	 * @return the fwidth
	 */
	public int getFwidth() {
		return fwidth;
	}

	/**
	 * @param fwidth the fwidth to set
	 */
	public void setFwidth(int fwidth) {
		this.fwidth = fwidth;
	}

	/**
	 * @return the fheight
	 */
	public int getFheight() {
		return fheight;
	}

	/**
	 * @param fheight the fheight to set
	 */
	public void setFheight(int fheight) {
		this.fheight = fheight;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_adv.FContractId
     *
     * @return the value of t_contract_adv.FContractId
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    public Long getFcontractid() {
        return fcontractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_adv.FContractId
     *
     * @param fcontractid the value for t_contract_adv.FContractId
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    public void setFcontractid(Long fcontractid) {
        this.fcontractid = fcontractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_adv.FAdvId
     *
     * @return the value of t_contract_adv.FAdvId
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    public Long getFadvid() {
        return fadvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_adv.FAdvId
     *
     * @param fadvid the value for t_contract_adv.FAdvId
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    public void setFadvid(Long fadvid) {
        this.fadvid = fadvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_adv.FDefinition
     *
     * @return the value of t_contract_adv.FDefinition
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    public String getFdefinition() {
        return fdefinition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_adv.FDefinition
     *
     * @param fdefinition the value for t_contract_adv.FDefinition
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    public void setFdefinition(String fdefinition) {
        this.fdefinition = fdefinition;
    }

	public String getFtype() {
		return ftype;
	}

	public void setFtype(String ftype) {
		this.ftype = ftype;
	}

	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public String getFpath() {
		return fpath;
	}

	public void setFpath(String fpath) {
		this.fpath = fpath;
	}

	public int getFpositionid() {
		return fpositionid;
	}

	public void setFpositionid(int fpositionid) {
		this.fpositionid = fpositionid;
	}

	public String getFcontractName() {
		return fcontractName;
	}

	public void setFcontractName(String fcontractName) {
		this.fcontractName = fcontractName;
	}

	public String getFname() {
		return fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	/**
	 * @return the carId
	 */
	public Long getCarId() {
		return carId;
	}

	/**
	 * @param carId the carId to set
	 */
	public void setCarId(Long carId) {
		this.carId = carId;
	}

	/**
	 * @return the fstarttime
	 */
	public String getFstarttime() {
		return fstarttime;
	}

	/**
	 * @param fstarttime the fstarttime to set
	 */
	public void setFstarttime(String fstarttime) {
		this.fstarttime = fstarttime;
	}

	/**
	 * @return the fendtime
	 */
	public String getFendtime() {
		return fendtime;
	}

	/**
	 * @param fendtime the fendtime to set
	 */
	public void setFendtime(String fendtime) {
		this.fendtime = fendtime;
	}

	/**
	 * @return the fbranchid
	 */
	public Long getFbranchid() {
		return fbranchid;
	}

	/**
	 * @return the advIdList
	 */
	public List<Long> getAdvIdList() {
		return advIdList;
	}

	/**
	 * @param advIdList the advIdList to set
	 */
	public void setAdvIdList(List<Long> advIdList) {
		this.advIdList = advIdList;
	}

	/**
	 * @param fbranchid the fbranchid to set
	 */
	public void setFbranchid(Long fbranchid) {
		this.fbranchid = fbranchid;
	}

	public String getFguid() {
		return fguid;
	}

	public void setFguid(String fguid) {
		this.fguid = fguid;
	}
}