package com.evmtv.epg.entity;

import java.util.ArrayList;
import java.util.List;

public class TContractAdvExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    public TContractAdvExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFcontractidIsNull() {
            addCriterion("FContractId is null");
            return (Criteria) this;
        }

        public Criteria andFcontractidIsNotNull() {
            addCriterion("FContractId is not null");
            return (Criteria) this;
        }

        public Criteria andFcontractidEqualTo(Long value) {
            addCriterion("FContractId =", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidNotEqualTo(Long value) {
            addCriterion("FContractId <>", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidGreaterThan(Long value) {
            addCriterion("FContractId >", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidGreaterThanOrEqualTo(Long value) {
            addCriterion("FContractId >=", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidLessThan(Long value) {
            addCriterion("FContractId <", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidLessThanOrEqualTo(Long value) {
            addCriterion("FContractId <=", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidIn(List<Long> values) {
            addCriterion("FContractId in", values, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidNotIn(List<Long> values) {
            addCriterion("FContractId not in", values, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidBetween(Long value1, Long value2) {
            addCriterion("FContractId between", value1, value2, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidNotBetween(Long value1, Long value2) {
            addCriterion("FContractId not between", value1, value2, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFadvidIsNull() {
            addCriterion("FAdvId is null");
            return (Criteria) this;
        }

        public Criteria andFadvidIsNotNull() {
            addCriterion("FAdvId is not null");
            return (Criteria) this;
        }

        public Criteria andFadvidEqualTo(Long value) {
            addCriterion("FAdvId =", value, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidNotEqualTo(Long value) {
            addCriterion("FAdvId <>", value, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidGreaterThan(Long value) {
            addCriterion("FAdvId >", value, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidGreaterThanOrEqualTo(Long value) {
            addCriterion("FAdvId >=", value, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidLessThan(Long value) {
            addCriterion("FAdvId <", value, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidLessThanOrEqualTo(Long value) {
            addCriterion("FAdvId <=", value, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidIn(List<Long> values) {
            addCriterion("FAdvId in", values, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidNotIn(List<Long> values) {
            addCriterion("FAdvId not in", values, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidBetween(Long value1, Long value2) {
            addCriterion("FAdvId between", value1, value2, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidNotBetween(Long value1, Long value2) {
            addCriterion("FAdvId not between", value1, value2, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFdefinitionIsNull() {
            addCriterion("FDefinition is null");
            return (Criteria) this;
        }

        public Criteria andFdefinitionIsNotNull() {
            addCriterion("FDefinition is not null");
            return (Criteria) this;
        }

        public Criteria andFdefinitionEqualTo(String value) {
            addCriterion("FDefinition =", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionNotEqualTo(String value) {
            addCriterion("FDefinition <>", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionGreaterThan(String value) {
            addCriterion("FDefinition >", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionGreaterThanOrEqualTo(String value) {
            addCriterion("FDefinition >=", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionLessThan(String value) {
            addCriterion("FDefinition <", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionLessThanOrEqualTo(String value) {
            addCriterion("FDefinition <=", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionLike(String value) {
            addCriterion("FDefinition like", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionNotLike(String value) {
            addCriterion("FDefinition not like", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionIn(List<String> values) {
            addCriterion("FDefinition in", values, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionNotIn(List<String> values) {
            addCriterion("FDefinition not in", values, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionBetween(String value1, String value2) {
            addCriterion("FDefinition between", value1, value2, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionNotBetween(String value1, String value2) {
            addCriterion("FDefinition not between", value1, value2, "fdefinition");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_contract_adv
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 08 11:51:54 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}