package com.evmtv.epg.entity;

import java.util.List;

import com.evmtv.epg.request.BaseRequest;
/**
 * <p>Title: 发布版本</p> 
 * <p>Description: </p> 
 * <p>Date: 2013年11月28日下午1:50:04</p> 
 * <p>Copyright: Copyright (c) 2013</p> 
 * <p>Company: www.evmtv.com</p> 
 * @author fangzhu@evmtv.com
 * @version 1.0
 */
public class TReleaseVersion extends BaseRequest{
    /**
	 * @field serialVersionUID
	 * @field_type long
	 */
	private static final long serialVersionUID = -6961800446249378500L;


	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_release_version.ID
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    private Long id;


    private String userName;
    
    private String branch;
    
    private List<Long> ids;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_release_version.FVersion
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    private String fversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_release_version.FCreateTime
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    private String fcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_release_version.FBranchId
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    private Long fbranchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_release_version.FCreateUserId
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    private Long fcreateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_release_version.FDesc
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    private String fdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_release_version.FDayVersion
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    private Integer fdayversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_release_version.FUpdateTime
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    private String fupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_release_version.FDefinition
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    private String fdefinition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_release_version.FProvReleaseVersionId
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    private Long fprovreleaseversionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_release_version.FStatus
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    private Integer fstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_release_version.FIsValid
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    private String fisvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_release_version.FIsHandle
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    private String fishandle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_release_version.FOrder
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    private Integer forder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_release_version.FNodeId
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    private Long fnodeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_release_version.ID
     *
     * @return the value of t_release_version.ID
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_release_version.ID
     *
     * @param id the value for t_release_version.ID
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_release_version.FVersion
     *
     * @return the value of t_release_version.FVersion
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public String getFversion() {
        return fversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_release_version.FVersion
     *
     * @param fversion the value for t_release_version.FVersion
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public void setFversion(String fversion) {
        this.fversion = fversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_release_version.FCreateTime
     *
     * @return the value of t_release_version.FCreateTime
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public String getFcreatetime() {
        return fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_release_version.FCreateTime
     *
     * @param fcreatetime the value for t_release_version.FCreateTime
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public void setFcreatetime(String fcreatetime) {
        this.fcreatetime = fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_release_version.FBranchId
     *
     * @return the value of t_release_version.FBranchId
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public Long getFbranchid() {
        return fbranchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_release_version.FBranchId
     *
     * @param fbranchid the value for t_release_version.FBranchId
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public void setFbranchid(Long fbranchid) {
        this.fbranchid = fbranchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_release_version.FCreateUserId
     *
     * @return the value of t_release_version.FCreateUserId
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public Long getFcreateuserid() {
        return fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_release_version.FCreateUserId
     *
     * @param fcreateuserid the value for t_release_version.FCreateUserId
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public void setFcreateuserid(Long fcreateuserid) {
        this.fcreateuserid = fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_release_version.FDesc
     *
     * @return the value of t_release_version.FDesc
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public String getFdesc() {
        return fdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_release_version.FDesc
     *
     * @param fdesc the value for t_release_version.FDesc
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public void setFdesc(String fdesc) {
        this.fdesc = fdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_release_version.FDayVersion
     *
     * @return the value of t_release_version.FDayVersion
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public Integer getFdayversion() {
        return fdayversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_release_version.FDayVersion
     *
     * @param fdayversion the value for t_release_version.FDayVersion
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public void setFdayversion(Integer fdayversion) {
        this.fdayversion = fdayversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_release_version.FUpdateTime
     *
     * @return the value of t_release_version.FUpdateTime
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public String getFupdatetime() {
        return fupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_release_version.FUpdateTime
     *
     * @param fupdatetime the value for t_release_version.FUpdateTime
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public void setFupdatetime(String fupdatetime) {
        this.fupdatetime = fupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_release_version.FDefinition
     *
     * @return the value of t_release_version.FDefinition
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public String getFdefinition() {
        return fdefinition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_release_version.FDefinition
     *
     * @param fdefinition the value for t_release_version.FDefinition
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public void setFdefinition(String fdefinition) {
        this.fdefinition = fdefinition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_release_version.FProvReleaseVersionId
     *
     * @return the value of t_release_version.FProvReleaseVersionId
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public Long getFprovreleaseversionid() {
        return fprovreleaseversionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_release_version.FProvReleaseVersionId
     *
     * @param fprovreleaseversionid the value for t_release_version.FProvReleaseVersionId
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public void setFprovreleaseversionid(Long fprovreleaseversionid) {
        this.fprovreleaseversionid = fprovreleaseversionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_release_version.FStatus
     *
     * @return the value of t_release_version.FStatus
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public Integer getFstatus() {
        return fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_release_version.FStatus
     *
     * @param fstatus the value for t_release_version.FStatus
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public void setFstatus(Integer fstatus) {
        this.fstatus = fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_release_version.FIsValid
     *
     * @return the value of t_release_version.FIsValid
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public String getFisvalid() {
        return fisvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_release_version.FIsValid
     *
     * @param fisvalid the value for t_release_version.FIsValid
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public void setFisvalid(String fisvalid) {
        this.fisvalid = fisvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_release_version.FIsHandle
     *
     * @return the value of t_release_version.FIsHandle
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public String getFishandle() {
        return fishandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_release_version.FIsHandle
     *
     * @param fishandle the value for t_release_version.FIsHandle
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public void setFishandle(String fishandle) {
        this.fishandle = fishandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_release_version.FOrder
     *
     * @return the value of t_release_version.FOrder
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public Integer getForder() {
        return forder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_release_version.FOrder
     *
     * @param forder the value for t_release_version.FOrder
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public void setForder(Integer forder) {
        this.forder = forder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_release_version.FNodeId
     *
     * @return the value of t_release_version.FNodeId
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public Long getFnodeid() {
        return fnodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_release_version.FNodeId
     *
     * @param fnodeid the value for t_release_version.FNodeId
     *
     * @mbggenerated Thu Nov 28 13:38:08 CST 2013
     */
    public void setFnodeid(Long fnodeid) {
        this.fnodeid = fnodeid;
    }

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getBranch() {
		return branch;
	}

	public void setBranch(String branch) {
		this.branch = branch;
	}

	public List<Long> getIds() {
		return ids;
	}

	public void setIds(List<Long> ids) {
		this.ids = ids;
	}
}