package com.evmtv.epg.entity;

public class TResourceWithBLOBs extends TResource {
    /**
	 * @field serialVersionUID
	 * @field_type long
	 */
	private static final long serialVersionUID = 7739412915609180354L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.FRemark
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    private String fremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.FExpand
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    private String fexpand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.FRawData
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    private byte[] frawdata;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.FRemark
     *
     * @return the value of t_resource.FRemark
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    public String getFremark() {
        return fremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.FRemark
     *
     * @param fremark the value for t_resource.FRemark
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    public void setFremark(String fremark) {
        this.fremark = fremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.FExpand
     *
     * @return the value of t_resource.FExpand
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    public String getFexpand() {
        return fexpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.FExpand
     *
     * @param fexpand the value for t_resource.FExpand
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    public void setFexpand(String fexpand) {
        this.fexpand = fexpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.FRawData
     *
     * @return the value of t_resource.FRawData
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    public byte[] getFrawdata() {
        return frawdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.FRawData
     *
     * @param frawdata the value for t_resource.FRawData
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    public void setFrawdata(byte[] frawdata) {
        this.frawdata = frawdata;
    }
}