package com.evmtv.epg.entity;

import java.util.ArrayList;
import java.util.List;

import com.evmtv.epg.request.BaseRequest;

public class TResourceExample extends BaseRequest{
    /**
	 * @field serialVersionUID
	 * @field_type long
	 */
	private static final long serialVersionUID = -2597249063440128608L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    public TResourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIsNull() {
            addCriterion("FCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIsNotNull() {
            addCriterion("FCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeEqualTo(String value) {
            addCriterion("FCreateTime =", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotEqualTo(String value) {
            addCriterion("FCreateTime <>", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeGreaterThan(String value) {
            addCriterion("FCreateTime >", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("FCreateTime >=", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLessThan(String value) {
            addCriterion("FCreateTime <", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLessThanOrEqualTo(String value) {
            addCriterion("FCreateTime <=", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLike(String value) {
            addCriterion("FCreateTime like", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotLike(String value) {
            addCriterion("FCreateTime not like", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIn(List<String> values) {
            addCriterion("FCreateTime in", values, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotIn(List<String> values) {
            addCriterion("FCreateTime not in", values, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeBetween(String value1, String value2) {
            addCriterion("FCreateTime between", value1, value2, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotBetween(String value1, String value2) {
            addCriterion("FCreateTime not between", value1, value2, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIsNull() {
            addCriterion("FCreateUserId is null");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIsNotNull() {
            addCriterion("FCreateUserId is not null");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridEqualTo(Long value) {
            addCriterion("FCreateUserId =", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotEqualTo(Long value) {
            addCriterion("FCreateUserId <>", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridGreaterThan(Long value) {
            addCriterion("FCreateUserId >", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridGreaterThanOrEqualTo(Long value) {
            addCriterion("FCreateUserId >=", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridLessThan(Long value) {
            addCriterion("FCreateUserId <", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridLessThanOrEqualTo(Long value) {
            addCriterion("FCreateUserId <=", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIn(List<Long> values) {
            addCriterion("FCreateUserId in", values, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotIn(List<Long> values) {
            addCriterion("FCreateUserId not in", values, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridBetween(Long value1, Long value2) {
            addCriterion("FCreateUserId between", value1, value2, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotBetween(Long value1, Long value2) {
            addCriterion("FCreateUserId not between", value1, value2, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIsNull() {
            addCriterion("FUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIsNotNull() {
            addCriterion("FUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeEqualTo(String value) {
            addCriterion("FUpdateTime =", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotEqualTo(String value) {
            addCriterion("FUpdateTime <>", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeGreaterThan(String value) {
            addCriterion("FUpdateTime >", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("FUpdateTime >=", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLessThan(String value) {
            addCriterion("FUpdateTime <", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLessThanOrEqualTo(String value) {
            addCriterion("FUpdateTime <=", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLike(String value) {
            addCriterion("FUpdateTime like", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotLike(String value) {
            addCriterion("FUpdateTime not like", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIn(List<String> values) {
            addCriterion("FUpdateTime in", values, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotIn(List<String> values) {
            addCriterion("FUpdateTime not in", values, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeBetween(String value1, String value2) {
            addCriterion("FUpdateTime between", value1, value2, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotBetween(String value1, String value2) {
            addCriterion("FUpdateTime not between", value1, value2, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridIsNull() {
            addCriterion("FUpdateUserId is null");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridIsNotNull() {
            addCriterion("FUpdateUserId is not null");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridEqualTo(Long value) {
            addCriterion("FUpdateUserId =", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridNotEqualTo(Long value) {
            addCriterion("FUpdateUserId <>", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridGreaterThan(Long value) {
            addCriterion("FUpdateUserId >", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridGreaterThanOrEqualTo(Long value) {
            addCriterion("FUpdateUserId >=", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridLessThan(Long value) {
            addCriterion("FUpdateUserId <", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridLessThanOrEqualTo(Long value) {
            addCriterion("FUpdateUserId <=", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridIn(List<Long> values) {
            addCriterion("FUpdateUserId in", values, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridNotIn(List<Long> values) {
            addCriterion("FUpdateUserId not in", values, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridBetween(Long value1, Long value2) {
            addCriterion("FUpdateUserId between", value1, value2, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridNotBetween(Long value1, Long value2) {
            addCriterion("FUpdateUserId not between", value1, value2, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFfreezedIsNull() {
            addCriterion("FFreezed is null");
            return (Criteria) this;
        }

        public Criteria andFfreezedIsNotNull() {
            addCriterion("FFreezed is not null");
            return (Criteria) this;
        }

        public Criteria andFfreezedEqualTo(String value) {
            addCriterion("FFreezed =", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedNotEqualTo(String value) {
            addCriterion("FFreezed <>", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedGreaterThan(String value) {
            addCriterion("FFreezed >", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedGreaterThanOrEqualTo(String value) {
            addCriterion("FFreezed >=", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedLessThan(String value) {
            addCriterion("FFreezed <", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedLessThanOrEqualTo(String value) {
            addCriterion("FFreezed <=", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedLike(String value) {
            addCriterion("FFreezed like", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedNotLike(String value) {
            addCriterion("FFreezed not like", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedIn(List<String> values) {
            addCriterion("FFreezed in", values, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedNotIn(List<String> values) {
            addCriterion("FFreezed not in", values, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedBetween(String value1, String value2) {
            addCriterion("FFreezed between", value1, value2, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedNotBetween(String value1, String value2) {
            addCriterion("FFreezed not between", value1, value2, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFdeletedIsNull() {
            addCriterion("FDeleted is null");
            return (Criteria) this;
        }

        public Criteria andFdeletedIsNotNull() {
            addCriterion("FDeleted is not null");
            return (Criteria) this;
        }

        public Criteria andFdeletedEqualTo(String value) {
            addCriterion("FDeleted =", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedNotEqualTo(String value) {
            addCriterion("FDeleted <>", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedGreaterThan(String value) {
            addCriterion("FDeleted >", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedGreaterThanOrEqualTo(String value) {
            addCriterion("FDeleted >=", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedLessThan(String value) {
            addCriterion("FDeleted <", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedLessThanOrEqualTo(String value) {
            addCriterion("FDeleted <=", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedLike(String value) {
            addCriterion("FDeleted like", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedNotLike(String value) {
            addCriterion("FDeleted not like", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedIn(List<String> values) {
            addCriterion("FDeleted in", values, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedNotIn(List<String> values) {
            addCriterion("FDeleted not in", values, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedBetween(String value1, String value2) {
            addCriterion("FDeleted between", value1, value2, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedNotBetween(String value1, String value2) {
            addCriterion("FDeleted not between", value1, value2, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFcheckedIsNull() {
            addCriterion("FChecked is null");
            return (Criteria) this;
        }

        public Criteria andFcheckedIsNotNull() {
            addCriterion("FChecked is not null");
            return (Criteria) this;
        }

        public Criteria andFcheckedEqualTo(String value) {
            addCriterion("FChecked =", value, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedNotEqualTo(String value) {
            addCriterion("FChecked <>", value, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedGreaterThan(String value) {
            addCriterion("FChecked >", value, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedGreaterThanOrEqualTo(String value) {
            addCriterion("FChecked >=", value, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedLessThan(String value) {
            addCriterion("FChecked <", value, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedLessThanOrEqualTo(String value) {
            addCriterion("FChecked <=", value, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedLike(String value) {
            addCriterion("FChecked like", value, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedNotLike(String value) {
            addCriterion("FChecked not like", value, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedIn(List<String> values) {
            addCriterion("FChecked in", values, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedNotIn(List<String> values) {
            addCriterion("FChecked not in", values, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedBetween(String value1, String value2) {
            addCriterion("FChecked between", value1, value2, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedNotBetween(String value1, String value2) {
            addCriterion("FChecked not between", value1, value2, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFguidIsNull() {
            addCriterion("FGUID is null");
            return (Criteria) this;
        }

        public Criteria andFguidIsNotNull() {
            addCriterion("FGUID is not null");
            return (Criteria) this;
        }

        public Criteria andFguidEqualTo(String value) {
            addCriterion("FGUID =", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidNotEqualTo(String value) {
            addCriterion("FGUID <>", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidGreaterThan(String value) {
            addCriterion("FGUID >", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidGreaterThanOrEqualTo(String value) {
            addCriterion("FGUID >=", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidLessThan(String value) {
            addCriterion("FGUID <", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidLessThanOrEqualTo(String value) {
            addCriterion("FGUID <=", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidLike(String value) {
            addCriterion("FGUID like", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidNotLike(String value) {
            addCriterion("FGUID not like", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidIn(List<String> values) {
            addCriterion("FGUID in", values, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidNotIn(List<String> values) {
            addCriterion("FGUID not in", values, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidBetween(String value1, String value2) {
            addCriterion("FGUID between", value1, value2, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidNotBetween(String value1, String value2) {
            addCriterion("FGUID not between", value1, value2, "fguid");
            return (Criteria) this;
        }

        public Criteria andFtypeIsNull() {
            addCriterion("FType is null");
            return (Criteria) this;
        }

        public Criteria andFtypeIsNotNull() {
            addCriterion("FType is not null");
            return (Criteria) this;
        }

        public Criteria andFtypeEqualTo(String value) {
            addCriterion("FType =", value, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeNotEqualTo(String value) {
            addCriterion("FType <>", value, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeGreaterThan(String value) {
            addCriterion("FType >", value, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeGreaterThanOrEqualTo(String value) {
            addCriterion("FType >=", value, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeLessThan(String value) {
            addCriterion("FType <", value, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeLessThanOrEqualTo(String value) {
            addCriterion("FType <=", value, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeLike(String value) {
            addCriterion("FType like", value, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeNotLike(String value) {
            addCriterion("FType not like", value, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeIn(List<String> values) {
            addCriterion("FType in", values, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeNotIn(List<String> values) {
            addCriterion("FType not in", values, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeBetween(String value1, String value2) {
            addCriterion("FType between", value1, value2, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeNotBetween(String value1, String value2) {
            addCriterion("FType not between", value1, value2, "ftype");
            return (Criteria) this;
        }

        public Criteria andFwidthIsNull() {
            addCriterion("FWidth is null");
            return (Criteria) this;
        }

        public Criteria andFwidthIsNotNull() {
            addCriterion("FWidth is not null");
            return (Criteria) this;
        }

        public Criteria andFwidthEqualTo(String value) {
            addCriterion("FWidth =", value, "fwidth");
            return (Criteria) this;
        }

        public Criteria andFwidthNotEqualTo(String value) {
            addCriterion("FWidth <>", value, "fwidth");
            return (Criteria) this;
        }

        public Criteria andFwidthGreaterThan(String value) {
            addCriterion("FWidth >", value, "fwidth");
            return (Criteria) this;
        }

        public Criteria andFwidthGreaterThanOrEqualTo(String value) {
            addCriterion("FWidth >=", value, "fwidth");
            return (Criteria) this;
        }

        public Criteria andFwidthLessThan(String value) {
            addCriterion("FWidth <", value, "fwidth");
            return (Criteria) this;
        }

        public Criteria andFwidthLessThanOrEqualTo(String value) {
            addCriterion("FWidth <=", value, "fwidth");
            return (Criteria) this;
        }

        public Criteria andFwidthLike(String value) {
            addCriterion("FWidth like", value, "fwidth");
            return (Criteria) this;
        }

        public Criteria andFwidthNotLike(String value) {
            addCriterion("FWidth not like", value, "fwidth");
            return (Criteria) this;
        }

        public Criteria andFwidthIn(List<String> values) {
            addCriterion("FWidth in", values, "fwidth");
            return (Criteria) this;
        }

        public Criteria andFwidthNotIn(List<String> values) {
            addCriterion("FWidth not in", values, "fwidth");
            return (Criteria) this;
        }

        public Criteria andFwidthBetween(String value1, String value2) {
            addCriterion("FWidth between", value1, value2, "fwidth");
            return (Criteria) this;
        }

        public Criteria andFwidthNotBetween(String value1, String value2) {
            addCriterion("FWidth not between", value1, value2, "fwidth");
            return (Criteria) this;
        }

        public Criteria andFheightIsNull() {
            addCriterion("FHeight is null");
            return (Criteria) this;
        }

        public Criteria andFheightIsNotNull() {
            addCriterion("FHeight is not null");
            return (Criteria) this;
        }

        public Criteria andFheightEqualTo(String value) {
            addCriterion("FHeight =", value, "fheight");
            return (Criteria) this;
        }

        public Criteria andFheightNotEqualTo(String value) {
            addCriterion("FHeight <>", value, "fheight");
            return (Criteria) this;
        }

        public Criteria andFheightGreaterThan(String value) {
            addCriterion("FHeight >", value, "fheight");
            return (Criteria) this;
        }

        public Criteria andFheightGreaterThanOrEqualTo(String value) {
            addCriterion("FHeight >=", value, "fheight");
            return (Criteria) this;
        }

        public Criteria andFheightLessThan(String value) {
            addCriterion("FHeight <", value, "fheight");
            return (Criteria) this;
        }

        public Criteria andFheightLessThanOrEqualTo(String value) {
            addCriterion("FHeight <=", value, "fheight");
            return (Criteria) this;
        }

        public Criteria andFheightLike(String value) {
            addCriterion("FHeight like", value, "fheight");
            return (Criteria) this;
        }

        public Criteria andFheightNotLike(String value) {
            addCriterion("FHeight not like", value, "fheight");
            return (Criteria) this;
        }

        public Criteria andFheightIn(List<String> values) {
            addCriterion("FHeight in", values, "fheight");
            return (Criteria) this;
        }

        public Criteria andFheightNotIn(List<String> values) {
            addCriterion("FHeight not in", values, "fheight");
            return (Criteria) this;
        }

        public Criteria andFheightBetween(String value1, String value2) {
            addCriterion("FHeight between", value1, value2, "fheight");
            return (Criteria) this;
        }

        public Criteria andFheightNotBetween(String value1, String value2) {
            addCriterion("FHeight not between", value1, value2, "fheight");
            return (Criteria) this;
        }

        public Criteria andFpathIsNull() {
            addCriterion("FPath is null");
            return (Criteria) this;
        }

        public Criteria andFpathIsNotNull() {
            addCriterion("FPath is not null");
            return (Criteria) this;
        }

        public Criteria andFpathEqualTo(String value) {
            addCriterion("FPath =", value, "fpath");
            return (Criteria) this;
        }

        public Criteria andFpathNotEqualTo(String value) {
            addCriterion("FPath <>", value, "fpath");
            return (Criteria) this;
        }

        public Criteria andFpathGreaterThan(String value) {
            addCriterion("FPath >", value, "fpath");
            return (Criteria) this;
        }

        public Criteria andFpathGreaterThanOrEqualTo(String value) {
            addCriterion("FPath >=", value, "fpath");
            return (Criteria) this;
        }

        public Criteria andFpathLessThan(String value) {
            addCriterion("FPath <", value, "fpath");
            return (Criteria) this;
        }

        public Criteria andFpathLessThanOrEqualTo(String value) {
            addCriterion("FPath <=", value, "fpath");
            return (Criteria) this;
        }

        public Criteria andFpathLike(String value) {
            addCriterion("FPath like", value, "fpath");
            return (Criteria) this;
        }

        public Criteria andFpathNotLike(String value) {
            addCriterion("FPath not like", value, "fpath");
            return (Criteria) this;
        }

        public Criteria andFpathIn(List<String> values) {
            addCriterion("FPath in", values, "fpath");
            return (Criteria) this;
        }

        public Criteria andFpathNotIn(List<String> values) {
            addCriterion("FPath not in", values, "fpath");
            return (Criteria) this;
        }

        public Criteria andFpathBetween(String value1, String value2) {
            addCriterion("FPath between", value1, value2, "fpath");
            return (Criteria) this;
        }

        public Criteria andFpathNotBetween(String value1, String value2) {
            addCriterion("FPath not between", value1, value2, "fpath");
            return (Criteria) this;
        }

        public Criteria andFnameIsNull() {
            addCriterion("FName is null");
            return (Criteria) this;
        }

        public Criteria andFnameIsNotNull() {
            addCriterion("FName is not null");
            return (Criteria) this;
        }

        public Criteria andFnameEqualTo(String value) {
            addCriterion("FName =", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotEqualTo(String value) {
            addCriterion("FName <>", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameGreaterThan(String value) {
            addCriterion("FName >", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameGreaterThanOrEqualTo(String value) {
            addCriterion("FName >=", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameLessThan(String value) {
            addCriterion("FName <", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameLessThanOrEqualTo(String value) {
            addCriterion("FName <=", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameLike(String value) {
            addCriterion("FName like", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotLike(String value) {
            addCriterion("FName not like", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameIn(List<String> values) {
            addCriterion("FName in", values, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotIn(List<String> values) {
            addCriterion("FName not in", values, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameBetween(String value1, String value2) {
            addCriterion("FName between", value1, value2, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotBetween(String value1, String value2) {
            addCriterion("FName not between", value1, value2, "fname");
            return (Criteria) this;
        }

        public Criteria andFfileformatIsNull() {
            addCriterion("FFileFormat is null");
            return (Criteria) this;
        }

        public Criteria andFfileformatIsNotNull() {
            addCriterion("FFileFormat is not null");
            return (Criteria) this;
        }

        public Criteria andFfileformatEqualTo(Integer value) {
            addCriterion("FFileFormat =", value, "ffileformat");
            return (Criteria) this;
        }

        public Criteria andFfileformatNotEqualTo(Integer value) {
            addCriterion("FFileFormat <>", value, "ffileformat");
            return (Criteria) this;
        }

        public Criteria andFfileformatGreaterThan(Integer value) {
            addCriterion("FFileFormat >", value, "ffileformat");
            return (Criteria) this;
        }

        public Criteria andFfileformatGreaterThanOrEqualTo(Integer value) {
            addCriterion("FFileFormat >=", value, "ffileformat");
            return (Criteria) this;
        }

        public Criteria andFfileformatLessThan(Integer value) {
            addCriterion("FFileFormat <", value, "ffileformat");
            return (Criteria) this;
        }

        public Criteria andFfileformatLessThanOrEqualTo(Integer value) {
            addCriterion("FFileFormat <=", value, "ffileformat");
            return (Criteria) this;
        }

        public Criteria andFfileformatIn(List<Integer> values) {
            addCriterion("FFileFormat in", values, "ffileformat");
            return (Criteria) this;
        }

        public Criteria andFfileformatNotIn(List<Integer> values) {
            addCriterion("FFileFormat not in", values, "ffileformat");
            return (Criteria) this;
        }

        public Criteria andFfileformatBetween(Integer value1, Integer value2) {
            addCriterion("FFileFormat between", value1, value2, "ffileformat");
            return (Criteria) this;
        }

        public Criteria andFfileformatNotBetween(Integer value1, Integer value2) {
            addCriterion("FFileFormat not between", value1, value2, "ffileformat");
            return (Criteria) this;
        }

        public Criteria andFscrolltypeIsNull() {
            addCriterion("FScrollType is null");
            return (Criteria) this;
        }

        public Criteria andFscrolltypeIsNotNull() {
            addCriterion("FScrollType is not null");
            return (Criteria) this;
        }

        public Criteria andFscrolltypeEqualTo(Integer value) {
            addCriterion("FScrollType =", value, "fscrolltype");
            return (Criteria) this;
        }

        public Criteria andFscrolltypeNotEqualTo(Integer value) {
            addCriterion("FScrollType <>", value, "fscrolltype");
            return (Criteria) this;
        }

        public Criteria andFscrolltypeGreaterThan(Integer value) {
            addCriterion("FScrollType >", value, "fscrolltype");
            return (Criteria) this;
        }

        public Criteria andFscrolltypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("FScrollType >=", value, "fscrolltype");
            return (Criteria) this;
        }

        public Criteria andFscrolltypeLessThan(Integer value) {
            addCriterion("FScrollType <", value, "fscrolltype");
            return (Criteria) this;
        }

        public Criteria andFscrolltypeLessThanOrEqualTo(Integer value) {
            addCriterion("FScrollType <=", value, "fscrolltype");
            return (Criteria) this;
        }

        public Criteria andFscrolltypeIn(List<Integer> values) {
            addCriterion("FScrollType in", values, "fscrolltype");
            return (Criteria) this;
        }

        public Criteria andFscrolltypeNotIn(List<Integer> values) {
            addCriterion("FScrollType not in", values, "fscrolltype");
            return (Criteria) this;
        }

        public Criteria andFscrolltypeBetween(Integer value1, Integer value2) {
            addCriterion("FScrollType between", value1, value2, "fscrolltype");
            return (Criteria) this;
        }

        public Criteria andFscrolltypeNotBetween(Integer value1, Integer value2) {
            addCriterion("FScrollType not between", value1, value2, "fscrolltype");
            return (Criteria) this;
        }

        public Criteria andFspeedIsNull() {
            addCriterion("FSpeed is null");
            return (Criteria) this;
        }

        public Criteria andFspeedIsNotNull() {
            addCriterion("FSpeed is not null");
            return (Criteria) this;
        }

        public Criteria andFspeedEqualTo(String value) {
            addCriterion("FSpeed =", value, "fspeed");
            return (Criteria) this;
        }

        public Criteria andFspeedNotEqualTo(String value) {
            addCriterion("FSpeed <>", value, "fspeed");
            return (Criteria) this;
        }

        public Criteria andFspeedGreaterThan(String value) {
            addCriterion("FSpeed >", value, "fspeed");
            return (Criteria) this;
        }

        public Criteria andFspeedGreaterThanOrEqualTo(String value) {
            addCriterion("FSpeed >=", value, "fspeed");
            return (Criteria) this;
        }

        public Criteria andFspeedLessThan(String value) {
            addCriterion("FSpeed <", value, "fspeed");
            return (Criteria) this;
        }

        public Criteria andFspeedLessThanOrEqualTo(String value) {
            addCriterion("FSpeed <=", value, "fspeed");
            return (Criteria) this;
        }

        public Criteria andFspeedLike(String value) {
            addCriterion("FSpeed like", value, "fspeed");
            return (Criteria) this;
        }

        public Criteria andFspeedNotLike(String value) {
            addCriterion("FSpeed not like", value, "fspeed");
            return (Criteria) this;
        }

        public Criteria andFspeedIn(List<String> values) {
            addCriterion("FSpeed in", values, "fspeed");
            return (Criteria) this;
        }

        public Criteria andFspeedNotIn(List<String> values) {
            addCriterion("FSpeed not in", values, "fspeed");
            return (Criteria) this;
        }

        public Criteria andFspeedBetween(String value1, String value2) {
            addCriterion("FSpeed between", value1, value2, "fspeed");
            return (Criteria) this;
        }

        public Criteria andFspeedNotBetween(String value1, String value2) {
            addCriterion("FSpeed not between", value1, value2, "fspeed");
            return (Criteria) this;
        }

        public Criteria andFbackcolorIsNull() {
            addCriterion("FBackColor is null");
            return (Criteria) this;
        }

        public Criteria andFbackcolorIsNotNull() {
            addCriterion("FBackColor is not null");
            return (Criteria) this;
        }

        public Criteria andFbackcolorEqualTo(String value) {
            addCriterion("FBackColor =", value, "fbackcolor");
            return (Criteria) this;
        }

        public Criteria andFbackcolorNotEqualTo(String value) {
            addCriterion("FBackColor <>", value, "fbackcolor");
            return (Criteria) this;
        }

        public Criteria andFbackcolorGreaterThan(String value) {
            addCriterion("FBackColor >", value, "fbackcolor");
            return (Criteria) this;
        }

        public Criteria andFbackcolorGreaterThanOrEqualTo(String value) {
            addCriterion("FBackColor >=", value, "fbackcolor");
            return (Criteria) this;
        }

        public Criteria andFbackcolorLessThan(String value) {
            addCriterion("FBackColor <", value, "fbackcolor");
            return (Criteria) this;
        }

        public Criteria andFbackcolorLessThanOrEqualTo(String value) {
            addCriterion("FBackColor <=", value, "fbackcolor");
            return (Criteria) this;
        }

        public Criteria andFbackcolorLike(String value) {
            addCriterion("FBackColor like", value, "fbackcolor");
            return (Criteria) this;
        }

        public Criteria andFbackcolorNotLike(String value) {
            addCriterion("FBackColor not like", value, "fbackcolor");
            return (Criteria) this;
        }

        public Criteria andFbackcolorIn(List<String> values) {
            addCriterion("FBackColor in", values, "fbackcolor");
            return (Criteria) this;
        }

        public Criteria andFbackcolorNotIn(List<String> values) {
            addCriterion("FBackColor not in", values, "fbackcolor");
            return (Criteria) this;
        }

        public Criteria andFbackcolorBetween(String value1, String value2) {
            addCriterion("FBackColor between", value1, value2, "fbackcolor");
            return (Criteria) this;
        }

        public Criteria andFbackcolorNotBetween(String value1, String value2) {
            addCriterion("FBackColor not between", value1, value2, "fbackcolor");
            return (Criteria) this;
        }

        public Criteria andFfontcolorIsNull() {
            addCriterion("FFontColor is null");
            return (Criteria) this;
        }

        public Criteria andFfontcolorIsNotNull() {
            addCriterion("FFontColor is not null");
            return (Criteria) this;
        }

        public Criteria andFfontcolorEqualTo(String value) {
            addCriterion("FFontColor =", value, "ffontcolor");
            return (Criteria) this;
        }

        public Criteria andFfontcolorNotEqualTo(String value) {
            addCriterion("FFontColor <>", value, "ffontcolor");
            return (Criteria) this;
        }

        public Criteria andFfontcolorGreaterThan(String value) {
            addCriterion("FFontColor >", value, "ffontcolor");
            return (Criteria) this;
        }

        public Criteria andFfontcolorGreaterThanOrEqualTo(String value) {
            addCriterion("FFontColor >=", value, "ffontcolor");
            return (Criteria) this;
        }

        public Criteria andFfontcolorLessThan(String value) {
            addCriterion("FFontColor <", value, "ffontcolor");
            return (Criteria) this;
        }

        public Criteria andFfontcolorLessThanOrEqualTo(String value) {
            addCriterion("FFontColor <=", value, "ffontcolor");
            return (Criteria) this;
        }

        public Criteria andFfontcolorLike(String value) {
            addCriterion("FFontColor like", value, "ffontcolor");
            return (Criteria) this;
        }

        public Criteria andFfontcolorNotLike(String value) {
            addCriterion("FFontColor not like", value, "ffontcolor");
            return (Criteria) this;
        }

        public Criteria andFfontcolorIn(List<String> values) {
            addCriterion("FFontColor in", values, "ffontcolor");
            return (Criteria) this;
        }

        public Criteria andFfontcolorNotIn(List<String> values) {
            addCriterion("FFontColor not in", values, "ffontcolor");
            return (Criteria) this;
        }

        public Criteria andFfontcolorBetween(String value1, String value2) {
            addCriterion("FFontColor between", value1, value2, "ffontcolor");
            return (Criteria) this;
        }

        public Criteria andFfontcolorNotBetween(String value1, String value2) {
            addCriterion("FFontColor not between", value1, value2, "ffontcolor");
            return (Criteria) this;
        }

        public Criteria andFadvclassidIsNull() {
            addCriterion("FAdvClassId is null");
            return (Criteria) this;
        }

        public Criteria andFadvclassidIsNotNull() {
            addCriterion("FAdvClassId is not null");
            return (Criteria) this;
        }

        public Criteria andFadvclassidEqualTo(Long value) {
            addCriterion("FAdvClassId =", value, "fadvclassid");
            return (Criteria) this;
        }

        public Criteria andFadvclassidNotEqualTo(Long value) {
            addCriterion("FAdvClassId <>", value, "fadvclassid");
            return (Criteria) this;
        }

        public Criteria andFadvclassidGreaterThan(Long value) {
            addCriterion("FAdvClassId >", value, "fadvclassid");
            return (Criteria) this;
        }

        public Criteria andFadvclassidGreaterThanOrEqualTo(Long value) {
            addCriterion("FAdvClassId >=", value, "fadvclassid");
            return (Criteria) this;
        }

        public Criteria andFadvclassidLessThan(Long value) {
            addCriterion("FAdvClassId <", value, "fadvclassid");
            return (Criteria) this;
        }

        public Criteria andFadvclassidLessThanOrEqualTo(Long value) {
            addCriterion("FAdvClassId <=", value, "fadvclassid");
            return (Criteria) this;
        }

        public Criteria andFadvclassidIn(List<Long> values) {
            addCriterion("FAdvClassId in", values, "fadvclassid");
            return (Criteria) this;
        }

        public Criteria andFadvclassidNotIn(List<Long> values) {
            addCriterion("FAdvClassId not in", values, "fadvclassid");
            return (Criteria) this;
        }

        public Criteria andFadvclassidBetween(Long value1, Long value2) {
            addCriterion("FAdvClassId between", value1, value2, "fadvclassid");
            return (Criteria) this;
        }

        public Criteria andFadvclassidNotBetween(Long value1, Long value2) {
            addCriterion("FAdvClassId not between", value1, value2, "fadvclassid");
            return (Criteria) this;
        }

        public Criteria andFdefinitionIsNull() {
            addCriterion("FDefinition is null");
            return (Criteria) this;
        }

        public Criteria andFdefinitionIsNotNull() {
            addCriterion("FDefinition is not null");
            return (Criteria) this;
        }

        public Criteria andFdefinitionEqualTo(String value) {
            addCriterion("FDefinition =", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionNotEqualTo(String value) {
            addCriterion("FDefinition <>", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionGreaterThan(String value) {
            addCriterion("FDefinition >", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionGreaterThanOrEqualTo(String value) {
            addCriterion("FDefinition >=", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionLessThan(String value) {
            addCriterion("FDefinition <", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionLessThanOrEqualTo(String value) {
            addCriterion("FDefinition <=", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionLike(String value) {
            addCriterion("FDefinition like", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionNotLike(String value) {
            addCriterion("FDefinition not like", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionIn(List<String> values) {
            addCriterion("FDefinition in", values, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionNotIn(List<String> values) {
            addCriterion("FDefinition not in", values, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionBetween(String value1, String value2) {
            addCriterion("FDefinition between", value1, value2, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionNotBetween(String value1, String value2) {
            addCriterion("FDefinition not between", value1, value2, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFbranchidIsNull() {
            addCriterion("FBranchId is null");
            return (Criteria) this;
        }

        public Criteria andFbranchidIsNotNull() {
            addCriterion("FBranchId is not null");
            return (Criteria) this;
        }

        public Criteria andFbranchidEqualTo(Long value) {
            addCriterion("FBranchId =", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidNotEqualTo(Long value) {
            addCriterion("FBranchId <>", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidGreaterThan(Long value) {
            addCriterion("FBranchId >", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidGreaterThanOrEqualTo(Long value) {
            addCriterion("FBranchId >=", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidLessThan(Long value) {
            addCriterion("FBranchId <", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidLessThanOrEqualTo(Long value) {
            addCriterion("FBranchId <=", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidIn(List<Long> values) {
            addCriterion("FBranchId in", values, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidNotIn(List<Long> values) {
            addCriterion("FBranchId not in", values, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidBetween(Long value1, Long value2) {
            addCriterion("FBranchId between", value1, value2, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidNotBetween(Long value1, Long value2) {
            addCriterion("FBranchId not between", value1, value2, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFcontractidIsNull() {
            addCriterion("Fcontractid is null");
            return (Criteria) this;
        }

        public Criteria andFcontractidIsNotNull() {
            addCriterion("Fcontractid is not null");
            return (Criteria) this;
        }

        public Criteria andFcontractidEqualTo(Long value) {
            addCriterion("Fcontractid =", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidNotEqualTo(Long value) {
            addCriterion("Fcontractid <>", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidGreaterThan(Long value) {
            addCriterion("Fcontractid >", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidGreaterThanOrEqualTo(Long value) {
            addCriterion("Fcontractid >=", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidLessThan(Long value) {
            addCriterion("Fcontractid <", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidLessThanOrEqualTo(Long value) {
            addCriterion("Fcontractid <=", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidIn(List<Long> values) {
            addCriterion("Fcontractid in", values, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidNotIn(List<Long> values) {
            addCriterion("Fcontractid not in", values, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidBetween(Long value1, Long value2) {
            addCriterion("Fcontractid between", value1, value2, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidNotBetween(Long value1, Long value2) {
            addCriterion("Fcontractid not between", value1, value2, "fcontractid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_resource
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 12 17:34:02 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = "t_resource."+condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = "t_resource."+condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = "t_resource."+condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}