package com.evmtv.epg.entity;

import com.evmtv.epg.request.BaseRequest;

public class TTimePeriod extends BaseRequest{
    /**
	 * @field serialVersionUID
	 * @field_type long
	 */
	private static final long serialVersionUID = -5932460918900641109L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_period.ID
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    private Long id;

	// 广告位
	private String adv;
	//版本号
	private Long rvid;
	// 分公司
	private String branch;
	// 广告位解析度
	private String fdefinition;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_period.FStartTime
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    private String fstarttime;

    @Override
	public String toString() {
		return "TTimePeriod [id=" + id + ", adv=" + adv + ", rvid=" + rvid
				+ ", branch=" + branch + ", fdefinition=" + fdefinition
				+ ", fstarttime=" + fstarttime + ", fendtime=" + fendtime
				+ ", fadvclassid=" + fadvclassid + ", fbranchid=" + fbranchid
				+ ", freleaseversionid=" + freleaseversionid + ", fpositionid="
				+ fpositionid + ", fversionadvid=" + fversionadvid + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_period.FEndTime
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    private String fendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_period.FAdvClassId
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    private Long fadvclassid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_period.FBranchId
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    private Long fbranchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_period.FDeleted
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    private String fdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_period.FReleaseVersionId
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    private Long freleaseversionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_period.FPositionId
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    private Integer fpositionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_period.FVersionAdvId
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    private Long fversionadvid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_period.ID
     *
     * @return the value of t_time_period.ID
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_period.ID
     *
     * @param id the value for t_time_period.ID
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_period.FStartTime
     *
     * @return the value of t_time_period.FStartTime
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public String getFstarttime() {
        return fstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_period.FStartTime
     *
     * @param fstarttime the value for t_time_period.FStartTime
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public void setFstarttime(String fstarttime) {
        this.fstarttime = fstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_period.FEndTime
     *
     * @return the value of t_time_period.FEndTime
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public String getFendtime() {
        return fendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_period.FEndTime
     *
     * @param fendtime the value for t_time_period.FEndTime
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public void setFendtime(String fendtime) {
        this.fendtime = fendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_period.FAdvClassId
     *
     * @return the value of t_time_period.FAdvClassId
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public Long getFadvclassid() {
        return fadvclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_period.FAdvClassId
     *
     * @param fadvclassid the value for t_time_period.FAdvClassId
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public void setFadvclassid(Long fadvclassid) {
        this.fadvclassid = fadvclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_period.FBranchId
     *
     * @return the value of t_time_period.FBranchId
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public Long getFbranchid() {
        return fbranchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_period.FBranchId
     *
     * @param fbranchid the value for t_time_period.FBranchId
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public void setFbranchid(Long fbranchid) {
        this.fbranchid = fbranchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_period.FDeleted
     *
     * @return the value of t_time_period.FDeleted
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public String getFdeleted() {
        return fdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_period.FDeleted
     *
     * @param fdeleted the value for t_time_period.FDeleted
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public void setFdeleted(String fdeleted) {
        this.fdeleted = fdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_period.FReleaseVersionId
     *
     * @return the value of t_time_period.FReleaseVersionId
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public Long getFreleaseversionid() {
        return freleaseversionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_period.FReleaseVersionId
     *
     * @param freleaseversionid the value for t_time_period.FReleaseVersionId
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public void setFreleaseversionid(Long freleaseversionid) {
        this.freleaseversionid = freleaseversionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_period.FPositionId
     *
     * @return the value of t_time_period.FPositionId
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public Integer getFpositionid() {
        return fpositionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_period.FPositionId
     *
     * @param fpositionid the value for t_time_period.FPositionId
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public void setFpositionid(Integer fpositionid) {
        this.fpositionid = fpositionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_period.FVersionAdvId
     *
     * @return the value of t_time_period.FVersionAdvId
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public Long getFversionadvid() {
        return fversionadvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_period.FVersionAdvId
     *
     * @param fversionadvid the value for t_time_period.FVersionAdvId
     *
     * @mbggenerated Tue Nov 12 11:04:19 CST 2013
     */
    public void setFversionadvid(Long fversionadvid) {
        this.fversionadvid = fversionadvid;
    }

	public String getAdv() {
		return adv;
	}

	public void setAdv(String adv) {
		this.adv = adv;
	}

	public Long getRvid() {
		return rvid;
	}

	public void setRvid(Long rvid) {
		this.rvid = rvid;
	}

	public String getBranch() {
		return branch;
	}

	public void setBranch(String branch) {
		this.branch = branch;
	}

	public String getFdefinition() {
		return fdefinition;
	}

	public void setFdefinition(String fdefinition) {
		this.fdefinition = fdefinition;
	}
}