package com.evmtv.epg.entity;

import com.evmtv.epg.request.UserNodeStatus;

public class TUserNodeStatus extends UserNodeStatus{
    /**
	 * @field serialVersionUID
	 * @field_type long
	 */
	private static final long serialVersionUID = 826847191970277597L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_node_status.ID
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_node_status.FUserNodeId
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    private Long fusernodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_node_status.FUserId
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    private Long fuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_node_status.FStatus
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    private String fstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_node_status.FCreateTime
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    private String fcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_node_status.FBranchId
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    private Long fbranchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_node_status.FSourceId
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    private Long fsourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_node_status.FContractId
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    private Long fcontractid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_node_status.FRemark
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    private String fremark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_node_status.ID
     *
     * @return the value of t_user_node_status.ID
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_node_status.ID
     *
     * @param id the value for t_user_node_status.ID
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_node_status.FUserNodeId
     *
     * @return the value of t_user_node_status.FUserNodeId
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public Long getFusernodeid() {
        return fusernodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_node_status.FUserNodeId
     *
     * @param fusernodeid the value for t_user_node_status.FUserNodeId
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public void setFusernodeid(Long fusernodeid) {
        this.fusernodeid = fusernodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_node_status.FUserId
     *
     * @return the value of t_user_node_status.FUserId
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public Long getFuserid() {
        return fuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_node_status.FUserId
     *
     * @param fuserid the value for t_user_node_status.FUserId
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public void setFuserid(Long fuserid) {
        this.fuserid = fuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_node_status.FStatus
     *
     * @return the value of t_user_node_status.FStatus
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public String getFstatus() {
        return fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_node_status.FStatus
     *
     * @param fstatus the value for t_user_node_status.FStatus
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public void setFstatus(String fstatus) {
        this.fstatus = fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_node_status.FCreateTime
     *
     * @return the value of t_user_node_status.FCreateTime
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public String getFcreatetime() {
        return fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_node_status.FCreateTime
     *
     * @param fcreatetime the value for t_user_node_status.FCreateTime
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public void setFcreatetime(String fcreatetime) {
        this.fcreatetime = fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_node_status.FBranchId
     *
     * @return the value of t_user_node_status.FBranchId
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public Long getFbranchid() {
        return fbranchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_node_status.FBranchId
     *
     * @param fbranchid the value for t_user_node_status.FBranchId
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public void setFbranchid(Long fbranchid) {
        this.fbranchid = fbranchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_node_status.FSourceId
     *
     * @return the value of t_user_node_status.FSourceId
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public Long getFsourceid() {
        return fsourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_node_status.FSourceId
     *
     * @param fsourceid the value for t_user_node_status.FSourceId
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public void setFsourceid(Long fsourceid) {
        this.fsourceid = fsourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_node_status.FContractId
     *
     * @return the value of t_user_node_status.FContractId
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public Long getFcontractid() {
        return fcontractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_node_status.FContractId
     *
     * @param fcontractid the value for t_user_node_status.FContractId
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public void setFcontractid(Long fcontractid) {
        this.fcontractid = fcontractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_node_status.FRemark
     *
     * @return the value of t_user_node_status.FRemark
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public String getFremark() {
        return fremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_node_status.FRemark
     *
     * @param fremark the value for t_user_node_status.FRemark
     *
     * @mbggenerated Sun Aug 04 18:43:41 CST 2013
     */
    public void setFremark(String fremark) {
        this.fremark = fremark;
    }
}