package com.evmtv.epg.entity;

import java.util.ArrayList;
import java.util.List;

import com.evmtv.epg.request.BaseRequest;

public class TBranchSourceReleaseExample extends BaseRequest{
    /**
	 * @field serialVersionUID
	 * @field_type long
	 */
	private static final long serialVersionUID = -8023123800277796795L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    protected String orderByClause;
    /**
     * 分组
     */
    protected String groupByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public TBranchSourceReleaseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
	 * @return the groupByClause
	 */
	public String getGroupByClause() {
		return groupByClause;
	}

	/**
	 * @param groupByClause the groupByClause to set
	 */
	public void setGroupByClause(String groupByClause) {
		this.groupByClause = groupByClause;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        groupByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFbranchidIsNull() {
            addCriterion("FBranchId is null");
            return (Criteria) this;
        }

        public Criteria andFbranchidIsNotNull() {
            addCriterion("FBranchId is not null");
            return (Criteria) this;
        }

        public Criteria andFbranchidEqualTo(Long value) {
            addCriterion("FBranchId =", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidNotEqualTo(Long value) {
            addCriterion("FBranchId <>", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidGreaterThan(Long value) {
            addCriterion("FBranchId >", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidGreaterThanOrEqualTo(Long value) {
            addCriterion("FBranchId >=", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidLessThan(Long value) {
            addCriterion("FBranchId <", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidLessThanOrEqualTo(Long value) {
            addCriterion("FBranchId <=", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidIn(List<Long> values) {
            addCriterion("FBranchId in", values, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidNotIn(List<Long> values) {
            addCriterion("FBranchId not in", values, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidBetween(Long value1, Long value2) {
            addCriterion("FBranchId between", value1, value2, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidNotBetween(Long value1, Long value2) {
            addCriterion("FBranchId not between", value1, value2, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFsourceidIsNull() {
            addCriterion("FSourceId is null");
            return (Criteria) this;
        }

        public Criteria andFsourceidIsNotNull() {
            addCriterion("FSourceId is not null");
            return (Criteria) this;
        }

        public Criteria andFsourceidEqualTo(Long value) {
            addCriterion("FSourceId =", value, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidNotEqualTo(Long value) {
            addCriterion("FSourceId <>", value, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidGreaterThan(Long value) {
            addCriterion("FSourceId >", value, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidGreaterThanOrEqualTo(Long value) {
            addCriterion("FSourceId >=", value, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidLessThan(Long value) {
            addCriterion("FSourceId <", value, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidLessThanOrEqualTo(Long value) {
            addCriterion("FSourceId <=", value, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidIn(List<Long> values) {
            addCriterion("FSourceId in", values, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidNotIn(List<Long> values) {
            addCriterion("FSourceId not in", values, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidBetween(Long value1, Long value2) {
            addCriterion("FSourceId between", value1, value2, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidNotBetween(Long value1, Long value2) {
            addCriterion("FSourceId not between", value1, value2, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIsNull() {
            addCriterion("FCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIsNotNull() {
            addCriterion("FCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeEqualTo(String value) {
            addCriterion("FCreateTime =", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotEqualTo(String value) {
            addCriterion("FCreateTime <>", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeGreaterThan(String value) {
            addCriterion("FCreateTime >", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("FCreateTime >=", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLessThan(String value) {
            addCriterion("FCreateTime <", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLessThanOrEqualTo(String value) {
            addCriterion("FCreateTime <=", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLike(String value) {
            addCriterion("FCreateTime like", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotLike(String value) {
            addCriterion("FCreateTime not like", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIn(List<String> values) {
            addCriterion("FCreateTime in", values, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotIn(List<String> values) {
            addCriterion("FCreateTime not in", values, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeBetween(String value1, String value2) {
            addCriterion("FCreateTime between", value1, value2, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotBetween(String value1, String value2) {
            addCriterion("FCreateTime not between", value1, value2, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIsNull() {
            addCriterion("FCreateUserId is null");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIsNotNull() {
            addCriterion("FCreateUserId is not null");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridEqualTo(Long value) {
            addCriterion("FCreateUserId =", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotEqualTo(Long value) {
            addCriterion("FCreateUserId <>", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridGreaterThan(Long value) {
            addCriterion("FCreateUserId >", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridGreaterThanOrEqualTo(Long value) {
            addCriterion("FCreateUserId >=", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridLessThan(Long value) {
            addCriterion("FCreateUserId <", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridLessThanOrEqualTo(Long value) {
            addCriterion("FCreateUserId <=", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIn(List<Long> values) {
            addCriterion("FCreateUserId in", values, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotIn(List<Long> values) {
            addCriterion("FCreateUserId not in", values, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridBetween(Long value1, Long value2) {
            addCriterion("FCreateUserId between", value1, value2, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotBetween(Long value1, Long value2) {
            addCriterion("FCreateUserId not between", value1, value2, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcontractidIsNull() {
            addCriterion("FContractId is null");
            return (Criteria) this;
        }

        public Criteria andFcontractidIsNotNull() {
            addCriterion("FContractId is not null");
            return (Criteria) this;
        }

        public Criteria andFcontractidEqualTo(Long value) {
            addCriterion("FContractId =", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidNotEqualTo(Long value) {
            addCriterion("FContractId <>", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidGreaterThan(Long value) {
            addCriterion("FContractId >", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidGreaterThanOrEqualTo(Long value) {
            addCriterion("FContractId >=", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidLessThan(Long value) {
            addCriterion("FContractId <", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidLessThanOrEqualTo(Long value) {
            addCriterion("FContractId <=", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidIn(List<Long> values) {
            addCriterion("FContractId in", values, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidNotIn(List<Long> values) {
            addCriterion("FContractId not in", values, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidBetween(Long value1, Long value2) {
            addCriterion("FContractId between", value1, value2, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidNotBetween(Long value1, Long value2) {
            addCriterion("FContractId not between", value1, value2, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFisusingIsNull() {
            addCriterion("FIsUsing is null");
            return (Criteria) this;
        }

        public Criteria andFisusingIsNotNull() {
            addCriterion("FIsUsing is not null");
            return (Criteria) this;
        }

        public Criteria andFisusingEqualTo(String value) {
            addCriterion("FIsUsing =", value, "fisusing");
            return (Criteria) this;
        }

        public Criteria andFisusingNotEqualTo(String value) {
            addCriterion("FIsUsing <>", value, "fisusing");
            return (Criteria) this;
        }

        public Criteria andFisusingGreaterThan(String value) {
            addCriterion("FIsUsing >", value, "fisusing");
            return (Criteria) this;
        }

        public Criteria andFisusingGreaterThanOrEqualTo(String value) {
            addCriterion("FIsUsing >=", value, "fisusing");
            return (Criteria) this;
        }

        public Criteria andFisusingLessThan(String value) {
            addCriterion("FIsUsing <", value, "fisusing");
            return (Criteria) this;
        }

        public Criteria andFisusingLessThanOrEqualTo(String value) {
            addCriterion("FIsUsing <=", value, "fisusing");
            return (Criteria) this;
        }

        public Criteria andFisusingLike(String value) {
            addCriterion("FIsUsing like", value, "fisusing");
            return (Criteria) this;
        }

        public Criteria andFisusingNotLike(String value) {
            addCriterion("FIsUsing not like", value, "fisusing");
            return (Criteria) this;
        }

        public Criteria andFisusingIn(List<String> values) {
            addCriterion("FIsUsing in", values, "fisusing");
            return (Criteria) this;
        }

        public Criteria andFisusingNotIn(List<String> values) {
            addCriterion("FIsUsing not in", values, "fisusing");
            return (Criteria) this;
        }

        public Criteria andFisusingBetween(String value1, String value2) {
            addCriterion("FIsUsing between", value1, value2, "fisusing");
            return (Criteria) this;
        }

        public Criteria andFisusingNotBetween(String value1, String value2) {
            addCriterion("FIsUsing not between", value1, value2, "fisusing");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIsNull() {
            addCriterion("FUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIsNotNull() {
            addCriterion("FUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeEqualTo(String value) {
            addCriterion("FUpdateTime =", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotEqualTo(String value) {
            addCriterion("FUpdateTime <>", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeGreaterThan(String value) {
            addCriterion("FUpdateTime >", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("FUpdateTime >=", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLessThan(String value) {
            addCriterion("FUpdateTime <", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLessThanOrEqualTo(String value) {
            addCriterion("FUpdateTime <=", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLike(String value) {
            addCriterion("FUpdateTime like", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotLike(String value) {
            addCriterion("FUpdateTime not like", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIn(List<String> values) {
            addCriterion("FUpdateTime in", values, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotIn(List<String> values) {
            addCriterion("FUpdateTime not in", values, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeBetween(String value1, String value2) {
            addCriterion("FUpdateTime between", value1, value2, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotBetween(String value1, String value2) {
            addCriterion("FUpdateTime not between", value1, value2, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFversionIsNull() {
            addCriterion("FVersion is null");
            return (Criteria) this;
        }

        public Criteria andFversionIsNotNull() {
            addCriterion("FVersion is not null");
            return (Criteria) this;
        }

        public Criteria andFversionEqualTo(String value) {
            addCriterion("FVersion =", value, "fversion");
            return (Criteria) this;
        }

        public Criteria andFversionNotEqualTo(String value) {
            addCriterion("FVersion <>", value, "fversion");
            return (Criteria) this;
        }

        public Criteria andFversionGreaterThan(String value) {
            addCriterion("FVersion >", value, "fversion");
            return (Criteria) this;
        }

        public Criteria andFversionGreaterThanOrEqualTo(String value) {
            addCriterion("FVersion >=", value, "fversion");
            return (Criteria) this;
        }

        public Criteria andFversionLessThan(String value) {
            addCriterion("FVersion <", value, "fversion");
            return (Criteria) this;
        }

        public Criteria andFversionLessThanOrEqualTo(String value) {
            addCriterion("FVersion <=", value, "fversion");
            return (Criteria) this;
        }

        public Criteria andFversionLike(String value) {
            addCriterion("FVersion like", value, "fversion");
            return (Criteria) this;
        }

        public Criteria andFversionNotLike(String value) {
            addCriterion("FVersion not like", value, "fversion");
            return (Criteria) this;
        }

        public Criteria andFversionIn(List<String> values) {
            addCriterion("FVersion in", values, "fversion");
            return (Criteria) this;
        }

        public Criteria andFversionNotIn(List<String> values) {
            addCriterion("FVersion not in", values, "fversion");
            return (Criteria) this;
        }

        public Criteria andFversionBetween(String value1, String value2) {
            addCriterion("FVersion between", value1, value2, "fversion");
            return (Criteria) this;
        }

        public Criteria andFversionNotBetween(String value1, String value2) {
            addCriterion("FVersion not between", value1, value2, "fversion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_branch_source_release
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 13 13:00:03 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}