package com.evmtv.epg.mapper;

import com.evmtv.epg.entity.TSource;
import com.evmtv.epg.entity.TVersionSource;
import com.evmtv.epg.entity.TVersionSourceExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TVersionSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    int countByExample(TVersionSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    int deleteByExample(TVersionSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    int insert(TVersionSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    int insertSelective(TVersionSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    List<TVersionSource> selectByExample(TVersionSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    TVersionSource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    int updateByExampleSelective(@Param("record") TVersionSource record, @Param("example") TVersionSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    int updateByExample(@Param("record") TVersionSource record, @Param("example") TVersionSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    int updateByPrimaryKeySelective(TVersionSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    int updateByPrimaryKey(TVersionSource record);
    /**
     * 批量新增
     * @param vs
     * @return
     */
	int batchInsert(List<TVersionSource> vs);
	/**
	 * 查询广告版本信息
	 * @param record
	 * @return
	 */
	List<TSource> selectSourceJoinByVersionSource(TVersionSource record);
	/**
	 * 记录数
	 * @param record
	 * @return
	 */
	int countSourceJoinByVersionSource(TVersionSource record);
	/**
	 * 查询广告使用版本
	 * @param sids
	 * @return
	 */
	List<Long> selectRvidBySid(@Param("sids")String sids);
}