package com.evmtv.epg.entity;

import com.evmtv.epg.request.BaseRequest;

public class TAdv extends BaseRequest{
    /**
	 * @field serialVersionUID
	 * @field_type long
	 */
	private static final long serialVersionUID = -6448202287424040081L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.ID
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private Long id;
    /**
     * 广告版本索引
     */
    private Long vaid;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.FCreateTime
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private String fcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.FCreateUserId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private Long fcreateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.FUpdateTime
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private String fupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.FUpdateUserId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private Long fupdateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.FGUID
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private String fguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.FChecked
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private String fchecked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.FDeleted
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private String fdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.FFreezed
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private String ffreezed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.FAdvClassId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private Long fadvclassid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.FType
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private String ftype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.FDefinition
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private String fdefinition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.FBranchId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private Long fbranchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.FContractId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private Long fcontractid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.FPositionId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private Integer fpositionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adv.FVersion
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    private Long fversion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.ID
     *
     * @return the value of t_adv.ID
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.ID
     *
     * @param id the value for t_adv.ID
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    @Override
	public String toString() {
		return "TAdv [id=" + id + ", vaid=" + vaid + ", fguid=" + fguid
				+ ", fadvclassid=" + fadvclassid + ", ftype=" + ftype
				+ ", fdefinition=" + fdefinition + ", fbranchid=" + fbranchid
				+ ", fpositionid=" + fpositionid + "]";
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.FCreateTime
     *
     * @return the value of t_adv.FCreateTime
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public String getFcreatetime() {
        return fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.FCreateTime
     *
     * @param fcreatetime the value for t_adv.FCreateTime
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setFcreatetime(String fcreatetime) {
        this.fcreatetime = fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.FCreateUserId
     *
     * @return the value of t_adv.FCreateUserId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public Long getFcreateuserid() {
        return fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.FCreateUserId
     *
     * @param fcreateuserid the value for t_adv.FCreateUserId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setFcreateuserid(Long fcreateuserid) {
        this.fcreateuserid = fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.FUpdateTime
     *
     * @return the value of t_adv.FUpdateTime
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public String getFupdatetime() {
        return fupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.FUpdateTime
     *
     * @param fupdatetime the value for t_adv.FUpdateTime
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setFupdatetime(String fupdatetime) {
        this.fupdatetime = fupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.FUpdateUserId
     *
     * @return the value of t_adv.FUpdateUserId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public Long getFupdateuserid() {
        return fupdateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.FUpdateUserId
     *
     * @param fupdateuserid the value for t_adv.FUpdateUserId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setFupdateuserid(Long fupdateuserid) {
        this.fupdateuserid = fupdateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.FGUID
     *
     * @return the value of t_adv.FGUID
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public String getFguid() {
        return fguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.FGUID
     *
     * @param fguid the value for t_adv.FGUID
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setFguid(String fguid) {
        this.fguid = fguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.FChecked
     *
     * @return the value of t_adv.FChecked
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public String getFchecked() {
        return fchecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.FChecked
     *
     * @param fchecked the value for t_adv.FChecked
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setFchecked(String fchecked) {
        this.fchecked = fchecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.FDeleted
     *
     * @return the value of t_adv.FDeleted
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public String getFdeleted() {
        return fdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.FDeleted
     *
     * @param fdeleted the value for t_adv.FDeleted
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setFdeleted(String fdeleted) {
        this.fdeleted = fdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.FFreezed
     *
     * @return the value of t_adv.FFreezed
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public String getFfreezed() {
        return ffreezed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.FFreezed
     *
     * @param ffreezed the value for t_adv.FFreezed
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setFfreezed(String ffreezed) {
        this.ffreezed = ffreezed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.FAdvClassId
     *
     * @return the value of t_adv.FAdvClassId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public Long getFadvclassid() {
        return fadvclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.FAdvClassId
     *
     * @param fadvclassid the value for t_adv.FAdvClassId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setFadvclassid(Long fadvclassid) {
        this.fadvclassid = fadvclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.FType
     *
     * @return the value of t_adv.FType
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public String getFtype() {
        return ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.FType
     *
     * @param ftype the value for t_adv.FType
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setFtype(String ftype) {
        this.ftype = ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.FDefinition
     *
     * @return the value of t_adv.FDefinition
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public String getFdefinition() {
        return fdefinition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.FDefinition
     *
     * @param fdefinition the value for t_adv.FDefinition
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setFdefinition(String fdefinition) {
        this.fdefinition = fdefinition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.FBranchId
     *
     * @return the value of t_adv.FBranchId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public Long getFbranchid() {
        return fbranchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.FBranchId
     *
     * @param fbranchid the value for t_adv.FBranchId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setFbranchid(Long fbranchid) {
        this.fbranchid = fbranchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.FContractId
     *
     * @return the value of t_adv.FContractId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public Long getFcontractid() {
        return fcontractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.FContractId
     *
     * @param fcontractid the value for t_adv.FContractId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setFcontractid(Long fcontractid) {
        this.fcontractid = fcontractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.FPositionId
     *
     * @return the value of t_adv.FPositionId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public Integer getFpositionid() {
        return fpositionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.FPositionId
     *
     * @param fpositionid the value for t_adv.FPositionId
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setFpositionid(Integer fpositionid) {
        this.fpositionid = fpositionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adv.FVersion
     *
     * @return the value of t_adv.FVersion
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public Long getFversion() {
        return fversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adv.FVersion
     *
     * @param fversion the value for t_adv.FVersion
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    public void setFversion(Long fversion) {
        this.fversion = fversion;
    }

	public Long getVaid() {
		return vaid;
	}

	public void setVaid(Long vaid) {
		this.vaid = vaid;
	}
}