package com.evmtv.epg.mapper;

import com.evmtv.epg.entity.TUserNode;
import com.evmtv.epg.entity.TUserNodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_node
     *
     * @mbggenerated Fri Aug 16 15:52:36 CST 2013
     */
    int countByExample(TUserNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_node
     *
     * @mbggenerated Fri Aug 16 15:52:36 CST 2013
     */
    int deleteByExample(TUserNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_node
     *
     * @mbggenerated Fri Aug 16 15:52:36 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_node
     *
     * @mbggenerated Fri Aug 16 15:52:36 CST 2013
     */
    int insert(TUserNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_node
     *
     * @mbggenerated Fri Aug 16 15:52:36 CST 2013
     */
    int insertSelective(TUserNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_node
     *
     * @mbggenerated Fri Aug 16 15:52:36 CST 2013
     */
    List<TUserNode> selectByExample(TUserNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_node
     *
     * @mbggenerated Fri Aug 16 15:52:36 CST 2013
     */
    TUserNode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_node
     *
     * @mbggenerated Fri Aug 16 15:52:36 CST 2013
     */
    int updateByExampleSelective(@Param("record") TUserNode record, @Param("example") TUserNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_node
     *
     * @mbggenerated Fri Aug 16 15:52:36 CST 2013
     */
    int updateByExample(@Param("record") TUserNode record, @Param("example") TUserNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_node
     *
     * @mbggenerated Fri Aug 16 15:52:36 CST 2013
     */
    int updateByPrimaryKeySelective(TUserNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_node
     *
     * @mbggenerated Fri Aug 16 15:52:36 CST 2013
     */
    int updateByPrimaryKey(TUserNode record);

	List<TUserNode> selectByExampleWithBranch(TUserNodeExample example);
}