package com.evmtv.epg.entity;

import java.util.ArrayList;
import java.util.List;

public class TVersionSourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    public TVersionSourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFsourceidIsNull() {
            addCriterion("FSourceId is null");
            return (Criteria) this;
        }

        public Criteria andFsourceidIsNotNull() {
            addCriterion("FSourceId is not null");
            return (Criteria) this;
        }

        public Criteria andFsourceidEqualTo(Long value) {
            addCriterion("FSourceId =", value, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidNotEqualTo(Long value) {
            addCriterion("FSourceId <>", value, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidGreaterThan(Long value) {
            addCriterion("FSourceId >", value, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidGreaterThanOrEqualTo(Long value) {
            addCriterion("FSourceId >=", value, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidLessThan(Long value) {
            addCriterion("FSourceId <", value, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidLessThanOrEqualTo(Long value) {
            addCriterion("FSourceId <=", value, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidIn(List<Long> values) {
            addCriterion("FSourceId in", values, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidNotIn(List<Long> values) {
            addCriterion("FSourceId not in", values, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidBetween(Long value1, Long value2) {
            addCriterion("FSourceId between", value1, value2, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFsourceidNotBetween(Long value1, Long value2) {
            addCriterion("FSourceId not between", value1, value2, "fsourceid");
            return (Criteria) this;
        }

        public Criteria andFchannelsidIsNull() {
            addCriterion("FChannelsId is null");
            return (Criteria) this;
        }

        public Criteria andFchannelsidIsNotNull() {
            addCriterion("FChannelsId is not null");
            return (Criteria) this;
        }

        public Criteria andFchannelsidEqualTo(String value) {
            addCriterion("FChannelsId =", value, "fchannelsid");
            return (Criteria) this;
        }

        public Criteria andFchannelsidNotEqualTo(String value) {
            addCriterion("FChannelsId <>", value, "fchannelsid");
            return (Criteria) this;
        }

        public Criteria andFchannelsidGreaterThan(String value) {
            addCriterion("FChannelsId >", value, "fchannelsid");
            return (Criteria) this;
        }

        public Criteria andFchannelsidGreaterThanOrEqualTo(String value) {
            addCriterion("FChannelsId >=", value, "fchannelsid");
            return (Criteria) this;
        }

        public Criteria andFchannelsidLessThan(String value) {
            addCriterion("FChannelsId <", value, "fchannelsid");
            return (Criteria) this;
        }

        public Criteria andFchannelsidLessThanOrEqualTo(String value) {
            addCriterion("FChannelsId <=", value, "fchannelsid");
            return (Criteria) this;
        }

        public Criteria andFchannelsidLike(String value) {
            addCriterion("FChannelsId like", value, "fchannelsid");
            return (Criteria) this;
        }

        public Criteria andFchannelsidNotLike(String value) {
            addCriterion("FChannelsId not like", value, "fchannelsid");
            return (Criteria) this;
        }

        public Criteria andFchannelsidIn(List<String> values) {
            addCriterion("FChannelsId in", values, "fchannelsid");
            return (Criteria) this;
        }

        public Criteria andFchannelsidNotIn(List<String> values) {
            addCriterion("FChannelsId not in", values, "fchannelsid");
            return (Criteria) this;
        }

        public Criteria andFchannelsidBetween(String value1, String value2) {
            addCriterion("FChannelsId between", value1, value2, "fchannelsid");
            return (Criteria) this;
        }

        public Criteria andFchannelsidNotBetween(String value1, String value2) {
            addCriterion("FChannelsId not between", value1, value2, "fchannelsid");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupidIsNull() {
            addCriterion("FChannelGroupId is null");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupidIsNotNull() {
            addCriterion("FChannelGroupId is not null");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupidEqualTo(Long value) {
            addCriterion("FChannelGroupId =", value, "fchannelgroupid");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupidNotEqualTo(Long value) {
            addCriterion("FChannelGroupId <>", value, "fchannelgroupid");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupidGreaterThan(Long value) {
            addCriterion("FChannelGroupId >", value, "fchannelgroupid");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupidGreaterThanOrEqualTo(Long value) {
            addCriterion("FChannelGroupId >=", value, "fchannelgroupid");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupidLessThan(Long value) {
            addCriterion("FChannelGroupId <", value, "fchannelgroupid");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupidLessThanOrEqualTo(Long value) {
            addCriterion("FChannelGroupId <=", value, "fchannelgroupid");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupidIn(List<Long> values) {
            addCriterion("FChannelGroupId in", values, "fchannelgroupid");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupidNotIn(List<Long> values) {
            addCriterion("FChannelGroupId not in", values, "fchannelgroupid");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupidBetween(Long value1, Long value2) {
            addCriterion("FChannelGroupId between", value1, value2, "fchannelgroupid");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupidNotBetween(Long value1, Long value2) {
            addCriterion("FChannelGroupId not between", value1, value2, "fchannelgroupid");
            return (Criteria) this;
        }

        public Criteria andFreleaseversionidIsNull() {
            addCriterion("FReleaseVersionId is null");
            return (Criteria) this;
        }

        public Criteria andFreleaseversionidIsNotNull() {
            addCriterion("FReleaseVersionId is not null");
            return (Criteria) this;
        }

        public Criteria andFreleaseversionidEqualTo(Long value) {
            addCriterion("FReleaseVersionId =", value, "freleaseversionid");
            return (Criteria) this;
        }

        public Criteria andFreleaseversionidNotEqualTo(Long value) {
            addCriterion("FReleaseVersionId <>", value, "freleaseversionid");
            return (Criteria) this;
        }

        public Criteria andFreleaseversionidGreaterThan(Long value) {
            addCriterion("FReleaseVersionId >", value, "freleaseversionid");
            return (Criteria) this;
        }

        public Criteria andFreleaseversionidGreaterThanOrEqualTo(Long value) {
            addCriterion("FReleaseVersionId >=", value, "freleaseversionid");
            return (Criteria) this;
        }

        public Criteria andFreleaseversionidLessThan(Long value) {
            addCriterion("FReleaseVersionId <", value, "freleaseversionid");
            return (Criteria) this;
        }

        public Criteria andFreleaseversionidLessThanOrEqualTo(Long value) {
            addCriterion("FReleaseVersionId <=", value, "freleaseversionid");
            return (Criteria) this;
        }

        public Criteria andFreleaseversionidIn(List<Long> values) {
            addCriterion("FReleaseVersionId in", values, "freleaseversionid");
            return (Criteria) this;
        }

        public Criteria andFreleaseversionidNotIn(List<Long> values) {
            addCriterion("FReleaseVersionId not in", values, "freleaseversionid");
            return (Criteria) this;
        }

        public Criteria andFreleaseversionidBetween(Long value1, Long value2) {
            addCriterion("FReleaseVersionId between", value1, value2, "freleaseversionid");
            return (Criteria) this;
        }

        public Criteria andFreleaseversionidNotBetween(Long value1, Long value2) {
            addCriterion("FReleaseVersionId not between", value1, value2, "freleaseversionid");
            return (Criteria) this;
        }

        public Criteria andFtimeperiodidIsNull() {
            addCriterion("FTimeperiodId is null");
            return (Criteria) this;
        }

        public Criteria andFtimeperiodidIsNotNull() {
            addCriterion("FTimeperiodId is not null");
            return (Criteria) this;
        }

        public Criteria andFtimeperiodidEqualTo(Long value) {
            addCriterion("FTimeperiodId =", value, "ftimeperiodid");
            return (Criteria) this;
        }

        public Criteria andFtimeperiodidNotEqualTo(Long value) {
            addCriterion("FTimeperiodId <>", value, "ftimeperiodid");
            return (Criteria) this;
        }

        public Criteria andFtimeperiodidGreaterThan(Long value) {
            addCriterion("FTimeperiodId >", value, "ftimeperiodid");
            return (Criteria) this;
        }

        public Criteria andFtimeperiodidGreaterThanOrEqualTo(Long value) {
            addCriterion("FTimeperiodId >=", value, "ftimeperiodid");
            return (Criteria) this;
        }

        public Criteria andFtimeperiodidLessThan(Long value) {
            addCriterion("FTimeperiodId <", value, "ftimeperiodid");
            return (Criteria) this;
        }

        public Criteria andFtimeperiodidLessThanOrEqualTo(Long value) {
            addCriterion("FTimeperiodId <=", value, "ftimeperiodid");
            return (Criteria) this;
        }

        public Criteria andFtimeperiodidIn(List<Long> values) {
            addCriterion("FTimeperiodId in", values, "ftimeperiodid");
            return (Criteria) this;
        }

        public Criteria andFtimeperiodidNotIn(List<Long> values) {
            addCriterion("FTimeperiodId not in", values, "ftimeperiodid");
            return (Criteria) this;
        }

        public Criteria andFtimeperiodidBetween(Long value1, Long value2) {
            addCriterion("FTimeperiodId between", value1, value2, "ftimeperiodid");
            return (Criteria) this;
        }

        public Criteria andFtimeperiodidNotBetween(Long value1, Long value2) {
            addCriterion("FTimeperiodId not between", value1, value2, "ftimeperiodid");
            return (Criteria) this;
        }

        public Criteria andFadvidIsNull() {
            addCriterion("FAdvId is null");
            return (Criteria) this;
        }

        public Criteria andFadvidIsNotNull() {
            addCriterion("FAdvId is not null");
            return (Criteria) this;
        }

        public Criteria andFadvidEqualTo(Long value) {
            addCriterion("FAdvId =", value, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidNotEqualTo(Long value) {
            addCriterion("FAdvId <>", value, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidGreaterThan(Long value) {
            addCriterion("FAdvId >", value, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidGreaterThanOrEqualTo(Long value) {
            addCriterion("FAdvId >=", value, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidLessThan(Long value) {
            addCriterion("FAdvId <", value, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidLessThanOrEqualTo(Long value) {
            addCriterion("FAdvId <=", value, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidIn(List<Long> values) {
            addCriterion("FAdvId in", values, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidNotIn(List<Long> values) {
            addCriterion("FAdvId not in", values, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidBetween(Long value1, Long value2) {
            addCriterion("FAdvId between", value1, value2, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFadvidNotBetween(Long value1, Long value2) {
            addCriterion("FAdvId not between", value1, value2, "fadvid");
            return (Criteria) this;
        }

        public Criteria andFversionadvidIsNull() {
            addCriterion("FVersionAdvId is null");
            return (Criteria) this;
        }

        public Criteria andFversionadvidIsNotNull() {
            addCriterion("FVersionAdvId is not null");
            return (Criteria) this;
        }

        public Criteria andFversionadvidEqualTo(Long value) {
            addCriterion("FVersionAdvId =", value, "fversionadvid");
            return (Criteria) this;
        }

        public Criteria andFversionadvidNotEqualTo(Long value) {
            addCriterion("FVersionAdvId <>", value, "fversionadvid");
            return (Criteria) this;
        }

        public Criteria andFversionadvidGreaterThan(Long value) {
            addCriterion("FVersionAdvId >", value, "fversionadvid");
            return (Criteria) this;
        }

        public Criteria andFversionadvidGreaterThanOrEqualTo(Long value) {
            addCriterion("FVersionAdvId >=", value, "fversionadvid");
            return (Criteria) this;
        }

        public Criteria andFversionadvidLessThan(Long value) {
            addCriterion("FVersionAdvId <", value, "fversionadvid");
            return (Criteria) this;
        }

        public Criteria andFversionadvidLessThanOrEqualTo(Long value) {
            addCriterion("FVersionAdvId <=", value, "fversionadvid");
            return (Criteria) this;
        }

        public Criteria andFversionadvidIn(List<Long> values) {
            addCriterion("FVersionAdvId in", values, "fversionadvid");
            return (Criteria) this;
        }

        public Criteria andFversionadvidNotIn(List<Long> values) {
            addCriterion("FVersionAdvId not in", values, "fversionadvid");
            return (Criteria) this;
        }

        public Criteria andFversionadvidBetween(Long value1, Long value2) {
            addCriterion("FVersionAdvId between", value1, value2, "fversionadvid");
            return (Criteria) this;
        }

        public Criteria andFversionadvidNotBetween(Long value1, Long value2) {
            addCriterion("FVersionAdvId not between", value1, value2, "fversionadvid");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupIsNull() {
            addCriterion("FChannelGroup is null");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupIsNotNull() {
            addCriterion("FChannelGroup is not null");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupEqualTo(String value) {
            addCriterion("FChannelGroup =", value, "fchannelgroup");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupNotEqualTo(String value) {
            addCriterion("FChannelGroup <>", value, "fchannelgroup");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupGreaterThan(String value) {
            addCriterion("FChannelGroup >", value, "fchannelgroup");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupGreaterThanOrEqualTo(String value) {
            addCriterion("FChannelGroup >=", value, "fchannelgroup");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupLessThan(String value) {
            addCriterion("FChannelGroup <", value, "fchannelgroup");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupLessThanOrEqualTo(String value) {
            addCriterion("FChannelGroup <=", value, "fchannelgroup");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupLike(String value) {
            addCriterion("FChannelGroup like", value, "fchannelgroup");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupNotLike(String value) {
            addCriterion("FChannelGroup not like", value, "fchannelgroup");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupIn(List<String> values) {
            addCriterion("FChannelGroup in", values, "fchannelgroup");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupNotIn(List<String> values) {
            addCriterion("FChannelGroup not in", values, "fchannelgroup");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupBetween(String value1, String value2) {
            addCriterion("FChannelGroup between", value1, value2, "fchannelgroup");
            return (Criteria) this;
        }

        public Criteria andFchannelgroupNotBetween(String value1, String value2) {
            addCriterion("FChannelGroup not between", value1, value2, "fchannelgroup");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_version_source
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 11 11:15:31 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_version_source
     *
     * @mbggenerated Mon Nov 11 11:15:31 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}