package com.evmtv.epg.mapper;

import com.evmtv.epg.entity.TContract;
import com.evmtv.epg.entity.TContractExample;
import com.evmtv.epg.entity.TContractWithBLOBs;
import com.evmtv.epg.response.ContractResponse;
import com.evmtv.epg.statistics.StatisticsRequest;
import com.evmtv.epg.statistics.StatisticsResponse;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    int countByExample(TContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    int deleteByExample(TContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    int insert(TContractWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    int insertSelective(TContractWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    List<TContractWithBLOBs> selectByExampleWithBLOBs(TContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    List<TContract> selectByExample(TContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    TContractWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    int updateByExampleSelective(@Param("record") TContractWithBLOBs record, @Param("example") TContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") TContractWithBLOBs record, @Param("example") TContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    int updateByExample(@Param("record") TContract record, @Param("example") TContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    int updateByPrimaryKeySelective(TContractWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(TContractWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    int updateByPrimaryKey(TContract record);
    
    List<ContractResponse> selectContract(TContractExample example);
    
    List<StatisticsResponse> selectStatistics(StatisticsRequest request);
    
    List<StatisticsResponse> selectCompany(StatisticsRequest request);
    
    List<StatisticsResponse> selectAdv(StatisticsRequest request);
}