package com.evmtv.epg.entity;

import com.evmtv.epg.request.BaseRequest;

public class TIncFile extends BaseRequest{
    /**
	 * @field serialVersionUID
	 * @field_type long
	 */
	private static final long serialVersionUID = -6763535460037817324L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inc_file.ID
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    private Long id;

    private String branch;
    
    private String user;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inc_file.FBranchId
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    private Long fbranchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inc_file.FName
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    private String fname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inc_file.FVersion
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    private String fversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inc_file.FPath
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    private String fpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inc_file.FDesc
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    private String fdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inc_file.FCreateTime
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    private String fcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inc_file.FCreateUserId
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    private Long fcreateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inc_file.FStatus
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    private Integer fstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inc_file.ID
     *
     * @return the value of t_inc_file.ID
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inc_file.ID
     *
     * @param id the value for t_inc_file.ID
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inc_file.FBranchId
     *
     * @return the value of t_inc_file.FBranchId
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public Long getFbranchid() {
        return fbranchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inc_file.FBranchId
     *
     * @param fbranchid the value for t_inc_file.FBranchId
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public void setFbranchid(Long fbranchid) {
        this.fbranchid = fbranchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inc_file.FName
     *
     * @return the value of t_inc_file.FName
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inc_file.FName
     *
     * @param fname the value for t_inc_file.FName
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public void setFname(String fname) {
        this.fname = fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inc_file.FVersion
     *
     * @return the value of t_inc_file.FVersion
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public String getFversion() {
        return fversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inc_file.FVersion
     *
     * @param fversion the value for t_inc_file.FVersion
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public void setFversion(String fversion) {
        this.fversion = fversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inc_file.FPath
     *
     * @return the value of t_inc_file.FPath
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public String getFpath() {
        return fpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inc_file.FPath
     *
     * @param fpath the value for t_inc_file.FPath
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public void setFpath(String fpath) {
        this.fpath = fpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inc_file.FDesc
     *
     * @return the value of t_inc_file.FDesc
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public String getFdesc() {
        return fdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inc_file.FDesc
     *
     * @param fdesc the value for t_inc_file.FDesc
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public void setFdesc(String fdesc) {
        this.fdesc = fdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inc_file.FCreateTime
     *
     * @return the value of t_inc_file.FCreateTime
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public String getFcreatetime() {
        return fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inc_file.FCreateTime
     *
     * @param fcreatetime the value for t_inc_file.FCreateTime
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public void setFcreatetime(String fcreatetime) {
        this.fcreatetime = fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inc_file.FCreateUserId
     *
     * @return the value of t_inc_file.FCreateUserId
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public Long getFcreateuserid() {
        return fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inc_file.FCreateUserId
     *
     * @param fcreateuserid the value for t_inc_file.FCreateUserId
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public void setFcreateuserid(Long fcreateuserid) {
        this.fcreateuserid = fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inc_file.FStatus
     *
     * @return the value of t_inc_file.FStatus
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public Integer getFstatus() {
        return fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inc_file.FStatus
     *
     * @param fstatus the value for t_inc_file.FStatus
     *
     * @mbggenerated Tue Oct 29 16:50:31 CST 2013
     */
    public void setFstatus(Integer fstatus) {
        this.fstatus = fstatus;
    }

	public String getBranch() {
		return branch;
	}

	public void setBranch(String branch) {
		this.branch = branch;
	}

	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}
}