package com.evmtv.epg.mapper;

import com.evmtv.epg.entity.TAdv;
import com.evmtv.epg.entity.TAdvExample;
import com.evmtv.epg.entity.TAdvWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TAdvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    int countByExample(TAdvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    int deleteByExample(TAdvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    int insert(TAdvWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    int insertSelective(TAdvWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    List<TAdvWithBLOBs> selectByExampleWithBLOBs(TAdvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    List<TAdv> selectByExample(TAdvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    TAdvWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    int updateByExampleSelective(@Param("record") TAdvWithBLOBs record, @Param("example") TAdvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") TAdvWithBLOBs record, @Param("example") TAdvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    int updateByExample(@Param("record") TAdv record, @Param("example") TAdvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    int updateByPrimaryKeySelective(TAdvWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(TAdvWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv
     *
     * @mbggenerated Sat Nov 09 10:54:25 CST 2013
     */
    int updateByPrimaryKey(TAdv record);
    /**
     * 链表查询分公司广告位
     * @param example
     * @return
     */
    List<TAdv> selectBranchAdvByExample(TAdvExample example);
    /**
     * 批量新增
     * @param advs
     * @return
     */
	int batchInsert(List<TAdv> advs); 
}