package com.evmtv.epg.mapper;

import com.evmtv.epg.entity.TAdvClassConfig;
import com.evmtv.epg.entity.TAdvClassConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TAdvClassConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv_class_config
     *
     * @mbggenerated Wed Aug 21 23:45:14 CST 2013
     */
    int countByExample(TAdvClassConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv_class_config
     *
     * @mbggenerated Wed Aug 21 23:45:14 CST 2013
     */
    int deleteByExample(TAdvClassConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv_class_config
     *
     * @mbggenerated Wed Aug 21 23:45:14 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv_class_config
     *
     * @mbggenerated Wed Aug 21 23:45:14 CST 2013
     */
    int insert(TAdvClassConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv_class_config
     *
     * @mbggenerated Wed Aug 21 23:45:14 CST 2013
     */
    int insertSelective(TAdvClassConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv_class_config
     *
     * @mbggenerated Wed Aug 21 23:45:14 CST 2013
     */
    List<TAdvClassConfig> selectByExample(TAdvClassConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv_class_config
     *
     * @mbggenerated Wed Aug 21 23:45:14 CST 2013
     */
    TAdvClassConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv_class_config
     *
     * @mbggenerated Wed Aug 21 23:45:14 CST 2013
     */
    int updateByExampleSelective(@Param("record") TAdvClassConfig record, @Param("example") TAdvClassConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv_class_config
     *
     * @mbggenerated Wed Aug 21 23:45:14 CST 2013
     */
    int updateByExample(@Param("record") TAdvClassConfig record, @Param("example") TAdvClassConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv_class_config
     *
     * @mbggenerated Wed Aug 21 23:45:14 CST 2013
     */
    int updateByPrimaryKeySelective(TAdvClassConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adv_class_config
     *
     * @mbggenerated Wed Aug 21 23:45:14 CST 2013
     */
    int updateByPrimaryKey(TAdvClassConfig record);

    /**
     * 查询对象
     * @param config
     * @return
     */
    TAdvClassConfig selectByObject(TAdvClassConfigExample example);
}