package com.evmtv.epg.mapper;

import com.evmtv.epg.entity.TBranch;
import com.evmtv.epg.entity.TBranchExample;
import com.evmtv.epg.entity.TBranchWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    int countByExample(TBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    int deleteByExample(TBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    int insert(TBranchWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    int insertSelective(TBranchWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    List<TBranchWithBLOBs> selectByExampleWithBLOBs(TBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    List<TBranch> selectByExample(TBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    TBranchWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    int updateByExampleSelective(@Param("record") TBranchWithBLOBs record, @Param("example") TBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") TBranchWithBLOBs record, @Param("example") TBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    int updateByExample(@Param("record") TBranch record, @Param("example") TBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    int updateByPrimaryKeySelective(TBranchWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(TBranchWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated Thu Aug 22 14:34:35 CST 2013
     */
    int updateByPrimaryKey(TBranch record);
}