package com.evmtv.epg.mapper;

import com.evmtv.epg.entity.TBranchSourceRelease;
import com.evmtv.epg.entity.TBranchSourceReleaseExample;
import com.evmtv.epg.entity.TContractAdv;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBranchSourceReleaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    int countByExample(TBranchSourceReleaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    int deleteByExample(TBranchSourceReleaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    int insert(TBranchSourceRelease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    int insertSelective(TBranchSourceRelease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    List<TBranchSourceRelease> selectByExample(TBranchSourceReleaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    TBranchSourceRelease selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    int updateByExampleSelective(@Param("record") TBranchSourceRelease record, @Param("example") TBranchSourceReleaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    int updateByExample(@Param("record") TBranchSourceRelease record, @Param("example") TBranchSourceReleaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    int updateByPrimaryKeySelective(TBranchSourceRelease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_source_release
     *
     * @mbggenerated Fri Sep 13 13:00:03 CST 2013
     */
    int updateByPrimaryKey(TBranchSourceRelease record);
    /**
     * 查询广告位
     * @param example
     * @return
     */
    List<Long> selectSourceId(TBranchSourceReleaseExample example);
    /**
     * 获取最大创建时间
     * @param example
     * @return
     */
    String selectByCreateTime(TBranchSourceReleaseExample example);
    /**
     * 查询过期合同索引
     * @param fbranchid
     * @return
     */
    List<TContractAdv> selectExpiredContractId(@Param("fbranchid") Long fbranchid);
}