package com.evmtv.epg.mapper;

import com.evmtv.epg.entity.TContractAdv;
import com.evmtv.epg.entity.TContractAdvExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TContractAdvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    int countByExample(TContractAdvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    int deleteByExample(TContractAdvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    int insert(TContractAdv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    int insertSelective(TContractAdv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    List<TContractAdv> selectByExample(TContractAdvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    TContractAdv selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    int updateByExampleSelective(@Param("record") TContractAdv record, @Param("example") TContractAdvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    int updateByExample(@Param("record") TContractAdv record, @Param("example") TContractAdvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    int updateByPrimaryKeySelective(TContractAdv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract_adv
     *
     * @mbggenerated Sun Sep 08 11:51:54 CST 2013
     */
    int updateByPrimaryKey(TContractAdv record);
    /**
     * 根据和同索引查询
     * @param fcontracid
     * @return
     */
    List<TContractAdv> selectByContractId(@Param("fcontractid") Long fcontractid);
    /***
     * 查询合同广告素材信息
     * @param fcontractid
     * @return
     */
    List<TContractAdv> selectResourceByContractId(@Param("fcontractid") Long fcontractid);
    /**
     * 根据分公司索引查询
     * @param fbranchid
     * @return
     */
	List<TContractAdv> selectByFbranchId(@Param("fbranchid") Long fbranchid);
	
    /**
     * 根据分公司索引查询广告位
     * @param fbranchid
     * @return
     */
	List<TContractAdv> selectAdvByFbranchId(@Param("fbranchid") Long fbranchid);
	
	/**
	 * 合同对象
	 * @param caid
	 * @return
	 */
    TContractAdv selectObjectByContractId(@Param("carid") Long carid);
}