package com.evmtv.epg.mapper;

import com.evmtv.epg.entity.TNodeStatus;
import com.evmtv.epg.entity.TNodeStatusExample;
import com.evmtv.epg.request.NodeStatusExpand;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TNodeStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node_status
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    int countByExample(TNodeStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node_status
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    int deleteByExample(TNodeStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node_status
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node_status
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    int insert(TNodeStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node_status
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    int insertSelective(TNodeStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node_status
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    List<TNodeStatus> selectByExampleWithBLOBs(TNodeStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node_status
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    List<TNodeStatus> selectByExample(TNodeStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node_status
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    TNodeStatus selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node_status
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    int updateByExampleSelective(@Param("record") TNodeStatus record, @Param("example") TNodeStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node_status
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") TNodeStatus record, @Param("example") TNodeStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node_status
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    int updateByExample(@Param("record") TNodeStatus record, @Param("example") TNodeStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node_status
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    int updateByPrimaryKeySelective(TNodeStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node_status
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(TNodeStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node_status
     *
     * @mbggenerated Mon Dec 02 13:40:29 CST 2013
     */
    int updateByPrimaryKey(TNodeStatus record);
    /**
     * 查询
     * @param fcontractadvresourceid
     * @return
     */
	List<TNodeStatus> selectByNodeStatus(TNodeStatus record);
	
	/**
	 * 根据用户查询
	 * @param fuserid
	 * @return
	 */
	List<NodeStatusExpand> selectByUserId(TNodeStatus record);
	/**
	 * 记录数
	 * @param fuserid
	 * @return
	 */
	int countByUserId(TNodeStatus record);

	/**
	 * @param cid
	 * @return
	 */
	TNodeStatus queryByContractId(Long cid);

	/**
	 * 根据父节点查询
	 * @param pid
	 * @return
	 */
	TNodeStatus selectByParentId(Long pid);

	/**
	 * 根据合同广告位索引或版本索引和节点索引查询
	 * @param carid
	 * @param rvid
	 * @param nid
	 * @return
	 */
	TNodeStatus selectByCaridOrRvidAndNodeid(@Param("carid")Long carid,@Param("rvid") Long rvid,@Param("nid")Long nid);
}