package com.evmtv.epg.mapper;

import com.evmtv.epg.entity.TReleaseVersion;
import com.evmtv.epg.entity.TReleaseVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TReleaseVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_release_version
     *
     * @mbggenerated Sun Nov 10 18:27:07 CST 2013
     */
    int countByExample(TReleaseVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_release_version
     *
     * @mbggenerated Sun Nov 10 18:27:07 CST 2013
     */
    int deleteByExample(TReleaseVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_release_version
     *
     * @mbggenerated Sun Nov 10 18:27:07 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_release_version
     *
     * @mbggenerated Sun Nov 10 18:27:07 CST 2013
     */
    int insert(TReleaseVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_release_version
     *
     * @mbggenerated Sun Nov 10 18:27:07 CST 2013
     */
    int insertSelective(TReleaseVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_release_version
     *
     * @mbggenerated Sun Nov 10 18:27:07 CST 2013
     */
    List<TReleaseVersion> selectByExample(TReleaseVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_release_version
     *
     * @mbggenerated Sun Nov 10 18:27:07 CST 2013
     */
    TReleaseVersion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_release_version
     *
     * @mbggenerated Sun Nov 10 18:27:07 CST 2013
     */
    int updateByExampleSelective(@Param("record") TReleaseVersion record, @Param("example") TReleaseVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_release_version
     *
     * @mbggenerated Sun Nov 10 18:27:07 CST 2013
     */
    int updateByExample(@Param("record") TReleaseVersion record, @Param("example") TReleaseVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_release_version
     *
     * @mbggenerated Sun Nov 10 18:27:07 CST 2013
     */
    int updateByPrimaryKeySelective(TReleaseVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_release_version
     *
     * @mbggenerated Sun Nov 10 18:27:07 CST 2013
     */
    int updateByPrimaryKey(TReleaseVersion record);
}