package com.evmtv.epg.mapper;

import com.evmtv.epg.entity.TResource;
import com.evmtv.epg.entity.TResourceExample;
import com.evmtv.epg.entity.TResourceWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    int countByExample(TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    int deleteByExample(TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    int insert(TResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    int insertSelective(TResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    List<TResourceWithBLOBs> selectByExampleWithBLOBs(TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    List<TResource> selectByExample(TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    TResourceWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    int updateByExampleSelective(@Param("record") TResourceWithBLOBs record, @Param("example") TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") TResourceWithBLOBs record, @Param("example") TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    int updateByExample(@Param("record") TResource record, @Param("example") TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    int updateByPrimaryKeySelective(TResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(TResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jul 12 17:34:02 CST 2013
     */
    int updateByPrimaryKey(TResource record);
    
    /**
     * 链表查询
     * @param r
     * @return
     */
    List<TResource> selectResource(@Param("r") TResource r);
    
    /**
     * 链表查询
     * @param resource
     * @return
     */
    int countResource(@Param("r") TResource r);
    /**
     * 广告编辑
     * @param example
     * @return
     */
    List<TResource> selectByResource(TResourceExample example);
}