package com.evmtv.epg.mapper;

import com.evmtv.epg.entity.TUser;
import com.evmtv.epg.entity.TUserExample;
import com.evmtv.epg.entity.TUserWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    int countByExample(TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    int deleteByExample(TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    int insert(TUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    int insertSelective(TUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    List<TUserWithBLOBs> selectByExampleWithBLOBs(TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    List<TUser> selectByExample(TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    TUserWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    int updateByExampleSelective(@Param("record") TUserWithBLOBs record, @Param("example") TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") TUserWithBLOBs record, @Param("example") TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    int updateByExample(@Param("record") TUser record, @Param("example") TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    int updateByPrimaryKeySelective(TUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(TUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jul 10 15:05:53 CST 2013
     */
    int updateByPrimaryKey(TUser record);
}