package com.evmtv.epg.mapper;

import com.evmtv.epg.entity.TVersion;
import com.evmtv.epg.entity.TVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated
     */
    int countByExample(TVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated
     */
    int deleteByExample(TVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated
     */
    int insert(TVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated
     */
    int insertSelective(TVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated
     */
    List<TVersion> selectByExample(TVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated
     */
    TVersion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TVersion record, @Param("example") TVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TVersion record, @Param("example") TVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TVersion record);
}