package com.evmtv.epg.entity;

import java.util.ArrayList;
import java.util.List;

import com.evmtv.epg.request.BaseRequest;

public class TMenuUsergroupExample extends BaseRequest{
    /**
	 * @field serialVersionUID
	 * @field_type long
	 */
	private static final long serialVersionUID = -4017043517836201531L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_menu_usergroup
     *
     * @mbggenerated Mon Jul 01 16:35:57 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_menu_usergroup
     *
     * @mbggenerated Mon Jul 01 16:35:57 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_menu_usergroup
     *
     * @mbggenerated Mon Jul 01 16:35:57 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_usergroup
     *
     * @mbggenerated Mon Jul 01 16:35:57 CST 2013
     */
    public TMenuUsergroupExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_usergroup
     *
     * @mbggenerated Mon Jul 01 16:35:57 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_usergroup
     *
     * @mbggenerated Mon Jul 01 16:35:57 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_usergroup
     *
     * @mbggenerated Mon Jul 01 16:35:57 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_usergroup
     *
     * @mbggenerated Mon Jul 01 16:35:57 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_usergroup
     *
     * @mbggenerated Mon Jul 01 16:35:57 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_usergroup
     *
     * @mbggenerated Mon Jul 01 16:35:57 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_usergroup
     *
     * @mbggenerated Mon Jul 01 16:35:57 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_usergroup
     *
     * @mbggenerated Mon Jul 01 16:35:57 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_usergroup
     *
     * @mbggenerated Mon Jul 01 16:35:57 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_usergroup
     *
     * @mbggenerated Mon Jul 01 16:35:57 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_menu_usergroup
     *
     * @mbggenerated Mon Jul 01 16:35:57 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFusergroupidIsNull() {
            addCriterion("FUserGroupId is null");
            return (Criteria) this;
        }

        public Criteria andFusergroupidIsNotNull() {
            addCriterion("FUserGroupId is not null");
            return (Criteria) this;
        }

        public Criteria andFusergroupidEqualTo(Long value) {
            addCriterion("FUserGroupId =", value, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidNotEqualTo(Long value) {
            addCriterion("FUserGroupId <>", value, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidGreaterThan(Long value) {
            addCriterion("FUserGroupId >", value, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidGreaterThanOrEqualTo(Long value) {
            addCriterion("FUserGroupId >=", value, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidLessThan(Long value) {
            addCriterion("FUserGroupId <", value, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidLessThanOrEqualTo(Long value) {
            addCriterion("FUserGroupId <=", value, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidIn(List<Long> values) {
            addCriterion("FUserGroupId in", values, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidNotIn(List<Long> values) {
            addCriterion("FUserGroupId not in", values, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidBetween(Long value1, Long value2) {
            addCriterion("FUserGroupId between", value1, value2, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFusergroupidNotBetween(Long value1, Long value2) {
            addCriterion("FUserGroupId not between", value1, value2, "fusergroupid");
            return (Criteria) this;
        }

        public Criteria andFmenuidIsNull() {
            addCriterion("FMenuId is null");
            return (Criteria) this;
        }

        public Criteria andFmenuidIsNotNull() {
            addCriterion("FMenuId is not null");
            return (Criteria) this;
        }

        public Criteria andFmenuidEqualTo(Long value) {
            addCriterion("FMenuId =", value, "fmenuid");
            return (Criteria) this;
        }

        public Criteria andFmenuidNotEqualTo(Long value) {
            addCriterion("FMenuId <>", value, "fmenuid");
            return (Criteria) this;
        }

        public Criteria andFmenuidGreaterThan(Long value) {
            addCriterion("FMenuId >", value, "fmenuid");
            return (Criteria) this;
        }

        public Criteria andFmenuidGreaterThanOrEqualTo(Long value) {
            addCriterion("FMenuId >=", value, "fmenuid");
            return (Criteria) this;
        }

        public Criteria andFmenuidLessThan(Long value) {
            addCriterion("FMenuId <", value, "fmenuid");
            return (Criteria) this;
        }

        public Criteria andFmenuidLessThanOrEqualTo(Long value) {
            addCriterion("FMenuId <=", value, "fmenuid");
            return (Criteria) this;
        }

        public Criteria andFmenuidIn(List<Long> values) {
            addCriterion("FMenuId in", values, "fmenuid");
            return (Criteria) this;
        }

        public Criteria andFmenuidNotIn(List<Long> values) {
            addCriterion("FMenuId not in", values, "fmenuid");
            return (Criteria) this;
        }

        public Criteria andFmenuidBetween(Long value1, Long value2) {
            addCriterion("FMenuId between", value1, value2, "fmenuid");
            return (Criteria) this;
        }

        public Criteria andFmenuidNotBetween(Long value1, Long value2) {
            addCriterion("FMenuId not between", value1, value2, "fmenuid");
            return (Criteria) this;
        }

        public Criteria andFreadonlyIsNull() {
            addCriterion("FReadonly is null");
            return (Criteria) this;
        }

        public Criteria andFreadonlyIsNotNull() {
            addCriterion("FReadonly is not null");
            return (Criteria) this;
        }

        public Criteria andFreadonlyEqualTo(String value) {
            addCriterion("FReadonly =", value, "freadonly");
            return (Criteria) this;
        }

        public Criteria andFreadonlyNotEqualTo(String value) {
            addCriterion("FReadonly <>", value, "freadonly");
            return (Criteria) this;
        }

        public Criteria andFreadonlyGreaterThan(String value) {
            addCriterion("FReadonly >", value, "freadonly");
            return (Criteria) this;
        }

        public Criteria andFreadonlyGreaterThanOrEqualTo(String value) {
            addCriterion("FReadonly >=", value, "freadonly");
            return (Criteria) this;
        }

        public Criteria andFreadonlyLessThan(String value) {
            addCriterion("FReadonly <", value, "freadonly");
            return (Criteria) this;
        }

        public Criteria andFreadonlyLessThanOrEqualTo(String value) {
            addCriterion("FReadonly <=", value, "freadonly");
            return (Criteria) this;
        }

        public Criteria andFreadonlyLike(String value) {
            addCriterion("FReadonly like", value, "freadonly");
            return (Criteria) this;
        }

        public Criteria andFreadonlyNotLike(String value) {
            addCriterion("FReadonly not like", value, "freadonly");
            return (Criteria) this;
        }

        public Criteria andFreadonlyIn(List<String> values) {
            addCriterion("FReadonly in", values, "freadonly");
            return (Criteria) this;
        }

        public Criteria andFreadonlyNotIn(List<String> values) {
            addCriterion("FReadonly not in", values, "freadonly");
            return (Criteria) this;
        }

        public Criteria andFreadonlyBetween(String value1, String value2) {
            addCriterion("FReadonly between", value1, value2, "freadonly");
            return (Criteria) this;
        }

        public Criteria andFreadonlyNotBetween(String value1, String value2) {
            addCriterion("FReadonly not between", value1, value2, "freadonly");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_menu_usergroup
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 01 16:35:57 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_menu_usergroup
     *
     * @mbggenerated Mon Jul 01 16:35:57 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}