package com.evmtv.epg.entity;

import java.util.ArrayList;
import java.util.List;

import com.evmtv.epg.request.BaseRequest;

public class TContractExample extends BaseRequest{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4958462743669020432L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public TContractExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFguidIsNull() {
            addCriterion("FGUID is null");
            return (Criteria) this;
        }

        public Criteria andFguidIsNotNull() {
            addCriterion("FGUID is not null");
            return (Criteria) this;
        }

        public Criteria andFguidEqualTo(String value) {
            addCriterion("FGUID =", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidNotEqualTo(String value) {
            addCriterion("FGUID <>", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidGreaterThan(String value) {
            addCriterion("FGUID >", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidGreaterThanOrEqualTo(String value) {
            addCriterion("FGUID >=", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidLessThan(String value) {
            addCriterion("FGUID <", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidLessThanOrEqualTo(String value) {
            addCriterion("FGUID <=", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidLike(String value) {
            addCriterion("FGUID like", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidNotLike(String value) {
            addCriterion("FGUID not like", value, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidIn(List<String> values) {
            addCriterion("FGUID in", values, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidNotIn(List<String> values) {
            addCriterion("FGUID not in", values, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidBetween(String value1, String value2) {
            addCriterion("FGUID between", value1, value2, "fguid");
            return (Criteria) this;
        }

        public Criteria andFguidNotBetween(String value1, String value2) {
            addCriterion("FGUID not between", value1, value2, "fguid");
            return (Criteria) this;
        }

        public Criteria andFadvnameIsNull() {
            addCriterion("FAdvName is null");
            return (Criteria) this;
        }

        public Criteria andFadvnameIsNotNull() {
            addCriterion("FAdvName is not null");
            return (Criteria) this;
        }

        public Criteria andFadvnameEqualTo(String value) {
            addCriterion("FAdvName =", value, "fadvname");
            return (Criteria) this;
        }

        public Criteria andFadvnameNotEqualTo(String value) {
            addCriterion("FAdvName <>", value, "fadvname");
            return (Criteria) this;
        }

        public Criteria andFadvnameGreaterThan(String value) {
            addCriterion("FAdvName >", value, "fadvname");
            return (Criteria) this;
        }

        public Criteria andFadvnameGreaterThanOrEqualTo(String value) {
            addCriterion("FAdvName >=", value, "fadvname");
            return (Criteria) this;
        }

        public Criteria andFadvnameLessThan(String value) {
            addCriterion("FAdvName <", value, "fadvname");
            return (Criteria) this;
        }

        public Criteria andFadvnameLessThanOrEqualTo(String value) {
            addCriterion("FAdvName <=", value, "fadvname");
            return (Criteria) this;
        }

        public Criteria andFadvnameLike(String value) {
            addCriterion("FAdvName like", value, "fadvname");
            return (Criteria) this;
        }

        public Criteria andFadvnameNotLike(String value) {
            addCriterion("FAdvName not like", value, "fadvname");
            return (Criteria) this;
        }

        public Criteria andFadvnameIn(List<String> values) {
            addCriterion("FAdvName in", values, "fadvname");
            return (Criteria) this;
        }

        public Criteria andFadvnameNotIn(List<String> values) {
            addCriterion("FAdvName not in", values, "fadvname");
            return (Criteria) this;
        }

        public Criteria andFadvnameBetween(String value1, String value2) {
            addCriterion("FAdvName between", value1, value2, "fadvname");
            return (Criteria) this;
        }

        public Criteria andFadvnameNotBetween(String value1, String value2) {
            addCriterion("FAdvName not between", value1, value2, "fadvname");
            return (Criteria) this;
        }

        public Criteria andFadvlocidIsNull() {
            addCriterion("FAdvLocId is null");
            return (Criteria) this;
        }

        public Criteria andFadvlocidIsNotNull() {
            addCriterion("FAdvLocId is not null");
            return (Criteria) this;
        }

        public Criteria andFadvlocidEqualTo(Integer value) {
            addCriterion("FAdvLocId =", value, "fadvlocid");
            return (Criteria) this;
        }

        public Criteria andFadvlocidNotEqualTo(Integer value) {
            addCriterion("FAdvLocId <>", value, "fadvlocid");
            return (Criteria) this;
        }

        public Criteria andFadvlocidGreaterThan(Integer value) {
            addCriterion("FAdvLocId >", value, "fadvlocid");
            return (Criteria) this;
        }

        public Criteria andFadvlocidGreaterThanOrEqualTo(Integer value) {
            addCriterion("FAdvLocId >=", value, "fadvlocid");
            return (Criteria) this;
        }

        public Criteria andFadvlocidLessThan(Integer value) {
            addCriterion("FAdvLocId <", value, "fadvlocid");
            return (Criteria) this;
        }

        public Criteria andFadvlocidLessThanOrEqualTo(Integer value) {
            addCriterion("FAdvLocId <=", value, "fadvlocid");
            return (Criteria) this;
        }

        public Criteria andFadvlocidIn(List<Integer> values) {
            addCriterion("FAdvLocId in", values, "fadvlocid");
            return (Criteria) this;
        }

        public Criteria andFadvlocidNotIn(List<Integer> values) {
            addCriterion("FAdvLocId not in", values, "fadvlocid");
            return (Criteria) this;
        }

        public Criteria andFadvlocidBetween(Integer value1, Integer value2) {
            addCriterion("FAdvLocId between", value1, value2, "fadvlocid");
            return (Criteria) this;
        }

        public Criteria andFadvlocidNotBetween(Integer value1, Integer value2) {
            addCriterion("FAdvLocId not between", value1, value2, "fadvlocid");
            return (Criteria) this;
        }

        public Criteria andFadvlevelIsNull() {
            addCriterion("FAdvLevel is null");
            return (Criteria) this;
        }

        public Criteria andFadvlevelIsNotNull() {
            addCriterion("FAdvLevel is not null");
            return (Criteria) this;
        }

        public Criteria andFadvlevelEqualTo(String value) {
            addCriterion("FAdvLevel =", value, "fadvlevel");
            return (Criteria) this;
        }

        public Criteria andFadvlevelNotEqualTo(String value) {
            addCriterion("FAdvLevel <>", value, "fadvlevel");
            return (Criteria) this;
        }

        public Criteria andFadvlevelGreaterThan(String value) {
            addCriterion("FAdvLevel >", value, "fadvlevel");
            return (Criteria) this;
        }

        public Criteria andFadvlevelGreaterThanOrEqualTo(String value) {
            addCriterion("FAdvLevel >=", value, "fadvlevel");
            return (Criteria) this;
        }

        public Criteria andFadvlevelLessThan(String value) {
            addCriterion("FAdvLevel <", value, "fadvlevel");
            return (Criteria) this;
        }

        public Criteria andFadvlevelLessThanOrEqualTo(String value) {
            addCriterion("FAdvLevel <=", value, "fadvlevel");
            return (Criteria) this;
        }

        public Criteria andFadvlevelLike(String value) {
            addCriterion("FAdvLevel like", value, "fadvlevel");
            return (Criteria) this;
        }

        public Criteria andFadvlevelNotLike(String value) {
            addCriterion("FAdvLevel not like", value, "fadvlevel");
            return (Criteria) this;
        }

        public Criteria andFadvlevelIn(List<String> values) {
            addCriterion("FAdvLevel in", values, "fadvlevel");
            return (Criteria) this;
        }

        public Criteria andFadvlevelNotIn(List<String> values) {
            addCriterion("FAdvLevel not in", values, "fadvlevel");
            return (Criteria) this;
        }

        public Criteria andFadvlevelBetween(String value1, String value2) {
            addCriterion("FAdvLevel between", value1, value2, "fadvlevel");
            return (Criteria) this;
        }

        public Criteria andFadvlevelNotBetween(String value1, String value2) {
            addCriterion("FAdvLevel not between", value1, value2, "fadvlevel");
            return (Criteria) this;
        }

        public Criteria andFdefinitionIsNull() {
            addCriterion("FDefinition is null");
            return (Criteria) this;
        }

        public Criteria andFdefinitionIsNotNull() {
            addCriterion("FDefinition is not null");
            return (Criteria) this;
        }

        public Criteria andFdefinitionEqualTo(String value) {
            addCriterion("FDefinition =", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionNotEqualTo(String value) {
            addCriterion("FDefinition <>", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionGreaterThan(String value) {
            addCriterion("FDefinition >", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionGreaterThanOrEqualTo(String value) {
            addCriterion("FDefinition >=", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionLessThan(String value) {
            addCriterion("FDefinition <", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionLessThanOrEqualTo(String value) {
            addCriterion("FDefinition <=", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionLike(String value) {
            addCriterion("FDefinition like", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionNotLike(String value) {
            addCriterion("FDefinition not like", value, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionIn(List<String> values) {
            addCriterion("FDefinition in", values, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionNotIn(List<String> values) {
            addCriterion("FDefinition not in", values, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionBetween(String value1, String value2) {
            addCriterion("FDefinition between", value1, value2, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFdefinitionNotBetween(String value1, String value2) {
            addCriterion("FDefinition not between", value1, value2, "fdefinition");
            return (Criteria) this;
        }

        public Criteria andFagentIsNull() {
            addCriterion("FAgent is null");
            return (Criteria) this;
        }

        public Criteria andFagentIsNotNull() {
            addCriterion("FAgent is not null");
            return (Criteria) this;
        }

        public Criteria andFagentEqualTo(String value) {
            addCriterion("FAgent =", value, "fagent");
            return (Criteria) this;
        }

        public Criteria andFagentNotEqualTo(String value) {
            addCriterion("FAgent <>", value, "fagent");
            return (Criteria) this;
        }

        public Criteria andFagentGreaterThan(String value) {
            addCriterion("FAgent >", value, "fagent");
            return (Criteria) this;
        }

        public Criteria andFagentGreaterThanOrEqualTo(String value) {
            addCriterion("FAgent >=", value, "fagent");
            return (Criteria) this;
        }

        public Criteria andFagentLessThan(String value) {
            addCriterion("FAgent <", value, "fagent");
            return (Criteria) this;
        }

        public Criteria andFagentLessThanOrEqualTo(String value) {
            addCriterion("FAgent <=", value, "fagent");
            return (Criteria) this;
        }

        public Criteria andFagentLike(String value) {
            addCriterion("FAgent like", value, "fagent");
            return (Criteria) this;
        }

        public Criteria andFagentNotLike(String value) {
            addCriterion("FAgent not like", value, "fagent");
            return (Criteria) this;
        }

        public Criteria andFagentIn(List<String> values) {
            addCriterion("FAgent in", values, "fagent");
            return (Criteria) this;
        }

        public Criteria andFagentNotIn(List<String> values) {
            addCriterion("FAgent not in", values, "fagent");
            return (Criteria) this;
        }

        public Criteria andFagentBetween(String value1, String value2) {
            addCriterion("FAgent between", value1, value2, "fagent");
            return (Criteria) this;
        }

        public Criteria andFagentNotBetween(String value1, String value2) {
            addCriterion("FAgent not between", value1, value2, "fagent");
            return (Criteria) this;
        }

        public Criteria andFbranchidIsNull() {
            addCriterion("FBranchId is null");
            return (Criteria) this;
        }

        public Criteria andFbranchidIsNotNull() {
            addCriterion("FBranchId is not null");
            return (Criteria) this;
        }

        public Criteria andFbranchidEqualTo(Long value) {
            addCriterion("FBranchId =", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidNotEqualTo(Long value) {
            addCriterion("FBranchId <>", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidGreaterThan(Long value) {
            addCriterion("FBranchId >", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidGreaterThanOrEqualTo(Long value) {
            addCriterion("FBranchId >=", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidLessThan(Long value) {
            addCriterion("FBranchId <", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidLessThanOrEqualTo(Long value) {
            addCriterion("FBranchId <=", value, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidIn(List<Long> values) {
            addCriterion("FBranchId in", values, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidNotIn(List<Long> values) {
            addCriterion("FBranchId not in", values, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidBetween(Long value1, Long value2) {
            addCriterion("FBranchId between", value1, value2, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFbranchidNotBetween(Long value1, Long value2) {
            addCriterion("FBranchId not between", value1, value2, "fbranchid");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIsNull() {
            addCriterion("FCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIsNotNull() {
            addCriterion("FCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeEqualTo(String value) {
            addCriterion("FCreateTime =", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotEqualTo(String value) {
            addCriterion("FCreateTime <>", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeGreaterThan(String value) {
            addCriterion("FCreateTime >", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("FCreateTime >=", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLessThan(String value) {
            addCriterion("FCreateTime <", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLessThanOrEqualTo(String value) {
            addCriterion("FCreateTime <=", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLike(String value) {
            addCriterion("FCreateTime like", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotLike(String value) {
            addCriterion("FCreateTime not like", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIn(List<String> values) {
            addCriterion("FCreateTime in", values, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotIn(List<String> values) {
            addCriterion("FCreateTime not in", values, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeBetween(String value1, String value2) {
            addCriterion("FCreateTime between", value1, value2, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotBetween(String value1, String value2) {
            addCriterion("FCreateTime not between", value1, value2, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIsNull() {
            addCriterion("FCreateUserId is null");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIsNotNull() {
            addCriterion("FCreateUserId is not null");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridEqualTo(Long value) {
            addCriterion("FCreateUserId =", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotEqualTo(Long value) {
            addCriterion("FCreateUserId <>", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridGreaterThan(Long value) {
            addCriterion("FCreateUserId >", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridGreaterThanOrEqualTo(Long value) {
            addCriterion("FCreateUserId >=", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridLessThan(Long value) {
            addCriterion("FCreateUserId <", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridLessThanOrEqualTo(Long value) {
            addCriterion("FCreateUserId <=", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIn(List<Long> values) {
            addCriterion("FCreateUserId in", values, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotIn(List<Long> values) {
            addCriterion("FCreateUserId not in", values, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridBetween(Long value1, Long value2) {
            addCriterion("FCreateUserId between", value1, value2, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotBetween(Long value1, Long value2) {
            addCriterion("FCreateUserId not between", value1, value2, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIsNull() {
            addCriterion("FUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIsNotNull() {
            addCriterion("FUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeEqualTo(String value) {
            addCriterion("FUpdateTime =", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotEqualTo(String value) {
            addCriterion("FUpdateTime <>", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeGreaterThan(String value) {
            addCriterion("FUpdateTime >", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("FUpdateTime >=", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLessThan(String value) {
            addCriterion("FUpdateTime <", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLessThanOrEqualTo(String value) {
            addCriterion("FUpdateTime <=", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLike(String value) {
            addCriterion("FUpdateTime like", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotLike(String value) {
            addCriterion("FUpdateTime not like", value, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIn(List<String> values) {
            addCriterion("FUpdateTime in", values, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotIn(List<String> values) {
            addCriterion("FUpdateTime not in", values, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeBetween(String value1, String value2) {
            addCriterion("FUpdateTime between", value1, value2, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotBetween(String value1, String value2) {
            addCriterion("FUpdateTime not between", value1, value2, "fupdatetime");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridIsNull() {
            addCriterion("FUpdateUserId is null");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridIsNotNull() {
            addCriterion("FUpdateUserId is not null");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridEqualTo(Long value) {
            addCriterion("FUpdateUserId =", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridNotEqualTo(Long value) {
            addCriterion("FUpdateUserId <>", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridGreaterThan(Long value) {
            addCriterion("FUpdateUserId >", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridGreaterThanOrEqualTo(Long value) {
            addCriterion("FUpdateUserId >=", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridLessThan(Long value) {
            addCriterion("FUpdateUserId <", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridLessThanOrEqualTo(Long value) {
            addCriterion("FUpdateUserId <=", value, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridIn(List<Long> values) {
            addCriterion("FUpdateUserId in", values, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridNotIn(List<Long> values) {
            addCriterion("FUpdateUserId not in", values, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridBetween(Long value1, Long value2) {
            addCriterion("FUpdateUserId between", value1, value2, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFupdateuseridNotBetween(Long value1, Long value2) {
            addCriterion("FUpdateUserId not between", value1, value2, "fupdateuserid");
            return (Criteria) this;
        }

        public Criteria andFcontactnameIsNull() {
            addCriterion("FContactName is null");
            return (Criteria) this;
        }

        public Criteria andFcontactnameIsNotNull() {
            addCriterion("FContactName is not null");
            return (Criteria) this;
        }

        public Criteria andFcontactnameEqualTo(String value) {
            addCriterion("FContactName =", value, "fcontactname");
            return (Criteria) this;
        }

        public Criteria andFcontactnameNotEqualTo(String value) {
            addCriterion("FContactName <>", value, "fcontactname");
            return (Criteria) this;
        }

        public Criteria andFcontactnameGreaterThan(String value) {
            addCriterion("FContactName >", value, "fcontactname");
            return (Criteria) this;
        }

        public Criteria andFcontactnameGreaterThanOrEqualTo(String value) {
            addCriterion("FContactName >=", value, "fcontactname");
            return (Criteria) this;
        }

        public Criteria andFcontactnameLessThan(String value) {
            addCriterion("FContactName <", value, "fcontactname");
            return (Criteria) this;
        }

        public Criteria andFcontactnameLessThanOrEqualTo(String value) {
            addCriterion("FContactName <=", value, "fcontactname");
            return (Criteria) this;
        }

        public Criteria andFcontactnameLike(String value) {
            addCriterion("FContactName like", value, "fcontactname");
            return (Criteria) this;
        }

        public Criteria andFcontactnameNotLike(String value) {
            addCriterion("FContactName not like", value, "fcontactname");
            return (Criteria) this;
        }

        public Criteria andFcontactnameIn(List<String> values) {
            addCriterion("FContactName in", values, "fcontactname");
            return (Criteria) this;
        }

        public Criteria andFcontactnameNotIn(List<String> values) {
            addCriterion("FContactName not in", values, "fcontactname");
            return (Criteria) this;
        }

        public Criteria andFcontactnameBetween(String value1, String value2) {
            addCriterion("FContactName between", value1, value2, "fcontactname");
            return (Criteria) this;
        }

        public Criteria andFcontactnameNotBetween(String value1, String value2) {
            addCriterion("FContactName not between", value1, value2, "fcontactname");
            return (Criteria) this;
        }

        public Criteria andFcontacttelIsNull() {
            addCriterion("FContactTel is null");
            return (Criteria) this;
        }

        public Criteria andFcontacttelIsNotNull() {
            addCriterion("FContactTel is not null");
            return (Criteria) this;
        }

        public Criteria andFcontacttelEqualTo(String value) {
            addCriterion("FContactTel =", value, "fcontacttel");
            return (Criteria) this;
        }

        public Criteria andFcontacttelNotEqualTo(String value) {
            addCriterion("FContactTel <>", value, "fcontacttel");
            return (Criteria) this;
        }

        public Criteria andFcontacttelGreaterThan(String value) {
            addCriterion("FContactTel >", value, "fcontacttel");
            return (Criteria) this;
        }

        public Criteria andFcontacttelGreaterThanOrEqualTo(String value) {
            addCriterion("FContactTel >=", value, "fcontacttel");
            return (Criteria) this;
        }

        public Criteria andFcontacttelLessThan(String value) {
            addCriterion("FContactTel <", value, "fcontacttel");
            return (Criteria) this;
        }

        public Criteria andFcontacttelLessThanOrEqualTo(String value) {
            addCriterion("FContactTel <=", value, "fcontacttel");
            return (Criteria) this;
        }

        public Criteria andFcontacttelLike(String value) {
            addCriterion("FContactTel like", value, "fcontacttel");
            return (Criteria) this;
        }

        public Criteria andFcontacttelNotLike(String value) {
            addCriterion("FContactTel not like", value, "fcontacttel");
            return (Criteria) this;
        }

        public Criteria andFcontacttelIn(List<String> values) {
            addCriterion("FContactTel in", values, "fcontacttel");
            return (Criteria) this;
        }

        public Criteria andFcontacttelNotIn(List<String> values) {
            addCriterion("FContactTel not in", values, "fcontacttel");
            return (Criteria) this;
        }

        public Criteria andFcontacttelBetween(String value1, String value2) {
            addCriterion("FContactTel between", value1, value2, "fcontacttel");
            return (Criteria) this;
        }

        public Criteria andFcontacttelNotBetween(String value1, String value2) {
            addCriterion("FContactTel not between", value1, value2, "fcontacttel");
            return (Criteria) this;
        }

        public Criteria andFstarttimeIsNull() {
            addCriterion("FStartTime is null");
            return (Criteria) this;
        }

        public Criteria andFstarttimeIsNotNull() {
            addCriterion("FStartTime is not null");
            return (Criteria) this;
        }

        public Criteria andFstarttimeEqualTo(String value) {
            addCriterion("FStartTime =", value, "fstarttime");
            return (Criteria) this;
        }

        public Criteria andFstarttimeNotEqualTo(String value) {
            addCriterion("FStartTime <>", value, "fstarttime");
            return (Criteria) this;
        }

        public Criteria andFstarttimeGreaterThan(String value) {
            addCriterion("FStartTime >", value, "fstarttime");
            return (Criteria) this;
        }

        public Criteria andFstarttimeGreaterThanOrEqualTo(String value) {
            addCriterion("FStartTime >=", value, "fstarttime");
            return (Criteria) this;
        }

        public Criteria andFstarttimeLessThan(String value) {
            addCriterion("FStartTime <", value, "fstarttime");
            return (Criteria) this;
        }

        public Criteria andFstarttimeLessThanOrEqualTo(String value) {
            addCriterion("FStartTime <=", value, "fstarttime");
            return (Criteria) this;
        }

        public Criteria andFstarttimeLike(String value) {
            addCriterion("FStartTime like", value, "fstarttime");
            return (Criteria) this;
        }

        public Criteria andFstarttimeNotLike(String value) {
            addCriterion("FStartTime not like", value, "fstarttime");
            return (Criteria) this;
        }

        public Criteria andFstarttimeIn(List<String> values) {
            addCriterion("FStartTime in", values, "fstarttime");
            return (Criteria) this;
        }

        public Criteria andFstarttimeNotIn(List<String> values) {
            addCriterion("FStartTime not in", values, "fstarttime");
            return (Criteria) this;
        }

        public Criteria andFstarttimeBetween(String value1, String value2) {
            addCriterion("FStartTime between", value1, value2, "fstarttime");
            return (Criteria) this;
        }

        public Criteria andFstarttimeNotBetween(String value1, String value2) {
            addCriterion("FStartTime not between", value1, value2, "fstarttime");
            return (Criteria) this;
        }

        public Criteria andFendtimeIsNull() {
            addCriterion("FEndTime is null");
            return (Criteria) this;
        }

        public Criteria andFendtimeIsNotNull() {
            addCriterion("FEndTime is not null");
            return (Criteria) this;
        }

        public Criteria andFendtimeEqualTo(String value) {
            addCriterion("FEndTime =", value, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeNotEqualTo(String value) {
            addCriterion("FEndTime <>", value, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeGreaterThan(String value) {
            addCriterion("FEndTime >", value, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeGreaterThanOrEqualTo(String value) {
            addCriterion("FEndTime >=", value, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeLessThan(String value) {
            addCriterion("FEndTime <", value, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeLessThanOrEqualTo(String value) {
            addCriterion("FEndTime <=", value, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeLike(String value) {
            addCriterion("FEndTime like", value, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeNotLike(String value) {
            addCriterion("FEndTime not like", value, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeIn(List<String> values) {
            addCriterion("FEndTime in", values, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeNotIn(List<String> values) {
            addCriterion("FEndTime not in", values, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeBetween(String value1, String value2) {
            addCriterion("FEndTime between", value1, value2, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeNotBetween(String value1, String value2) {
            addCriterion("FEndTime not between", value1, value2, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFpriceIsNull() {
            addCriterion("FPrice is null");
            return (Criteria) this;
        }

        public Criteria andFpriceIsNotNull() {
            addCriterion("FPrice is not null");
            return (Criteria) this;
        }

        public Criteria andFpriceEqualTo(String value) {
            addCriterion("FPrice =", value, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceNotEqualTo(String value) {
            addCriterion("FPrice <>", value, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceGreaterThan(String value) {
            addCriterion("FPrice >", value, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceGreaterThanOrEqualTo(String value) {
            addCriterion("FPrice >=", value, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceLessThan(String value) {
            addCriterion("FPrice <", value, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceLessThanOrEqualTo(String value) {
            addCriterion("FPrice <=", value, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceLike(String value) {
            addCriterion("FPrice like", value, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceNotLike(String value) {
            addCriterion("FPrice not like", value, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceIn(List<String> values) {
            addCriterion("FPrice in", values, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceNotIn(List<String> values) {
            addCriterion("FPrice not in", values, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceBetween(String value1, String value2) {
            addCriterion("FPrice between", value1, value2, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceNotBetween(String value1, String value2) {
            addCriterion("FPrice not between", value1, value2, "fprice");
            return (Criteria) this;
        }

        public Criteria andFdiscountIsNull() {
            addCriterion("FDiscount is null");
            return (Criteria) this;
        }

        public Criteria andFdiscountIsNotNull() {
            addCriterion("FDiscount is not null");
            return (Criteria) this;
        }

        public Criteria andFdiscountEqualTo(String value) {
            addCriterion("FDiscount =", value, "fdiscount");
            return (Criteria) this;
        }

        public Criteria andFdiscountNotEqualTo(String value) {
            addCriterion("FDiscount <>", value, "fdiscount");
            return (Criteria) this;
        }

        public Criteria andFdiscountGreaterThan(String value) {
            addCriterion("FDiscount >", value, "fdiscount");
            return (Criteria) this;
        }

        public Criteria andFdiscountGreaterThanOrEqualTo(String value) {
            addCriterion("FDiscount >=", value, "fdiscount");
            return (Criteria) this;
        }

        public Criteria andFdiscountLessThan(String value) {
            addCriterion("FDiscount <", value, "fdiscount");
            return (Criteria) this;
        }

        public Criteria andFdiscountLessThanOrEqualTo(String value) {
            addCriterion("FDiscount <=", value, "fdiscount");
            return (Criteria) this;
        }

        public Criteria andFdiscountLike(String value) {
            addCriterion("FDiscount like", value, "fdiscount");
            return (Criteria) this;
        }

        public Criteria andFdiscountNotLike(String value) {
            addCriterion("FDiscount not like", value, "fdiscount");
            return (Criteria) this;
        }

        public Criteria andFdiscountIn(List<String> values) {
            addCriterion("FDiscount in", values, "fdiscount");
            return (Criteria) this;
        }

        public Criteria andFdiscountNotIn(List<String> values) {
            addCriterion("FDiscount not in", values, "fdiscount");
            return (Criteria) this;
        }

        public Criteria andFdiscountBetween(String value1, String value2) {
            addCriterion("FDiscount between", value1, value2, "fdiscount");
            return (Criteria) this;
        }

        public Criteria andFdiscountNotBetween(String value1, String value2) {
            addCriterion("FDiscount not between", value1, value2, "fdiscount");
            return (Criteria) this;
        }

        public Criteria andFpaywayIsNull() {
            addCriterion("FPayWay is null");
            return (Criteria) this;
        }

        public Criteria andFpaywayIsNotNull() {
            addCriterion("FPayWay is not null");
            return (Criteria) this;
        }

        public Criteria andFpaywayEqualTo(String value) {
            addCriterion("FPayWay =", value, "fpayway");
            return (Criteria) this;
        }

        public Criteria andFpaywayNotEqualTo(String value) {
            addCriterion("FPayWay <>", value, "fpayway");
            return (Criteria) this;
        }

        public Criteria andFpaywayGreaterThan(String value) {
            addCriterion("FPayWay >", value, "fpayway");
            return (Criteria) this;
        }

        public Criteria andFpaywayGreaterThanOrEqualTo(String value) {
            addCriterion("FPayWay >=", value, "fpayway");
            return (Criteria) this;
        }

        public Criteria andFpaywayLessThan(String value) {
            addCriterion("FPayWay <", value, "fpayway");
            return (Criteria) this;
        }

        public Criteria andFpaywayLessThanOrEqualTo(String value) {
            addCriterion("FPayWay <=", value, "fpayway");
            return (Criteria) this;
        }

        public Criteria andFpaywayLike(String value) {
            addCriterion("FPayWay like", value, "fpayway");
            return (Criteria) this;
        }

        public Criteria andFpaywayNotLike(String value) {
            addCriterion("FPayWay not like", value, "fpayway");
            return (Criteria) this;
        }

        public Criteria andFpaywayIn(List<String> values) {
            addCriterion("FPayWay in", values, "fpayway");
            return (Criteria) this;
        }

        public Criteria andFpaywayNotIn(List<String> values) {
            addCriterion("FPayWay not in", values, "fpayway");
            return (Criteria) this;
        }

        public Criteria andFpaywayBetween(String value1, String value2) {
            addCriterion("FPayWay between", value1, value2, "fpayway");
            return (Criteria) this;
        }

        public Criteria andFpaywayNotBetween(String value1, String value2) {
            addCriterion("FPayWay not between", value1, value2, "fpayway");
            return (Criteria) this;
        }

        public Criteria andFdeletedIsNull() {
            addCriterion("FDeleted is null");
            return (Criteria) this;
        }

        public Criteria andFdeletedIsNotNull() {
            addCriterion("FDeleted is not null");
            return (Criteria) this;
        }

        public Criteria andFdeletedEqualTo(String value) {
            addCriterion("FDeleted =", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedNotEqualTo(String value) {
            addCriterion("FDeleted <>", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedGreaterThan(String value) {
            addCriterion("FDeleted >", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedGreaterThanOrEqualTo(String value) {
            addCriterion("FDeleted >=", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedLessThan(String value) {
            addCriterion("FDeleted <", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedLessThanOrEqualTo(String value) {
            addCriterion("FDeleted <=", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedLike(String value) {
            addCriterion("FDeleted like", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedNotLike(String value) {
            addCriterion("FDeleted not like", value, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedIn(List<String> values) {
            addCriterion("FDeleted in", values, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedNotIn(List<String> values) {
            addCriterion("FDeleted not in", values, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedBetween(String value1, String value2) {
            addCriterion("FDeleted between", value1, value2, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFdeletedNotBetween(String value1, String value2) {
            addCriterion("FDeleted not between", value1, value2, "fdeleted");
            return (Criteria) this;
        }

        public Criteria andFcheckedIsNull() {
            addCriterion("FChecked is null");
            return (Criteria) this;
        }

        public Criteria andFcheckedIsNotNull() {
            addCriterion("FChecked is not null");
            return (Criteria) this;
        }

        public Criteria andFcheckedEqualTo(String value) {
            addCriterion("FChecked =", value, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedNotEqualTo(String value) {
            addCriterion("FChecked <>", value, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedGreaterThan(String value) {
            addCriterion("FChecked >", value, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedGreaterThanOrEqualTo(String value) {
            addCriterion("FChecked >=", value, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedLessThan(String value) {
            addCriterion("FChecked <", value, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedLessThanOrEqualTo(String value) {
            addCriterion("FChecked <=", value, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedLike(String value) {
            addCriterion("FChecked like", value, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedNotLike(String value) {
            addCriterion("FChecked not like", value, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedIn(List<String> values) {
            addCriterion("FChecked in", values, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedNotIn(List<String> values) {
            addCriterion("FChecked not in", values, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedBetween(String value1, String value2) {
            addCriterion("FChecked between", value1, value2, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFcheckedNotBetween(String value1, String value2) {
            addCriterion("FChecked not between", value1, value2, "fchecked");
            return (Criteria) this;
        }

        public Criteria andFfreezedIsNull() {
            addCriterion("FFreezed is null");
            return (Criteria) this;
        }

        public Criteria andFfreezedIsNotNull() {
            addCriterion("FFreezed is not null");
            return (Criteria) this;
        }

        public Criteria andFfreezedEqualTo(String value) {
            addCriterion("FFreezed =", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedNotEqualTo(String value) {
            addCriterion("FFreezed <>", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedGreaterThan(String value) {
            addCriterion("FFreezed >", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedGreaterThanOrEqualTo(String value) {
            addCriterion("FFreezed >=", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedLessThan(String value) {
            addCriterion("FFreezed <", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedLessThanOrEqualTo(String value) {
            addCriterion("FFreezed <=", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedLike(String value) {
            addCriterion("FFreezed like", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedNotLike(String value) {
            addCriterion("FFreezed not like", value, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedIn(List<String> values) {
            addCriterion("FFreezed in", values, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedNotIn(List<String> values) {
            addCriterion("FFreezed not in", values, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedBetween(String value1, String value2) {
            addCriterion("FFreezed between", value1, value2, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFfreezedNotBetween(String value1, String value2) {
            addCriterion("FFreezed not between", value1, value2, "ffreezed");
            return (Criteria) this;
        }

        public Criteria andFtitleIsNull() {
            addCriterion("FTitle is null");
            return (Criteria) this;
        }

        public Criteria andFtitleIsNotNull() {
            addCriterion("FTitle is not null");
            return (Criteria) this;
        }

        public Criteria andFtitleEqualTo(String value) {
            addCriterion("FTitle =", value, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleNotEqualTo(String value) {
            addCriterion("FTitle <>", value, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleGreaterThan(String value) {
            addCriterion("FTitle >", value, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleGreaterThanOrEqualTo(String value) {
            addCriterion("FTitle >=", value, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleLessThan(String value) {
            addCriterion("FTitle <", value, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleLessThanOrEqualTo(String value) {
            addCriterion("FTitle <=", value, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleLike(String value) {
            addCriterion("FTitle like", value, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleNotLike(String value) {
            addCriterion("FTitle not like", value, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleIn(List<String> values) {
            addCriterion("FTitle in", values, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleNotIn(List<String> values) {
            addCriterion("FTitle not in", values, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleBetween(String value1, String value2) {
            addCriterion("FTitle between", value1, value2, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleNotBetween(String value1, String value2) {
            addCriterion("FTitle not between", value1, value2, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFfilepathIsNull() {
            addCriterion("FFilePath is null");
            return (Criteria) this;
        }

        public Criteria andFfilepathIsNotNull() {
            addCriterion("FFilePath is not null");
            return (Criteria) this;
        }

        public Criteria andFfilepathEqualTo(String value) {
            addCriterion("FFilePath =", value, "ffilepath");
            return (Criteria) this;
        }

        public Criteria andFfilepathNotEqualTo(String value) {
            addCriterion("FFilePath <>", value, "ffilepath");
            return (Criteria) this;
        }

        public Criteria andFfilepathGreaterThan(String value) {
            addCriterion("FFilePath >", value, "ffilepath");
            return (Criteria) this;
        }

        public Criteria andFfilepathGreaterThanOrEqualTo(String value) {
            addCriterion("FFilePath >=", value, "ffilepath");
            return (Criteria) this;
        }

        public Criteria andFfilepathLessThan(String value) {
            addCriterion("FFilePath <", value, "ffilepath");
            return (Criteria) this;
        }

        public Criteria andFfilepathLessThanOrEqualTo(String value) {
            addCriterion("FFilePath <=", value, "ffilepath");
            return (Criteria) this;
        }

        public Criteria andFfilepathLike(String value) {
            addCriterion("FFilePath like", value, "ffilepath");
            return (Criteria) this;
        }

        public Criteria andFfilepathNotLike(String value) {
            addCriterion("FFilePath not like", value, "ffilepath");
            return (Criteria) this;
        }

        public Criteria andFfilepathIn(List<String> values) {
            addCriterion("FFilePath in", values, "ffilepath");
            return (Criteria) this;
        }

        public Criteria andFfilepathNotIn(List<String> values) {
            addCriterion("FFilePath not in", values, "ffilepath");
            return (Criteria) this;
        }

        public Criteria andFfilepathBetween(String value1, String value2) {
            addCriterion("FFilePath between", value1, value2, "ffilepath");
            return (Criteria) this;
        }

        public Criteria andFfilepathNotBetween(String value1, String value2) {
            addCriterion("FFilePath not between", value1, value2, "ffilepath");
            return (Criteria) this;
        }

        public Criteria andFfiletitleIsNull() {
            addCriterion("FFileTitle is null");
            return (Criteria) this;
        }

        public Criteria andFfiletitleIsNotNull() {
            addCriterion("FFileTitle is not null");
            return (Criteria) this;
        }

        public Criteria andFfiletitleEqualTo(String value) {
            addCriterion("FFileTitle =", value, "ffiletitle");
            return (Criteria) this;
        }

        public Criteria andFfiletitleNotEqualTo(String value) {
            addCriterion("FFileTitle <>", value, "ffiletitle");
            return (Criteria) this;
        }

        public Criteria andFfiletitleGreaterThan(String value) {
            addCriterion("FFileTitle >", value, "ffiletitle");
            return (Criteria) this;
        }

        public Criteria andFfiletitleGreaterThanOrEqualTo(String value) {
            addCriterion("FFileTitle >=", value, "ffiletitle");
            return (Criteria) this;
        }

        public Criteria andFfiletitleLessThan(String value) {
            addCriterion("FFileTitle <", value, "ffiletitle");
            return (Criteria) this;
        }

        public Criteria andFfiletitleLessThanOrEqualTo(String value) {
            addCriterion("FFileTitle <=", value, "ffiletitle");
            return (Criteria) this;
        }

        public Criteria andFfiletitleLike(String value) {
            addCriterion("FFileTitle like", value, "ffiletitle");
            return (Criteria) this;
        }

        public Criteria andFfiletitleNotLike(String value) {
            addCriterion("FFileTitle not like", value, "ffiletitle");
            return (Criteria) this;
        }

        public Criteria andFfiletitleIn(List<String> values) {
            addCriterion("FFileTitle in", values, "ffiletitle");
            return (Criteria) this;
        }

        public Criteria andFfiletitleNotIn(List<String> values) {
            addCriterion("FFileTitle not in", values, "ffiletitle");
            return (Criteria) this;
        }

        public Criteria andFfiletitleBetween(String value1, String value2) {
            addCriterion("FFileTitle between", value1, value2, "ffiletitle");
            return (Criteria) this;
        }

        public Criteria andFfiletitleNotBetween(String value1, String value2) {
            addCriterion("FFileTitle not between", value1, value2, "ffiletitle");
            return (Criteria) this;
        }

        public Criteria andFpictitleIsNull() {
            addCriterion("FPicTitle is null");
            return (Criteria) this;
        }

        public Criteria andFpictitleIsNotNull() {
            addCriterion("FPicTitle is not null");
            return (Criteria) this;
        }

        public Criteria andFpictitleEqualTo(String value) {
            addCriterion("FPicTitle =", value, "fpictitle");
            return (Criteria) this;
        }

        public Criteria andFpictitleNotEqualTo(String value) {
            addCriterion("FPicTitle <>", value, "fpictitle");
            return (Criteria) this;
        }

        public Criteria andFpictitleGreaterThan(String value) {
            addCriterion("FPicTitle >", value, "fpictitle");
            return (Criteria) this;
        }

        public Criteria andFpictitleGreaterThanOrEqualTo(String value) {
            addCriterion("FPicTitle >=", value, "fpictitle");
            return (Criteria) this;
        }

        public Criteria andFpictitleLessThan(String value) {
            addCriterion("FPicTitle <", value, "fpictitle");
            return (Criteria) this;
        }

        public Criteria andFpictitleLessThanOrEqualTo(String value) {
            addCriterion("FPicTitle <=", value, "fpictitle");
            return (Criteria) this;
        }

        public Criteria andFpictitleLike(String value) {
            addCriterion("FPicTitle like", value, "fpictitle");
            return (Criteria) this;
        }

        public Criteria andFpictitleNotLike(String value) {
            addCriterion("FPicTitle not like", value, "fpictitle");
            return (Criteria) this;
        }

        public Criteria andFpictitleIn(List<String> values) {
            addCriterion("FPicTitle in", values, "fpictitle");
            return (Criteria) this;
        }

        public Criteria andFpictitleNotIn(List<String> values) {
            addCriterion("FPicTitle not in", values, "fpictitle");
            return (Criteria) this;
        }

        public Criteria andFpictitleBetween(String value1, String value2) {
            addCriterion("FPicTitle between", value1, value2, "fpictitle");
            return (Criteria) this;
        }

        public Criteria andFpictitleNotBetween(String value1, String value2) {
            addCriterion("FPicTitle not between", value1, value2, "fpictitle");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_contract
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 11 10:50:18 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_contract
     *
     * @mbggenerated Thu Jul 11 10:50:18 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = "t_contract."+condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = "t_contract."+condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = "t_contract."+condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}